### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by colindaven** [nanoporetech/megalodon#1]
Hi,

I've had quite a few goes at the install and ironed out a few issues.

On my end behind a Univ proxy, `git+http` works a lot better than `git+git` .

Taiyaki seems to be happier if both `torch` and `pytest` are installed prior to installation, in addition to `cython` and `numpy`.

I should note megalodon itself is the next install step after taiyaki.

I can't work out this error though, do you have suggestions ? OS=Ubuntu 1604

Thanks

TASK [Install pip taiyaki] *************************************************************************************************************************************
fatal: [172.24.8.22]: FAILED! => {"changed": false, "cmd": ["/home/rcug/.local/bin/pip3", "install", "--user", "git+http://github.com/nanoporetech/taiyaki.git"], "msg": "stdout: Collecting git+http://github.com/nanoporetech/taiyaki.git\n  Cloning http://github.com/nanoporetech/taiyaki.git to ./pip-req-build-gx3opexs\n\n:stderr:   Running command git clone -q http://github.com/nanoporetech/taiyaki.git /tmp/pip-req-build-gx3opexs\n    ERROR: Complete output from command python setup.py egg_info:\n    ERROR: Compiling taiyaki/squiggle_match/squiggle_match.pyx because it changed.\n    Compiling taiyaki/ctc/ctc.pyx because it changed.\n    [1/2] Cythonizing taiyaki/ctc/ctc.pyx\n    [2/2] Cythonizing taiyaki/squiggle_match/squiggle_match.pyx\n    \n    Installed /tmp/pip-req-build-gx3opexs/.eggs/pytest_xdist-1.29.0-py3.5.egg\n    Searching for pytest-runner\n    Reading https://pypi.python.org/simple/pytest-runner/\n    Best match: pytest-runner 5.1\n    Downloading https://files.pythonhosted.org/packages/d9/6d/4b41a74b31720e25abd4799be72d54811da4b4d0233e38b75864dcc1f7ad/pytest-runner-5.1.tar.gz#sha256=25a013c8d84f0ca60bb01bd11913a3bcab420f601f0f236de4423074af656e7a\n    Processing pytest-runner-5.1.tar.gz\n    Writing /tmp/easy_install-uo35u53s/pytest-runner-5.1/setup.cfg\n    Running pytest-runner-5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-uo35u53s/pytest-runner-5.1/egg-dist-tmp-jm9ja8nu\n    /home/rcug/.local/lib/python3.5/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-req-build-gx3opexs/taiyaki/ctc/ctc.pyx\n      tree = Parsing.p_module(s, pxd, full_module_name)\n    /home/rcug/.local/lib/python3.5/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-req-build-gx3opexs/taiyaki/squiggle_match/squiggle_match.pyx\n      tree = Parsing.p_module(s, pxd, full_module_name)\n    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'\n      warnings.warn(msg)\n    zip_safe flag not set; analyzing archive contents...\n    Moving pytest_runner-5.1-py3.5.egg to /tmp/pip-req-build-gx3opexs/.eggs\n    \n    Installed /tmp/pip-req-build-gx3opexs/.eggs/pytest_runner-5.1-py3.5.egg\n    Searching for pytest-forked\n    Reading https://pypi.python.org/simple/pytest-forked/\n    Best match: pytest-forked 1.0.2\n    Downloading https://files.pythonhosted.org/packages/30/be/cb5dc4f0fa5ba121943305f4f235dc1a30fae53daac20094ab89f4618578/pytest-forked-1.0.2.tar.gz#sha256=d352aaced2ebd54d42a65825722cb433004b4446ab5d2044851d9cc7a00c9e38\n    Processing pytest-forked-1.0.2.tar.gz\n    Writing /tmp/easy_install-fle6byba/pytest-forked-1.0.2/setup.cfg\n    Running pytest-forked-1.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-fle6byba/pytest-forked-1.0.2/egg-dist-tmp-30bu5r5s\n    warning: no files found matching 'README.txt'\n    no previously-included directories found matching '.git'\n    creating /tmp/pip-req-build-gx3opexs/.eggs/pytest_forked-1.0.2-py3.5.egg\n    Extracting pytest_forked-1.0.2-py3.5.egg to /tmp/pip-req-build-gx3opexs/.eggs\n    \n    Installed /tmp/pip-req-build-gx3opexs/.eggs/pytest_forked-1.0.2-py3.5.egg\n    Searching for execnet>=1.1\n    Reading https://pypi.python.org/simple/execnet/\n    Best match: execnet 1.6.0\n    Downloading https://files.pythonhosted.org/packages/fe/9c/215c0b6a82a6b01a89d46559f401045aba2e166a91e545c16960e2bb62df/execnet-1.6.0.tar.gz#sha256=752a3786f17416d491f833a29217dda3ea4a471fc5269c492eebcee8cc4772d3\n    Processing execnet-1.6.0.tar.gz\n    Writing /tmp/easy_install-c8ute6tx/execnet-1.6.0/setup.cfg\n    Running execnet-1.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-c8ute6tx/execnet-1.6.0/egg-dist-tmp-62zpijii\n    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'\n      warnings.warn(msg)\n    zip_safe flag not set; analyzing archive contents...\n    execnet.script.__pycache__.socketserverservice.cpython-35: module references __file__\n    execnet.__pycache__.gateway_bootstrap.cpython-35: module references __file__\n    execnet.__pycache__.gateway_bootstrap.cpython-35: module MAY be using inspect.getsource\n    execnet.__pycache__.gateway.cpython-35: module references __file__\n    execnet.__pycache__.gateway.cpython-35: module MAY be using inspect.getsource\n    execnet.__pycache__.gateway.cpython-35: module MAY be using inspect.getsourcefile\n    creating /tmp/pip-req-build-gx3opexs/.eggs/execnet-1.6.0-py3.5.egg\n    Extracting execnet-1.6.0-py3.5.egg to /tmp/pip-req-build-gx3opexs/.eggs\n    \n    Installed /tmp/pip-req-build-gx3opexs/.eggs/execnet-1.6.0-py3.5.egg\n    Searching for apipkg>=1.4\n    Reading https://pypi.python.org/simple/apipkg/\n    Best match: apipkg 1.5\n    Downloading https://files.pythonhosted.org/packages/a8/af/07a13b1560ebcc9bf4dd439aeb63243cbd8d374f4f328691470d6a9b9804/apipkg-1.5.tar.gz#sha256=37228cda29411948b422fae072f57e31d3396d2ee1c9783775980ee9c9990af6\n    Processing apipkg-1.5.tar.gz\n    Writing /tmp/easy_install-qwhyslib/apipkg-1.5/setup.cfg\n    Running apipkg-1.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-qwhyslib/apipkg-1.5/egg-dist-tmp-v9oysguu\n    warning: no previously-included files found matching 'pyproject.toml'\n    \n    Installed /tmp/easy_install-qwhyslib/apipkg-1.5/.eggs/setuptools-41.0.1-py3.5.egg\n    Searching for setuptools_scm\n    Reading https://pypi.python.org/simple/setuptools_scm/\n    Best match: setuptools-scm 3.3.3\n    Downloading https://files.pythonhosted.org/packages/38/d8/3789eb77845f8700bd12943835fdbd79b693c2f009cdcb985d7d33884f6c/setuptools_scm-3.3.3-py3.5.egg#sha256=38c714af0f04999f12c419b39bdae9969ebe94af40b230b0999afb5004a8deab\n    Processing setuptools_scm-3.3.3-py3.5.egg\n    Moving setuptools_scm-3.3.3-py3.5.egg to /tmp/easy_install-qwhyslib/apipkg-1.5/.eggs\n    \n    Installed /tmp/easy_install-qwhyslib/apipkg-1.5/.eggs/setuptools_scm-3.3.3-py3.5.egg\n    Traceback (most recent call last):\n      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2237, in resolve\n        return functools.reduce(getattr, self.attrs, module)\n    AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'\n    \n    During handling of the above exception, another exception occurred:\n    \n    Traceback (most recent call last):\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 154, in save_modules\n        yield saved\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 195, in setup_context\n        yield\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 243, in run_setup\n        DirectorySandbox(setup_dir).run(runner)\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 273, in run\n        return func()\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 242, in runner\n        _execfile(setup_script, ns)\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 46, in _execfile\n        exec(code, globals, locals)\n      File \"/tmp/easy_install-qwhyslib/apipkg-1.5/setup.py\", line 53, in <module>\n        name='taiyaki',\n      File \"/tmp/easy_install-qwhyslib/apipkg-1.5/setup.py\", line 48, in main\n        if any([cmd in sys.argv for cmd in [\"install\", \"build\", \"build_clib\", \"build_ext\", \"bdist_wheel\"]]):\n      File \"/usr/lib/python3.5/distutils/core.py\", line 108, in setup\n        _setup_distribution = dist = klass(attrs)\n      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 272, in __init__\n        _Distribution.__init__(self,attrs)\n      File \"/usr/lib/python3.5/distutils/dist.py\", line 281, in __init__\n        self.finalize_options()\n      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 327, in finalize_options\n        ep.load()(self, ep.name, value)\n      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2229, in load\n        return self.resolve()\n      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2239, in resolve\n        raise ImportError(str(exc))\n    ImportError: module 'setuptools.dist' has no attribute 'check_specifier'\n    \n    During handling of the above exception, another exception occurred:\n    \n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"/tmp/pip-req-build-gx3opexs/setup.py\", line 84, in <module>\n        scripts=[x for x in glob('bin/*.py')],\n      File \"/usr/lib/python3.5/distutils/core.py\", line 108, in setup\n        _setup_distribution = dist = klass(attrs)\n      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 269, in __init__\n        self.fetch_build_eggs(attrs['setup_requires'])\n      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 313, in fetch_build_eggs\n        replace_conflicting=True,\n      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 826, in resolve\n        dist = best[req.key] = env.best_match(req, ws, installer)\n      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 1092, in best_match\n        return self.obtain(req, installer)\n      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 1104, in obtain\n        return installer(requirement)\n      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 380, in fetch_build_egg\n        return cmd.easy_install(req)\n      File \"/usr/lib/python3/dist-packages/setuptools/command/easy_install.py\", line 663, in easy_install\n        return self.install_item(spec, dist.location, tmpdir, deps)\n      File \"/usr/lib/python3/dist-packages/setuptools/command/easy_install.py\", line 693, in install_item\n        dists = self.install_eggs(spec, download, tmpdir)\n      File \"/usr/lib/python3/dist-packages/setuptools/command/easy_install.py\", line 873, in install_eggs\n        return self.build_and_install(setup_script, setup_base)\n      File \"/usr/lib/python3/dist-packages/setuptools/command/easy_install.py\", line 1101, in build_and_install\n        self.run_setup(setup_script, setup_base, args)\n      File \"/usr/lib/python3/dist-packages/setuptools/command/easy_install.py\", line 1087, in run_setup\n        run_setup(setup_script, args)\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 246, in run_setup\n        raise\n      File \"/usr/lib/python3.5/contextlib.py\", line 77, in __exit__\n        self.gen.throw(type, value, traceback)\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 195, in setup_context\n        yield\n      File \"/usr/lib/python3.5/contextlib.py\", line 77, in __exit__\n        self.gen.throw(type, value, traceback)\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 166, in save_modules\n        saved_exc.resume()\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 141, in resume\n        six.reraise(type, exc, self._tb)\n      File \"/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py\", line 685, in reraise\n        raise value.with_traceback(tb)\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 154, in save_modules\n        yield saved\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 195, in setup_context\n        yield\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 243, in run_setup\n        DirectorySandbox(setup_dir).run(runner)\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 273, in run\n        return func()\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 242, in runner\n        _execfile(setup_script, ns)\n      File \"/usr/lib/python3/dist-packages/setuptools/sandbox.py\", line 46, in _execfile\n        exec(code, globals, locals)\n      File \"/tmp/easy_install-qwhyslib/apipkg-1.5/setup.py\", line 53, in <module>\n        name='taiyaki',\n      File \"/tmp/easy_install-qwhyslib/apipkg-1.5/setup.py\", line 48, in main\n        if any([cmd in sys.argv for cmd in [\"install\", \"build\", \"build_clib\", \"build_ext\", \"bdist_wheel\"]]):\n      File \"/usr/lib/python3.5/distutils/core.py\", line 108, in setup\n        _setup_distribution = dist = klass(attrs)\n      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 272, in __init__\n        _Distribution.__init__(self,attrs)\n      File \"/usr/lib/python3.5/distutils/dist.py\", line 281, in __init__\n        self.finalize_options()\n      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 327, in finalize_options\n        ep.load()(self, ep.name, value)\n      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2229, in load\n        return self.resolve()\n      File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2239, in resolve\n        raise ImportError(str(exc))\n    ImportError: module 'setuptools.dist' has no attribute 'check_specifier'\n    ----------------------------------------\nERROR: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-req-build-gx3opexs/\n"}

**Comment by marcus1487** [comment]
I would suggest trying a full taiyaki installation (`git clone https://github.com/nanoporetech/taiyaki & cd taiyaki & make install`). This seems to be an issue with the particular environment. It looks like there might be another taiyaki installation interfering with this installation, but that is just a guess. Note that after a full taiyaki installation the prepared virtual env will need to be activated (via `source taiyaki/venv/bin/activate`).

**Comment by colindaven** [comment]
Thanks. That seems to have helped. I could install both taiyaki and megalodon correctly.

One more thing though - even though I can import taiyaki when using the sourced virtual environment python directly, megalodon throws an import error. I would be grateful for any ideas here, thanks.

```
(taiyaki) rcug@hpc01:/ngsssd1/rcug/ONT_thermo_2019/analysis_hac$ megalodon --mappings-format bam --reference /lager2/rcug/seqres/metagenref/bakiMix_2019/Cellulomonas_Fervidobacterium_Liberibacter.fasta --processes 24 ../20190620_1055_MN32001_FAK85862_bf499a51/fast5/
Traceback (most recent call last):
  File "/home/rcug/.local/lib/python3.5/site-packages/megalodon/backends.py", line 44, in _load_taiyaki_model
    from taiyaki.helpers import load_model as load_taiyaki_model
ImportError: No module named 'taiyaki'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rcug/.local/bin/megalodon", line 10, in <module>
    sys.exit(_main())
  File "/home/rcug/.local/lib/python3.5/site-packages/megalodon/megalodon.py", line 974, in _main
    args.max_concurrent_chunks)
  File "/home/rcug/.local/lib/python3.5/site-packages/megalodon/backends.py", line 124, in __init__
    self._load_taiyaki_model()
  File "/home/rcug/.local/lib/python3.5/site-packages/megalodon/backends.py", line 49, in _load_taiyaki_model
    logger.error(
UnboundLocalError: local variable 'logger' referenced before assignment


(taiyaki) rcug@hpc01:/ngsssd1/rcug/ONT_thermo_2019/analysis_hac$ python
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taiyaki
>>> 
```

**Comment by marcus1487** [comment]
megalodon must be installed within the taiyaki virtual environment. My guess is that megalodon was installed in the root environment and is thus not linked to the same python and thus cannot find the taiyaki installation.

**Comment by colindaven** [comment]
Great, thank you.

For others: for me a 
` pip install git+https://github.com/nanoporetech/megalodon.git`

from within the installed and activated taiyaki venv worked.
