### ISSUE TITLE
guppy and pyguppy point verisons don't match

### ISSUE THREAD

**Issue by timp0** [nanoporetech/megalodon#102]
Installation problem - following the installation procedures, when running I get an error that:

"WARNING: Guppy and pyguppy point versions do not match. This could lead to a failure. Install matching pyguppy version via `pip install ont-pyguppy-client-lib==4.4.2`" - but this doesn't work because - presumably pyguppy doesn't have a 4.4.2 client lib. 

A search suggests pyguppyclient might be the latest version, but then megalodon doesn't seem to recognize it?

**Comment by marcus1487** [comment]
My best guess is that there is a slight delay in the submission of the new client version to pypi. @fbrennen ?

The patch point versions are usually compatible. You should be okay with 4.4.1 pyguppy client version.

**Comment by timp0** [comment]
Awesome
