### ISSUE TITLE
PyGuppy & Guppy Updates

### ISSUE THREAD

**Issue by ChristianJP** [nanoporetech/megalodon#103]
Hello,

I am currently trying to run megalodon however the log:

DBG 14:36:06 : Guppy version: "4.4.2" --- MainProcess-MainThread backends.py:500
DBG 14:36:06 : Pyguppy version: "4.4.1" --- MainProcess-MainThread backends.py:501
DBG 14:36:06 : Guppy and pyguppy point versions do not match

This Suggests:
1. I need to either upgrade PyGuppy 4.4.2- this is not possible as the latest version 4.4.1.
2. Or install a previous version of Guppy - does not appear as on option via nanoporetech community.

Please advise on this issue, thankyou very much!

**Comment by PanZiwei** [comment]
Hi I have encountered the issue before. You have to keep Guppy and PyGuppy with the same version.
So I think you can downgrade to Guppy 4.4.1 since it seems that Pyguppy didn't release the 4.4.2 version:https://pypi.org/project/ont-pyguppy-client-lib/#history

**Comment by ChristianJP** [comment]
@PanZiwei  Where did you find the downgraded version of guppy? ^ * please see 2 - I tried this but it does not appear as an option available

**Comment by PanZiwei** [comment]
@ChristianJP 
I think they just released the latest PyGuppy v4.2.2
