### ISSUE TITLE
[megalodon_extras aggregate] Read processing rates decreasing with large input

### ISSUE THREAD

**Issue by idelvall** [nanoporetech/megalodon#106]
Hi, were are trying to run this command `/bin/sh -c megalodon_extras aggregate run  --processes 7 --outputs mods --megalodon-directory /batchx/megalodonDir/ --mod-aggregate-method binary_threshold --mod-binary-threshold 0.8 --mod-output-formats bedmethyl modvcf wiggle  --output-suffix re_aggregated` with an input db file of 134 GB.

We have noticed that the reads processing rate went down from  around 60K per-read calls/s initially, to 11 per-read calls/s  after 14h of runtime.

At that moment we took these screenshots:
![Screenshot from 2021-02-26 12-45-22](https://user-images.githubusercontent.com/5653455/109300898-723bfb00-7837-11eb-9795-5946e8357708.png)

![Screenshot from 2021-02-26 11-55-55](https://user-images.githubusercontent.com/5653455/109300996-913a8d00-7837-11eb-8431-881766904252.png)

Notice that the latest aggregate subprocess is taking almost 100% of the memory and lacks any running thread.

Then after a while we took this new snapshot, and that process is now in zombie state:

![Screenshot from 2021-02-26 13-26-08](https://user-images.githubusercontent.com/5653455/109301463-4cfbbc80-7838-11eb-9d91-d50ef0bceed7.png)

Also we observed that there haven't been any updates to the output files during the last hour and a half.

![Screenshot from 2021-02-26 13-31-36](https://user-images.githubusercontent.com/5653455/109301414-37869280-7838-11eb-8ba4-ec8416246185.png)

My impression is that we hitting a OOM and the kernel reaper is killing that particular thread, but the parent is ignoring this signal and continuing working instead of exiting itself and propagating the error up.

What do you think @marcus1487 ?
Also, what are the memory requirements for this tool, based on the input data?

Thanks!

**Comment by marcus1487** [comment]
This certainly looks like a memory leak. This command should not be taking this much memory. I'll have a look at the memory error.

The megalodon workers are spawned as daemon processes, so they will not kill the parent process. This is intended to save a run with a few unexpected errors, but may be leading to this unfortunate setting. I'll have a look at this as well.

**Comment by marcus1487** [comment]
The latest release (2.3.0) should address this slowing. Please reopen this issue if this is not the case.
