### ISSUE TITLE
WARNING: Error inserting modified base scores into database.

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/megalodon#11]
Using megalodon made from cloning github repository and GPU calling. Basecalling continues when error happens.

Command line: nohup nice megalodon fastq/workspace/ --outputs basecalls mappings per_read_mods --write-mods-text --mod-motif Z CG 0 --output-directory megalodon/ --mappings-format bam --reference /mnt/ix1/Resources/GenomeRef/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa --devices 2

In the nohup.out I get: ******************** WARNING: Error inserting modified base scores into database. See log debug output for error details. ********************

And in the log.out I see: 
DBG: megalodon: 197: Successfully processed read 005b4e07-9eca-4126-b830-b4cc9eca6ee8
DBG: megalodon: 189: Analyzing read 005c5dd8-06e4-4d4f-965e-7520c42b44c3
DBG: megalodon: 197: Successfully processed read 005c5dd8-06e4-4d4f-965e-7520c42b44c3
DBG: megalodon: 189: Analyzing read 005d5a58-1224-4c2e-837d-7708ce5bfe9e
DBG: megalodon: 208: Incomplete processing for read 005d5a58-1224-4c2e-837d-7708ce5bfe9e ::: No alignment
DBG: megalodon: 189: Analyzing read 0081f81f-1c9e-4997-b17c-6eaa90e72566
DBG: megalodon: 197: Successfully processed read 0081f81f-1c9e-4997-b17c-6eaa90e72566
DBG: megalodon: 189: Analyzing read 00880d64-7463-4d6a-a7c2-2a6af97c4aca
DBG: megalodon: 197: Successfully processed read 00880d64-7463-4d6a-a7c2-2a6af97c4aca
DBG: megalodon: 189: Analyzing read 00884bde-63e5-4eb7-b496-5a24f37d2e17
DBG: mods: 538: Error inserting modified base scores into database: tuple index out of range
Traceback (most recent call last):
  File "/home/billylau/.conda/envs/megalodon/lib/python3.6/site-packages/megalodon/mods.py", line 527, in store_mod_call
    mods_db.insert_read_scores(r_mod_scores, read_id, chrm, strand)
  File "/home/billylau/.conda/envs/megalodon/lib/python3.6/site-packages/megalodon/mods.py", line 237, in insert_read_scores
    pos_ids = self.get_pos_ids_or_insert(r_mod_scores, chrm_id, strand)
  File "/home/billylau/.conda/envs/megalodon/lib/python3.6/site-packages/megalodon/mods.py", line 165, in get_pos_ids_or_insert
    r_pos = tuple(zip(*r_mod_scores))[0]
IndexError: tuple index out of range

**Comment by marcus1487** [comment]
This is a bug due to reads that do not overlap any modified bases or sequence variants. I have pushed a fix to this issue and it should be resolved now.

Thank you very much for the bug report!
