### ISSUE TITLE
[question] 6mA, 5mC & 5hmC at the same time?

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/megalodon#110]
Hi, I'm pretty new to methylation calling, so forgive me if this sounds like a noob question :-)

I was wondering if I can call all 3 types at the same time.

I was looking at the rerio models mentioned, but there is either:

res_dna_r941_min_modbases_5mC_5hmC_CpG_v001.cfg (**5hmC & 5mC in all context)**
res_dna_r941_min_modbases-all-context_v001 (**5mC & 6mA in all contexts**)

There doesn't seem to be one that does all 3. Would I have to run megalodon twice to get all 3 types?
Also, what would be the correct --mod-motif syntax for the respective model?
Cheers

**Comment by marcus1487** [comment]
There is not currently a model with optimal performance which can detect 5mC, 5hmC and 6mA at the same time. We have found, at least in initial efforts, that adding more modified bases to a basecalling model degrades the performance on the modified base models. In fact for the highest accuracy 5mC calls it is currently recommended to use the 5mC all-context model (e.g. `res_dna_r941_min_modbases_5mC_v001.cfg`). This model likely collapses some 5hmC calls into 5mC calls, but makes the distinction between 5mC+5hmC calls and canonical calls much more accurately than the 5mC+5hmC model. We are working towards models with the highest accuracy modified base calls including several modified bases at the same time, but the current recommendation is to perform multiple basecalling runs with the modified base models of interest.

**Comment by JWDebler** [comment]
Thank you. I'll run them individually then.
