### ISSUE TITLE
 running megalodon on supercomputer

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/megalodon#111]
Hi, 
I am trying to run megalodon on a supercomputer with GPU nodes. 
I used a separate megalodon and guppy singularity images, but I am getting an error related to pyGuppy. I am not sure where that needs to be installed.

my slurm script looks like this

```
module load singularity
module load cuda

srun -n 1 --export=all --gres=gpu:1 \
singularity exec --nv megalodon_2.2.10--py38h0213d0e_0.sif megalodon fast5_files \
--guppy-params "-d ./rerio/basecall_models/" \
--guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg \
--outputs mod_mappings mods \
--reference genome.fasta \
--mod-motif m CG 0 \
--guppy-server-path "singularity exec --nv guppy-gpu_4.2.2.sif guppy_basecall_server" \
--output-directory megalodon_output \
--devices 0
```

I am not really sure if supplying another singularity command as the --guppy-server-path works.

The error I get is this:

```
[14:11:22] Running Megalodon version 2.2.10
[14:11:22] Loading guppy basecalling backend
Traceback (most recent call last):
  File "/usr/local/bin/megalodon", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.8/site-packages/megalodon/__main__.py", line 444, in _main
    megalodon._main(args)
  File "/usr/local/lib/python3.8/site-packages/megalodon/megalodon.py", line 1249, in _main
    model_info = backends.ModelInfo(backend_params, args.processes)
  File "/usr/local/lib/python3.8/site-packages/megalodon/backends.py", line 687, in __init__
    self._load_pyguppy()
  File "/usr/local/lib/python3.8/site-packages/megalodon/backends.py", line 672, in _load_pyguppy
    from pyguppy_client_lib.pyclient import PyGuppyClient
ModuleNotFoundError: No module named 'pyguppy_client_lib'
srun: error: t022: task 0: Exited with exit code 1
```

Cheers

**Comment by marcus1487** [comment]
I don't think that the singularity command will work for the `--guppy-server-path`. This will not be executed, but instead passed as a path to megalodon. The actual path should be supplied here. But I don't think this is the core issue. How was megalodon installed? The environment appears to be missing the `ont_pyguppy_client_lib` python package dependency.

**Comment by JWDebler** [comment]
It wasn't installed, I am using [this docker container](https://quay.io/repository/biocontainers/megalodon?tab=tags)

**Comment by marcus1487** [comment]
I'm not sure who maintains these docker images, but I would suggest raising this issue there. This appears to be an issue with the megalodon install within this image. `ont_pyguppy_client_lib` is a pre-requisite for megalodon and should be installed when `megalodon` is installed.
