### ISSUE TITLE
Invalid Character in sequence

### ISSUE THREAD

**Issue by timp0** [nanoporetech/megalodon#112]
So I'm getting a new issue:

Running this on GPU:

!megalodon subset_f5 --processes 10 --outputs mappings variants variant_mappings per_read_variants \
    --reference {ref} --variant-filename {variants} --output-directory try2 \
    --guppy-server-path /usr/bin/guppy_basecall_server --reads-per-guppy-batch 10 --devices 0 

I am getting an issue of:

67.0% (   5898 reads) : Invalid character in sequence     

What . . . does this mean in this context? I'm only passing in fast5 and vcf, so I'm not sure what possible sequence it's referring to?

Log attached.

[log.txt](https://github.com/nanoporetech/megalodon/files/6091468/log.txt)

**Comment by marcus1487** [comment]
This error indicates that the reference has a non-ACGT character in the range around a variant it is attempting to process. Without the context bases (see `--variant-context-bases` option in `megalodon --help-long`) megalodon cannot call the variant of interest. Megalodon proposes the reference sequence and the sequence containing the variants from the VCF. The code to compute the likelihood of these two sequences given the basecaller output is not robust to unknown bases.

**Comment by timp0** [comment]
But . . . I don't have any unknown bases in there.  It's just chrM from hg38.  
[chrM.sl.hg38.fa.gz](https://github.com/nanoporetech/megalodon/files/6240339/chrM.sl.hg38.fa.gz)

**Comment by marcus1487** [comment]
Any chance you can share the variant file? I'll have a look in the code to see if there might be another condition triggering this output.

**Comment by timp0** [comment]
Yup heck, if you really want I can share the 10k fast5 I subset too, it's only 2.1GB

**Comment by timp0** [comment]
Here's the VCF, had to gzip to be github compatible
[variant.calls.2.vcf.gz](https://github.com/nanoporetech/megalodon/files/6243971/variant.calls.2.vcf.gz)

**Comment by timp0** [comment]
Ohhhh - I found hg38 in chrM does have a single N in there - that would throw it off huh?

**Comment by marcus1487** [comment]
Not sure how I missed that yesterday as well. Yes, any read mapping over that base will not be able to produce variants calls in that region (within the specified range for SNPs and indels by `--variant-context-bases`; default 15 bases either side for SNPs and 30 for indels). I thought the rest of the read should have been called, but may have only fixed that in the mods output. I'll reopen the issue. Sequence variant code in megalodon has fallen out of maintenance a bit.

**Comment by marcus1487** [comment]
Issue should be resolved in the latest release. Please re-open if this issue persists.
