### ISSUE TITLE
[question] interpreting input/output queue

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/megalodon#116]
Hi, 
I just got megalodon running on our HPC. I now need some help interpreting the queue capacity. This is what it shows at the moment:

```
Full output or empty input queues indicate I/O bottleneck

      | 19102/347368 [22:20<6:23:54, 14.25reads/s, samples/s=7.82e+5]
 input queue capacity extract_signal      : 100%|██████████| 10000/10000
output queue capacity per_read_mods       :   0%|          | 5/10000
```

Does that mean that my input queue is full and not processing reads fast enough?

I am running megalodon with default values at the moment, and am not sure which arguments to tweak.

Cheers

**Comment by marcus1487** [comment]
This is the desired state during a megalodon run. The basecalling backend is generally the bottleneck for a megalodon run. The hope is that megalodon will run just as fast as the standalone guppy basecaller. This output is intended to help diagnose input/output bottlenecks which are not expected in general.

This output indicates that signal has been read from FAST5 files and is waiting for the basecall workers to retrieve this data and return results. The empty per_read_mods queue indicates that all (but 5) reads worth of modified base results have been received and written to disk. If the input queue is empty this indicates that the signal cannot be extracted from the FAST5 file fast enough. If the per_read_mods queue starts to fill up this indicates that the results cannot be written to disk quickly enough.

I hope this helps understanding the megalodon output, but please post any additional questions.
