### ISSUE TITLE
megalodon_extras merge aggregated_modified_bases consumes excessive RAM

### ISSUE THREAD

**Issue by MrKevinDC** [nanoporetech/megalodon#117]
Hi @marcus1487, we have been running megalodon on small subsets with the aim of merging them later and we have been successful obtaining their results. `megalodon_extras merge modified_bases` works fine.

However, when running `megalodon_extras merge aggregated_modified_bases` on 16 files of a total size of 122.4 GB, even when sorting as stated in the documentation (`sort -k1V -k2n megalodon_results/modified_bases.5mC.bed > megalodon_results/modified_bases.5mC.sorted.bed`) and setting the flag `--sorted-inputs`, we have not noticed any reduction in memory consumption, the run gets killed at the 3rd file, even though memory use should be minimal when files are sorted. We are using 40GB of RAM. 

Is there something we could do aside from greatly increasing the RAM size for accommodating this large RAM usage?

**Comment by marcus1487** [comment]
This is odd indeed. With the `--sorted-inputs` option the memory consumption should be very low. 

You note that the "run gets killed at the 3rd file". This indicates that the command is not actually running the sorted version of the command. Are you seeing a new progress bar for each input file? With the sorted version there should be only one progress bar indicating the number of sites processed so far.

**Comment by MrKevinDC** [comment]
Thank you for your hints Marcus, indeed we changed the way the command was passed in and it worked, `--sorted-inputs` had to go before the bedfiles, not at the end. Thank you!
Before closing this issue I'd like to point out a runtime warning we've had, see what you think of it:

```

[batchx#30393|b@b/n/m/merge-agg-modbases:0.2.8] [2021/03/11 12:22:16] Records Written: 0it [00:00, ?it/s]Records Written: 7046it [00:00, 70448.65it/s]Records Written: 18464it [00:00, 92309.96it/s]Records Written: 29882it [00:00, 96776.28it/s]Records Written: 41519it [00:00, 101569.30it/s]/usr/local/lib/python3.8/dist-packages/megalodon_extras/merge_aggregated_modified_bases.py:38: RuntimeWarning: invalid value encountered in true_divide
[batchx#30393|b@b/n/m/merge-agg-modbases:0.2.8] [2021/03/11 12:22:16]   np.around(np.array(mod_covs, dtype=int) * 100 / covs, 1))) + '\n')

```

**Comment by marcus1487** [comment]
That is odd that the `--sorted-inputs` flag would not work at the end. In a test on my machine I am seeing that this option works at the end of the command. What shell/environment are you using/in? Are you sure the command included the option (and wasn't missing a trailing newline escape slash or something)?

Thank you for flagging the warning. Megalodon outputs a fraction of 0 when all the per-read calls are filtered out, but there are still reads covering the position. I'll add a catch for this warning in the next release, but should probably consider filtering these values from the standard megalodon output.

**Comment by MrKevinDC** [comment]
Probably the `subprocess.call()` with `shell=True` I executed did not capture that flag efficiently before, that is probably my fault. I think that is all from me then, I leave up to you if you want to close the issue or leave it in until next release. Thank you for the help!

**Comment by marcus1487** [comment]
Warning has been suppressed in version 2.3.0.
