### ISSUE TITLE
Help with bioinformatic analysis of outputs

### ISSUE THREAD

**Issue by wentski** [nanoporetech/megalodon#118]
Hello,

Our lab are completely new to MinIon sequencing and have no experience of analysing the data it produces. I am trying to assess methylation of a known DNA motif using megalodon. I have, mainly through trial and error, managed to run the package and it appears to process our data successfully. At this point however, I have no idea how to interpret the output files. I can't seem to find any resources on how to interpret the data outputted by megalodon or what good outputs should look like.

At this point I think part of the problem is that I am not entirely sure what I am looking for. I am very much new to this area of bioinformatics. I ideally need a good example of a workflow, with examples of required inputs and desired outputs for this kind of analysis, and then how to analyse those outputs to determine if the motif of interest has been modified or not. Even if someone could point me in the direction of somewhere I could piece this all together, that would be great.

I feel like I have been bundling around in the dark with this for a couple of months now with little progress, so any help or guidance at all is greatly appreciated!

Many thanks,

Sam

**Comment by marcus1487** [comment]
The output files produced by megalodon are described in [the documentation here](https://nanoporetech.github.io/megalodon/file_formats.html). This page also provides links to the relevant webpages with further details on the standard formats.

Megalodon comes with a number of tools for the purpose of validating results (both per-read and aggregated by reference position) including those driven by motifs. Have a look at the documentation for these commands in [here](https://nanoporetech.github.io/megalodon/extras_validate.html). The `megalodon_extras modified_bases create_motif_bed` command may also be of interest for this sample [here](https://nanoporetech.github.io/megalodon/extras_modified_bases.html#megalodon-extras-modified-bases-create-motif-bed). The [bedtools suite of command line tools](https://bedtools.readthedocs.io/en/latest/) is invaluable for manipulating the BED files such as those produced by megalodon methylation calling.

I don't have a pointer to a specific downstream methylation analysis pipeline. This will depend on the exact goal of the analysis (e.g. differential analysis, motif detection, etc).

I hope these resources help, and please post if you have further question.

**Comment by wentski** [comment]
Hi Marcus,

Thank you for your reply, I had not spotted that particular page on the documentation so it was useful. 

After some further experimentation, I was able to process the data. Unfortunately, a majority of my reads returned "guppy server timeout". I have seen this message before and had set --guppy-timeout 300 when I ran, which I had hoped would solve this issue. (I should also mention that I am running on a CPU rather than a GPU). So my first question would be, do I need to increase the --guppy-timeout value, or is there some other issue here? For example, I've come across some tools which will only accept single-read fast5 files and multi-read files needed to be de-multiplexed first.

The run did produce some output files from a small proportion of the data (attached below). So I need to, from these files, determine if our motif of interest is modified. It will be a 6mA modification and we are sequencing from an otherwise methylation deficient strain, so no other genome modification should be present. We basically need a yes/no answer at this point, although any additional info would be useful. I have never used .bed files before and I cannot open the BAM files in IGV without an indexing file. So my second question would be, how can I go about extracting the information I need from these output files? Is this the point where I should run megalodon_extras modified_bases create_motif_bed ?

I have attached the command I used and a list of the output files in the hope that it will provide some more insight.

Many thanks again for your help,

Sam


![image](https://user-images.githubusercontent.com/78024165/110978425-481c2a00-835b-11eb-8318-d4d4b5af7468.png)
![image](https://user-images.githubusercontent.com/78024165/110978476-59653680-835b-11eb-8da1-66b4b2c8cf94.png)

**Comment by marcus1487** [comment]
For the `--guppy-timeout` error, this is an issue with the megalodon guppy interface that has arisen recently. A fix for this is coming in the next megalodon release. This should be next week. Even with this fix though the run time one CPU resources versus GPU is about 100X different. The basecalling algorithms make great use of GPU resources and it is strongly recommended that GPU resources be allocated for basecalling.

For the analysis question, have you had a look at the validate commands from megalodon linked in my previous post. These address the exact question you are referencing. Example commands and expected results can be found on the documentation page for the validation commands.

**Comment by tonperre** [comment]
I am giving a +1 for the output downstream analysis.
As I am a bit surprised not to have found any publication related to Megalodon (am I right?) I have the same feeling of walking in the dark as well!

**Comment by marcus1487** [comment]
There is not a publication linked to the methods implemented in megalodon or benchmarking results. We are focusing on improving these results further and adding more modified base models internally, so have chosen not to focus on submitting a publication. The documentation contains some of the higher level algorithm specifications (especially the [algorithm details section](https://nanoporetech.github.io/megalodon/algorithm_details.html)).

One issue with detailing modified base performance/pipelines is that there are so many different settings each with their own unique challenges. For example, bacteria generally modify all strands at a fixed set of motifs. In this setting modified base detection is generally concerned with finding these motifs. In mammalian sequencing, 5mC CpG methylation is generally the primary target, but every strand at a particular location is not necessarily modified. Identifying links (two CpG islands with linked methylation patterns) between distance regions is also of great interest in this setting.

Each setting produces a unique set of challenges and thus applying benchmarks from one does not guarantee results in another setting for modified bases. We are aiming to make as many settings as straightforward as possible with nanopore sequencing and megalodon, but appreciate that this can certainly be a hard field to navigate. 

Users providing feedback on useful pipelines or features that would be useful to add or more clearly document would be greatly helpful!

**Comment by tonperre** [comment]
Thanks Marcus 
I am indeed working in specific types of human genetics and it seems so far to be a bit off comparing to WGBS.
Do you think there's a way I could communicate with you without polluting the issues-thread of github ?
Would be much appreciated !

**Comment by marcus1487** [comment]
The new release of megalodon (2.3.0) and guppy (4.5.2), not use the most accurate models by default. This may be the reason for the discrepancy between the megalodon results and WGBS. If this issue persists please re-open this issue.
