### ISSUE TITLE
VBZ plugin is installed ERROR

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#119]
Hi everyone, I've had success running Megalodon a few times now, recently I added mod_basecalls to the outputs, and meg has started giving me this error. 

Error 
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/megalodon/fast5_io.py", line 226, in _extract_signal_worker
    fast5_fp, read_id, extract_dacs)
  File "/home/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/megalodon/backends.py", line 770, in extract_signal_info
    dacs = fast5_io.get_signal(read, scale=False)
  File "/home/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/megalodon/fast5_io.py", line 150, in get_signal
    'installed (if applicable).')
megalodon.megalodon_helper.MegaError: Error extracting raw data. Ensure VBZ plugin is installed (if applicable).`

Some more 
`OSError: Failed to read compressed raw data. VBZ compression filter (id=32020) may be missing from expected path: '/home/ec2-u
ser/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ont_fast5_api/vbz_plugin'`

These are the files present in this directory 
-rw-rw-r-- 1 ec2-user ec2-user 2900824 Mar  4 14:34 libvbz_hdf_plugin_aarch64.so
-rw-rw-r-- 1 ec2-user ec2-user  513760 Mar  4 14:34 libvbz_hdf_plugin.dylib
-rw-rw-r-- 1 ec2-user ec2-user 3403440 Mar  4 14:34 libvbz_hdf_plugin_x86_64.so
-rw-rw-r-- 1 ec2-user ec2-user  208896 Mar  4 14:34 vbz_hdf_plugin.dll

[log.txt](https://github.com/nanoporetech/megalodon/files/6150750/log.txt)

I attached the log.txt as well, please let me know if anyone has any idea whats going on! Thanks

**Comment by marcus1487** [comment]
This appears to be a corrupted FAST5 file. Note at the end of the log.txt that the first error caught is a `OSError: Can't read data (inflate() failed)`. This generally indicates that the file is corrupted. I would not guess that this has anything to do with the `mod_basecalls` output. The zvb errors are provided as this is the most common reason for the previous error, but corrupted files can lead to the same type of error as in this case.

**Comment by fidibidi** [comment]
Thanks Marcus,
Will investigate further!
Fidi
