### ISSUE TITLE
cuda0 vs cuda:0 - question

### ISSUE THREAD

**Issue by SophieS9** [nanoporetech/megalodon#120]
Hi Megalodon Team,

This is likely a naive question, but I was wondering if it would be possible to explain the differences between the cuda0 and cuda:0 parameter options for --devices. I'm running Megalodon on a GPU node with a test data set from Humans around 16G in size but it's been stuck at "MappingWorkerClosing" for several days now. I just want to make sure that I'm utilising the GPU nodes in the best way so would like a description of these parameters!

Thanks!

Sophie

**Comment by marcus1487** [comment]
There is no difference between `cuda0`, `cuda:0` or `0`. Megalodon will parse each of these into the appropriate forms for guppy. See the [actual parsing function here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/backends.py#L71) for programatic details.

As for the stall on `MappingWorkerClosing`, that certainly sounds like a bug. My best guess is that there is a worker that failed unexpectedly and that megalodon is now hanging indefinitely. The next release will include a rework of the core megalodon/guppy interface that should make these types of events more rare. I will close this issue once this next release is out, but please do reopen if this issue persists after this release.

**Comment by SophieS9** [comment]
Thanks Marcus, that's super helpful!

With regards to the MappingWorkerClosing hanging, I'm assuming the best solution is just to kill the run and start over? Is there a way of resuming so that basecalling doesn't need to be repeated?

**Comment by SophieS9** [comment]
Hi Marcus,

Just to let you know that I killed the previous run of Megalodon and started again, and once again it's hanging at the MappingWorkerClosing step - it's been there for over 80 hours now - is there any way for me to see if this is just taking a long time to complete but is still working or if it is truly hanging? None of the output files have been changed since this step began? Thanks!

**Comment by marcus1487** [comment]
Usually the log.txt file will contain some information about a stalled process (usually the communicating process will have failed). If you could post the log.txt file I could take a look to hopefully identify the core issue. I strongly suspect this is a stalled process.

**Comment by SophieS9** [comment]
Thanks Marcus, the log file is 67MB so can't attach - you should be able to view here [https://drive.google.com/file/d/1HXHtsADW_-1RPNN28wEC-Q8QyNrODrVj/view?usp=sharing](https://drive.google.com/file/d/1HXHtsADW_-1RPNN28wEC-Q8QyNrODrVj/view?usp=sharing). Just to let you know, I'm actually just testing things out with some public data before we start to collect our own data, so the files I've used are here - [https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR11047859](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR11047859). 

Here's my command, running on a slurm compute cluster:
```
megalodon --outputs basecalls mappings mod_basecalls mod_mappings mods --reference  GRCh38_latest_genomic.fna --processes 8 --output-directory $out --devices cuda0 --guppy-server-path /opt/software/uoa/2021/apps/guppy/ont-guppy-gpu_4.4.2/bin/guppy_basecall_server --guppy-timeout 60.0 --overwrite $in
```

Thanks!

**Comment by SophieS9** [comment]
Just to update on my last comment - this seems to an error with the HPC which I'm using to run the job and not specific to Megalodon!
