### ISSUE TITLE
Results Analysis 

### ISSUE THREAD

**Issue by rushup1** [nanoporetech/megalodon#123]
Hello, 

I am completely new to megalodon and have no experience analyzing the data set that is produced. I got the program to run and I am not sure how to analyze the output files. I need to determine which genes are highly methylated and create a heatmap. I am not sure to use the output files to perform further analysis. I am not sure where I can look to get understand how to interpret these results. Any help or ideas will be greatly appreciated. 

The output files I got were: 

![image](https://user-images.githubusercontent.com/81039132/112645095-849c5b00-8e1c-11eb-8651-86fc4029a4e2.png)

Thank you, 
Rush

**Comment by marcus1487** [comment]
The [megalodon documentation pages](https://nanoporetech.github.io/megalodon/file_formats.html) have a lot of information about the file formats and links to useful outside resources. In terms of downstream analysis the bedmethyl file (when setting `--outputs mods` or from the `megalodon_extras aggregate run` command) is generally the most common input for downstream methylation analysis pipelines.

The proposed analysis goal of "determine which genes are highly methylated and create a heatmap" can get a bit complicated. There are many different ways to aggregate methylation calls across reference sites. CpG islands are a common choice, but then linking those to genes is another task. There are many resources surrounding this analysis task, but I don't believe this is a "solved problem" in bioinformatics.

**Comment by rushup1** [comment]
Thank you so much. This helps a lot :)

**Comment by fidibidi** [comment]
Hey @rushup1 !!

I think I'm in a very similar boat as you... 

Did you ever find any tools that were useful for interpreting the results?

Thanks!
