### ISSUE TITLE
Guppy error in 4.5.2 causing Megalodon to crash

### ISSUE THREAD

**Issue by dgiguer** [nanoporetech/megalodon#124]
Hi, 

I've had success with installing and running Megalodon with Guppy 4.4.1, but the recently upgrading the 4.5.2 has caused a new error in the `guppy_basecall_server` backend. `guppy_basecaller` works just fine. 

```
2021-03-28 16:27:13.163858 [guppy/message] ONT Guppy basecall server software version 4.5.2+bcc53d392, client-server API version 6.0.0
log path:            megalodon_results/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  4

2021-03-28 16:27:13.163967 [guppy/info] crashpad_handler successfully launched.
2021-03-28 16:27:13.164572 [guppy/info] Listening on port 39549.
2021-03-28 16:27:13.263464 [guppy/info] CUDA device 0 (compute 7.5) initialised, memory limit 8366915584B (7998930944B free)

2021-03-28 16:27:13.301504 [guppy/error] Substitution matrix for Minalign class must be 5x5.
2021-03-28 16:27:13.301567 [guppy/warning] An error occurred initialising the basecaller. Aborting.
```

I've tried uninstalling + reinstalling with several methods (in a virtual env, using pip, upgrading minKNOW, using a conda environment), but I cannot seem to find the source of this error.  I've also tried changing the cuda input to 0, cuda:0. I can't get rid of the `Minialign` class error. 

I've tried running just the command from `/usr/bin/guppy_basecall_server -p auto -l megalodon_results/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --post_out -x cuda:0 -d rerio/rerio/basecall_models/` from `log.txt`, and the same error occurs but with no additional information: 
```
[16:35:38] Running Megalodon version 2.2.10
DBG 16:35:38 : Command: """/opt/miniconda3/bin/megalodon ./fast5s --guppy-params -d rerio/basecall_models/ --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --outputs basecalls mappings mod_mappings mods --reference final_nuclear_genome.fasta --mod-motif m CG 0 --devices cuda:0 --processes 5 --guppy-server-path /usr/bin/guppy_basecall_server --overwrite""" --- MainProcess-MainThread megalodon.py:1240
[16:35:38] Loading guppy basecalling backend
DBG 16:35:38 : Guppy version: "4.5.2" --- MainProcess-MainThread backends.py:541
DBG 16:35:38 : Pyguppy version: "4.5.2" --- MainProcess-MainThread backends.py:542
DBG 16:35:38 : guppy server init command: "/usr/bin/guppy_basecall_server -p auto -l megalodon_results/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --post_out -x cuda:0 -d rerio/basecall_models/" --- MainProcess-MainThread backends.py:598
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in --output-directory for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************
```

Any insight into the minialign class error would be much appreciated!

**Comment by ssmax1** [comment]
Hi, I'm also getting the error - "Substitution matrix for Minalign class must be 5x5" - when testing Megalodon version 4.5.2+bcc53d39.
 
ONT Guppy basecall server software version 4.5.2+bcc53d39, client-server API version 6.0.0
log path:            /test/output/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  4
[guppy/error] main: Substitution matrix for Minalign class must be 5x5.
[guppy/warning] main: An error occurred initialising the basecaller. Aborting.

**Comment by fbrennen** [comment]
Hi both -- a temporary fix is to replace the stub mismatch matrix in rerio with one from guppy 4.5.2:

`cp ont-guppy/data/barcoding/5x5_mismatch_matrix.txt rerio/basecall_models/barcoding/rerio_stub_mismatch_matrix.txt`

 We'll work on getting a proper fix available soon.

**Comment by marcus1487** [comment]
The stub in rerio has been updated and should work with guppy >=4.5 now. Please re-open this issue if the current rerio repository does not resolve this issue.
