### ISSUE TITLE
dna_r9.4.1_450bps_modbases_5mc_hac.cfg vs dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg?

### ISSUE THREAD

**Issue by gokalpyildirir** [nanoporetech/megalodon#125]
Hello,

After reinstalling guppy/megalodon on my computer, I realized that the default config file "dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg" is missing from the /opt/ont/guppy/data folder. In fact, I can see that there are only three config files that I can use for the modbases: 

dna_r10.3_450bps_modbases_5mc_hac_prom.cfg
dna_r9.4.1_450bps_modbases_5mc_hac.cfg
dna_r9.4.1_450bps_modbases_5mc_hac_prom.cfg

I don't know what happened to the default config or if I simply keep missing it. My question is, since I was only focusing on the 5mC methylations after running megalodon with the default config, would it be coherent with the rest of my analyses if I use the dna_r9.4.1_450bps_modbases_5mc_hac.cfg config file instead of the default one? Is there any difference between this one and the default when it comes to 5mC methylation calling? And if I have to use the default config, can you show me where I can download that? 

Thank you for the help!

**Comment by marcus1487** [comment]
The new models show significantly better 5mC detection performance than the mod base models found in guppy <4.5.2. This is also the reason that the previous mod base models were removed from guppy. The new models are the exact same models found in Rerio so those calibration files should work. The next release of megalodon (hopefully out later this week) will add automatic links to these calibration files for these new models.

**Comment by marcus1487** [comment]
Default calibration files added in 2.3.0 release.

**Comment by gokalpyildirir** [comment]
Thank you!
