### ISSUE TITLE
Installation of ont-pyguppy-client fails for python 3.9

### ISSUE THREAD

**Issue by timp0** [nanoporetech/megalodon#127]
More an FYI than anything, ont-pyguppy-client-lib won't install with pip on python 3.9.2 - which is the default miniconda.  Suggest you specify python 3.8 max in documentation.

**Comment by marcus1487** [comment]
This issue has been raised internally, but a note was added to the README to resolve this issue for now.

It turns out mappy is also not compatible with python 3.9, but I've [submitted a MR that was accepted](https://github.com/lh3/minimap2/pull/723) to fix this in the next release.
