### ISSUE TITLE
Missing calibration file?

### ISSUE THREAD

**Issue by timp0** [nanoporetech/megalodon#128]
So - upon upgrade to guppy 4.5.2+bcc53d39 and megalodon 2.3.0 and accompanying pyguppy, I get a new fun error - 

ERROR: No default sequence variant calibration file found for guppy config: dna_r9.4.1_450bps_modbases_5mc_hac.cfg

I found that this cfg file is at least present in /opt/ont/guppy/data - and I also see the template_r9.4.1_450bps_modbases_5mc_hac.jsn file in there.

Full command I'm currently using: 

!megalodon subset_f5 --processes 10 --sort-mappings --outputs variants variant_mappings per_read_variants \
    --reference {nonref} --variant-filename {variants} --output-directory try7 \
    --guppy-server-path /usr/bin/guppy_basecall_server --devices 0 

I tested guppy_basecaller by itself with this cfg and it works fine . . . so not sure the issue.

**Comment by marcus1487** [comment]
This looks like an issue with a change made to the package setup (converted from `setup.py` to `setup.cfg`) and the calibration files were no longer included in the source pypi package. Weirdly they were still included in the wheel distribution (only available for mac python 3.7) so I didn't catch this in local testing, but can confirm the bug on a linux test. I've just updated the package on pypi (`2.3.1`) and will upload the new version to conda (usually takes about a day to upload there). This should resolve the issue, but please post if it is not fixed.

**Comment by marcus1487** [comment]
I'm having issues uploading the new version to pypi, but should have it resolved shortly.

**Comment by marcus1487** [comment]
Upload successful. Fresh install from pip should resolve the issue now.
