### ISSUE TITLE
The run is stuck just before megalodon_extras aggregate run step.

### ISSUE THREAD

**Issue by gokalpyildirir** [nanoporetech/megalodon#129]
Hello,

I am using our GPU server for basecalling, then transferring the data to the CPU server to aggregate the reads. For the previous runs, this strategy worked great. Tail of a succesful run looks like:
...
DBG 08:29:17 : d65259d5-5b81-492f-bb00-201f6fb02ad7 BasecallingCompleted --- ReadWorker000-MainThread backends.py:887
DBG 08:29:17 : d65259d5-5b81-492f-bb00-201f6fb02ad7 Success --- ReadWorker000-MainThread megalodon.py:308
DBG 08:29:17 : Closing --- ReadWorker000-MainThread megalodon.py:264
DBG 08:29:17 : MappingWorkerClosing --- MainProcess-Mapper000 mapping.py:212
DBG 08:29:17 : JoiningMain: Workers --- MainProcess-MainThread megalodon.py:674
DBG 08:29:17 : JoiningMain: ReadWorker000 --- MainProcess-MainThread megalodon.py:677
DBG 08:29:17 : JoinedMain: ReadWorker000 --- MainProcess-MainThread megalodon.py:679
DBG 08:29:17 : JoiningMain: ReadWorker001 --- MainProcess-MainThread megalodon.py:677
DBG 08:29:17 : JoinedMain: ReadWorker001 --- MainProcess-MainThread megalodon.py:679
DBG 08:29:17 : JoiningMain: ReadWorker002 --- MainProcess-MainThread megalodon.py:677
DBG 08:29:17 : JoinedMain: ReadWorker002 --- MainProcess-MainThread megalodon.py:679
DBG 08:29:17 : JoiningMain: ReadWorker003 --- MainProcess-MainThread megalodon.py:677
DBG 08:29:17 : JoinedMain: ReadWorker003 --- MainProcess-MainThread megalodon.py:679
DBG 08:29:17 : JoiningMain: Mappers --- MainProcess-MainThread megalodon.py:680
DBG 08:29:17 : JoiningMain: Mapper000 --- MainProcess-MainThread megalodon.py:683
DBG 08:29:17 : JoinedMain: Mapper000 --- MainProcess-MainThread megalodon.py:685
DBG 08:29:17 : JoiningMain: Mapper001 --- MainProcess-MainThread megalodon.py:683
DBG 08:29:17 : JoinedMain: Mapper001 --- MainProcess-MainThread megalodon.py:685
DBG 08:29:17 : JoiningMain: Mapper002 --- MainProcess-MainThread megalodon.py:683
DBG 08:29:17 : JoinedMain: Mapper002 --- MainProcess-MainThread megalodon.py:685
DBG 08:29:17 : JoiningMain: Mapper003 --- MainProcess-MainThread megalodon.py:683
DBG 08:29:17 : JoinedMain: Mapper003 --- MainProcess-MainThread megalodon.py:685
DBG 08:29:17 : JoiningMain: Getters --- MainProcess-MainThread megalodon.py:688
[08:29:17] Waiting for mods database to complete indexing
DBG 08:29:17 : JoiningMain: per_read_mods --- MainProcess-MainThread megalodon.py:698
DBG 08:29:17 : GetterClosing --- per_read_mods-MainThread mods.py:1546
DBG 08:29:17 : CreatingIndex --- per_read_mods-MainThread mods.py:1563
DBG 08:29:17 : GetterClosing --- failed_reads-MainThread megalodon.py:557
[08:29:17] Unsuccessful processing types:
     8.6% (1034744 reads) : No alignment                                                                    
DBG 06:31:57 : ClosingDB --- per_read_mods-MainThread mods.py:1565
DBG 06:31:57 : JoinedMain: per_read_mods --- MainProcess-MainThread megalodon.py:700
DBG 06:31:57 : JoiningMain: Complete --- MainProcess-MainThread megalodon.py:701
[06:32:01] Spawning modified base aggregation processes
[06:32:01] Aggregating 11573748478 per-read modified base statistics
[06:32:01] NOTE: If this step is very slow, ensure the output directory is located on a fast read disk (e.g. local SSD). Aggregation can be restarted using the `megalodon_extras aggregate run` command

And at this point, I am running the aggregate from the other server no problem. However, this time it looks like the run is stuck at the MappingWorkerClosing step. I even restarted the run, but it's still stuck at this step. This is what the tail of the new run's log looks like:

...
DBG 23:00:24 : 448448f6-09a1-4676-a6a6-b3fd67045610 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : 43d11131-5c39-46e3-add4-e3315c14ad37 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : d18ba590-cca8-4446-ad02-c63a78f3a50d Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : 4cd24ef6-b9a0-4d4d-96d7-ea529cfb3c89 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : ed5bd4a8-8ac3-4da8-a790-d410e5c0cf72 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : f43c5377-ce4c-4b04-9e04-02b8489079e2 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : 46843b74-eae2-4691-bdeb-ae2049b68d18 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : ce5b54b6-a47c-4395-86a9-ce8da2facc21 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : cf884e1c-922a-4ceb-9a3f-fca7d228ae72 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : 490daa91-31c0-42ae-a3f9-41cc25450d58 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : eacda12f-1455-447e-8799-7a0f22ced65a Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : 7161a0ce-5431-42e6-bf7d-3c392ac2f65d Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : b45c7703-cd86-4573-a1f6-f57c3bc980c4 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : f096e5d6-2c61-4bd2-8b8b-2014a1efe287 Processing --- ReadWorker001-MainThread megalodon.py:287
DBG 23:00:24 : JoiningMain: SignalExtractors --- MainProcess-MainThread megalodon.py:658
DBG 23:00:24 : JoinedMain: SignalExtractors --- MainProcess-MainThread megalodon.py:661
DBG 23:00:24 : Closing --- ReadWorker001-MainThread megalodon.py:279
DBG 23:00:24 : f43c5377-ce4c-4b04-9e04-02b8489079e2 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:24 : f43c5377-ce4c-4b04-9e04-02b8489079e2 Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:24 : 448448f6-09a1-4676-a6a6-b3fd67045610 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:24 : 448448f6-09a1-4676-a6a6-b3fd67045610 Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : 43d11131-5c39-46e3-add4-e3315c14ad37 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : 43d11131-5c39-46e3-add4-e3315c14ad37 Failed No alignment --- ReadWorker001-MainThread megalodon.py:336
DBG 23:00:25 : d18ba590-cca8-4446-ad02-c63a78f3a50d BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : d18ba590-cca8-4446-ad02-c63a78f3a50d Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : 4cd24ef6-b9a0-4d4d-96d7-ea529cfb3c89 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : 4cd24ef6-b9a0-4d4d-96d7-ea529cfb3c89 Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : ed5bd4a8-8ac3-4da8-a790-d410e5c0cf72 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : ed5bd4a8-8ac3-4da8-a790-d410e5c0cf72 Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : 46843b74-eae2-4691-bdeb-ae2049b68d18 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : 46843b74-eae2-4691-bdeb-ae2049b68d18 Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : ce5b54b6-a47c-4395-86a9-ce8da2facc21 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : ce5b54b6-a47c-4395-86a9-ce8da2facc21 Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : cf884e1c-922a-4ceb-9a3f-fca7d228ae72 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : cf884e1c-922a-4ceb-9a3f-fca7d228ae72 Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : 490daa91-31c0-42ae-a3f9-41cc25450d58 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : 490daa91-31c0-42ae-a3f9-41cc25450d58 Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : eacda12f-1455-447e-8799-7a0f22ced65a BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : eacda12f-1455-447e-8799-7a0f22ced65a Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : 7161a0ce-5431-42e6-bf7d-3c392ac2f65d BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : 7161a0ce-5431-42e6-bf7d-3c392ac2f65d Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : b45c7703-cd86-4573-a1f6-f57c3bc980c4 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : b45c7703-cd86-4573-a1f6-f57c3bc980c4 Success --- ReadWorker001-MainThread megalodon.py:323
DBG 23:00:25 : f096e5d6-2c61-4bd2-8b8b-2014a1efe287 BasecallingCompleted --- ReadWorker001-MainThread backends.py:916
DBG 23:00:25 : f096e5d6-2c61-4bd2-8b8b-2014a1efe287 Failed No alignment --- ReadWorker001-MainThread megalodon.py:336
DBG 23:00:25 : MappingWorkerClosing --- MainProcess-Mapper001 mapping.py:226

The run has been stuck like this for a few days. Should I wait more? The megalodon run screen shows that 100% of the reads were processed, and the per_read_modified_base_calls.db and per_read_modified_base_calls.txt files were both produced. Is there any way I can use these files as input and finish the run that way?

And this is my command file:

megalodon \
        /B3/20200731_1828_MN23309_FAN60216_9a194af9/fast5 \
        --outputs mods \
        --reference chrs_B3_plus_unplaced.fasta \
        --write-mods-text --processes 3 \
        --guppy-server-path /usr/bin/guppy_basecall_server \
        --guppy-config dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg \
        --devices "cuda:all:70%" --overwrite \
        --num-read-enumeration-threads 3 \
        --num-extract-signal-processes 1

Thank you for the help!
-Goko

**Comment by marcus1487** [comment]
This is a known issue with the previous version of Megalodon. The most recent release (last week) should make the megalodon/guppy interface much more robust to avoid this issue. 

For this particular run you can use the modified base database, but need to run the `megalodon_extras modified_bases index_database` command to index the database. Note that for your pipeline this indexing step can be completed on CPU resources only. Trigger the skipping of this step in a standard `megalodon` run with the `--skip-database-index` argument.

I would also note that the `dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg` model is not recommended for the highest accuracy modified base calls. The latest release of guppy 4.5.2 has officially removed this model as it is deprecated in favor of the more accurate models found in Rerio (which are now shipped with Guppy). This does require that basecalling be completed with the new model, but should improve the resulting modified base calls.

**Comment by gokalpyildirir** [comment]
Great! I'll do that.

I really want to use the updated config file, but my previous runs were all done with the default one. And it's a bit too time consuming for me to start everything all over again. 

I have started running the indexing. After this is done, I will just run the `megalodon_extras aggregate run` then correct?

Thanks for the help!

**Comment by marcus1487** [comment]
I understand concerning compute required. Just want to make sure that you were aware of the new model as the results are much better.

Yes. After the indexing step, the aggregate step can be run.
