### ISSUE TITLE
Megalodon running, but files aren't updating

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#131]
Hello!

Backstory:
I installed megalodon on an Amazon EC2 p3.2xlarge instance, which has a GPU, the NVIDIA NV100. 
Its been great, because I've finally been able to run data through meg, at a reasonable speed. 

Until I gave it a large dataset, around ~140gb, of .fast5 files. 

I gave it the following command:
megalodon data/ --guppy-server-path /usr/bin/guppy_basecall_server --output-directory data/gpu-meg --overwrite --reference /tmp/GRCh38.no_alt.fa --outputs basecalls mappings mod_mappings --write-mods-text --processes 8 --devices cuda:0

Everything seems to run fine, and eventually, I leave it be. I come back this morning, and the live feed of the meg application is frozen, and no files have been updated in hours. 

Yet, htop reveals the meg program is still running? 

I've attached two files below, the guppy log, and the log.txt. If someone could please advise or give any suggestions on how I may fix this situation that'd be a huge help!!! 

Here are the logs...
https://drive.google.com/drive/folders/1PlGgKJh0mBe-ZxTG-2X6bgvv5oabyJen?usp=sharing

Thanks.

**Comment by marcus1487** [comment]
Having a look through the guppy and megalodon logs I'm not seeing anything that would indicate any errors or reasons for the stall. Can you see anything in the command line output that might indicate an error?

**Comment by marcus1487** [comment]
Yes. It is certainly possible to run in chunks and merge. This is recommended for large datasets where this type of failure may happen more often. Merging mapping outputs is possible with the `samtools merge` command ([see docs here](http://www.htslib.org/doc/samtools-merge.html)). The basecalls output can simply by `cat`ed together. The text output can be merged again by concatenation (though the header should be clipped off). If the `per_read_mods` output is requested, this can also be merged with the `megalodon_extras merge modified_bases` command ([docs here](https://nanoporetech.github.io/megalodon/extras_merge.html#megalodon-extras-merge-modified-bases)). Even the aggregated bedmethyl files can be aggregated (all processing is done on a per-read level, so results will not change here if performed together or chunked and merged).Docs for aggregated merging are found in the last link as well. For megalodon commands, the command line help (`-h` or `--help` to any command) is the most reliable place to find the options available for each command. I hope this helps!

**Comment by fidibidi** [comment]
Marcus! 

You are one of the most helpful people I've ever met in the issues section of ANY PROJECT, thanks so much, you are very much appreciated!!!
