### ISSUE TITLE
Signals mapping results in no alignments.

### ISSUE THREAD

**Issue by ahmadr75** [nanoporetech/megalodon#133]
Hello Marcus,

I am trying to remap some fast5(reach a fast5 file with analyses filled directory) files for training and developing a basecaller. 

My intent is to use data in [Training Datasets](https://bridges.monash.edu/articles/dataset/Training_data/7676198?file=14274248).
For example, I use a Jupiter notebook on Google collaborator with the following lines of code.

1. for downloading the raw fast5 files and reference fasta file.

`%%bash
!cd /content/  
!wget https://au-east.erc.monash.edu.au/fpfiles/14260685/Klebsiella_pneumoniae_KSB1_6F.tar.gz && tar -xf Klebsiella_pneumoniae_KSB1_6F.tar.gz   `

2. for remapping the fast5 files with reference fasta file.

`!megalodon --do-not-use-guppy-server --taiyaki-model-filename /content/taiyaki/models/mGru_flipflop.py  --outputs \   signal_mappings --output-directory /content/outp_dir --overwrite
--reference /content/Klebsiella_pneumoniae_KSB1_6F/Klebsiella_pneumoniae_KSB1_6F/read_references.fasta  \ /content/Klebsiella_pneumoniae_KSB1_6F/Klebsiella_pneumoniae_KSB1_6F/training_fast5s/0000/` 

Also, I have installed both packages (Taiyaki and Megalodon) to use.

It will terminate without any errors; however, no reads are mapped at all.

It would be much appreciated if you could suggest to me how to deal with such an issue. Thank you so much.

Best Regards,
Ahmad
![image](https://user-images.githubusercontent.com/45995379/115722505-4ef37f00-a394-11eb-8750-009b569ca222.png)

**Comment by marcus1487** [comment]
The issue here is the model used. The `/content/taiyaki/models/mGru_flipflop.py` model just defines the models structure. When this model is initialized in Taiyaki it is filled with random paramters. Thus your issue is that the basecalling model is producing essentially random outputs.

I would recommend that you use the guppy backend with the most appropriate basecalling model/config for processing. Runtime should also be ~10X faster with the Guppy backend.

**Comment by ahmadr75** [comment]
@marcus1487 Thanks so much for the detailed feedback. I have already checked the corresponding website for Guppy and it seems they get billing information and other stuff, so I taught I can just use Taiyaki backend without expense. Am I right about this? 
If so are there any base callers that can be mixed with Megalodon package without charge?

**Comment by marcus1487** [comment]
I believe guppy is available without providing billing information (though I may be mistaken). You must register for the nanopore community though. Please register [here](https://community.nanoporetech.com/) or contact support concerning access to the community [here](https://nanoporetech.com/contact).
