### ISSUE TITLE
 Guppy server initialization failed

### ISSUE THREAD

**Issue by emily288** [nanoporetech/megalodon#136]
Hi, I'm trying to run megalodon to get modified base calls and variants, here are the commands. I think the guppy server path is right, but I always get the following error messages. Could you please help me to figure this out? Thank you very much!

Scripts: 
module load guppy/4.4.1
module load cuda/11.0
module load python3/anaconda/2020.02
source activate /work/.conda/Nanopore
megalodon \
/work/fast5 \
--guppy-server-path /work/ont-guppy_4.4.1/ont-guppy-cpu/bin/guppy_basecall_server \
--guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg \ 
--outputs basecalls mappings mod_mappings mods \
--reference /work/GRCm38.101/sequences.fa 
--output-directory /work/megalodon_test \
--devices 0 1 --processes 40 --overwrite

Error message:
[15:08:35] Running Megalodon version 2.2.10
DBG 15:08:35 : Command:
[15:08:35] Loading guppy basecalling backend
DBG 15:08:35 : Guppy version: "4.4.1" --- MainProcess-MainThread backends.py:541
DBG 15:08:35 : Pyguppy version: "4.4.1" --- MainProcess-MainThread backends.py:542
DBG 15:08:35 : guppy server init command: "/work/ont-guppy_4.4.1/ont-guppy-cpu/bin/guppy_basecall_server -p auto -l /work/megalodon_test/cell line/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --post_out -x cuda:0 cuda:1" --- MainProcess-MainThread backends.py:599
ERROR: Guppy server initialization failed. See guppy logs in --output-directory for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.

Then I tried the guppy server init command as the instruction, here is the output:
terminate called after throwing an instance of 'std::runtime_error'
  what():  This build does not support GPU basecalling mode.
Aborted

Sincerely,
Emily

**Comment by marcus1487** [comment]
It looks like you have installed the CPU version of guppy (`ont-guppy-cpu`), but are trying to specify GPU devices (`--devices 0 1`). If you could install the GPU compatible version of guppy this should work.

P.S. I would recommend upgrading to the most recent version of megalodon.

**Comment by emily288** [comment]
Thank you very much!
I can't find a gpu version of guppy, do you have a link or package? Sorry,
I'm still a beginner in bioinformatics.
Or could I modify the scripts, for example, how to change "--device 0 1",
so I can use the CPU version of guppy?

Sincerely,
Emily

Marcus Stoiber ***@***.***> 于2021年4月29日周四 下午4:10写道：

**Comment by marcus1487** [comment]
If you remove the `--device 0 1`, the above command should work, but the GPU backend is *much* faster. The GPU version is available from the nanoopre community webpage under the software downloads section.

**Comment by emily288** [comment]
Thank you very much, I really appreciate it! I will download and run GPU
version later.
But when I remove (--device 0 1), I still get the same error information.
I'm afraid something else is wrong.
[image: image.png]


Marcus Stoiber ***@***.***> 于2021年4月29日周四 下午4:41写道：
