### ISSUE TITLE
guppy 4.5.4 - substitution matrix for minalign class must be 5x5

### ISSUE THREAD

**Issue by bmdoran** [nanoporetech/megalodon#137]
CPU version runs without error.  Version 4.4.1 runs without error on GPU but version 4.5.4 throws the substitution matrix error on GPU.

**Comment by marcus1487** [comment]
This is likely due to a Rerio bug which has been resolved. Update the Rerio repository (`git pull` from Rerio root) to fix this issue. If this does not solve the issue please post here.
