### ISSUE TITLE
Help understanding results

### ISSUE THREAD

**Issue by aerijman** [nanoporetech/megalodon#139]
HI,

1- In the sqlite database provided as a result of the execution of megalodon, `score_pos` in `data` table seem to be the genomic position multiplied by 2. Why?

2- In that same sqlite db, in `data` table, some positions with `score_mod`=1, which according to table `mod_long_names` corresponds to `5mC`, happen to be 'A' and not 'C' (or 'G' for negative strand?) 

3- I can't make sense of the Mm and Ml tags in the mod_mappings.bam 

**Thank you very much** and I am looking forward for your explanations!!

**Comment by marcus1487** [comment]
1. This value encodes a combination of the contiguous, strand and position. So the strand offset is the reason for the *2. 

2. I’m not sure exactly what you are referencing here. Could you explain in more detail the expected and observed results? In general I would say that access directly via the SQLite table is not recommended. Beta support is available via the mods module, but the per read text file dump is probably the more accessible format for the raw data. 

3. This tag is described by a draft merge request to the hts-spec group. See details I. The docs here: https://nanoporetech.github.io/megalodon/file_formats.html

**Comment by aerijman** [comment]
Thank you for your answer. In [THIS](https://www.dropbox.com/s/egyxbjuda04f939/single_read.sam?dl=0) single read from an experiment on bacterial methylation ONT data, analyzed with guppy-megalodon.

There are 7486 nucleotides. (C:2183, G:1630, A:1876, T:1797). In `Mm` tag there are 1052 C+Z values
and 1173 A+Y values. 

Please let me know if I am in the right track (and excuse me for my poor capacity of interpretation):
__Are there 1052 methylated Cs? Then `Ml` is the _confidence_ for these Cs to be methylated?__

If my assumption is correct, the zeros mean the next "C"?


Thank you very much!

**Comment by aerijman** [comment]
1. Thank you very much. You have been very helpful and fast!
2. Last question and we can close this issue. In reads with flag=16 (read reverse strand) I should be considering genomic positions of `G`s right? These will correspond to `C`s in the `-` strand (bam sequence is always `+` strand).
Thank you again!

**Comment by marcus1487** [comment]
Yes. BAM SEQ field will be forward strand reference sequence. So for a canonical C modbase model, the `G` positions will be called on the reverse strand.
