### ISSUE TITLE
error on merging per read databases

### ISSUE THREAD

**Issue by sdemirci** [nanoporetech/megalodon#14]
Hello,

I am trying to merge several `per_read_modified_base_calls.db` files on a 500GB ram machine. It also has 88 GB /tmp space available. 

On a full dataset ,which is ~600 *.db each having the size of ~1.5 GB, I am getting below error after writing over 100GB merged db. Then it deletes the merged db. It also gives me "Stale file handle". Same happens if I use `--mod-positions-on-disk` option. I monitored the memory and /tmp usage. It doesn't use /tmp and memory usage was reasonable. 

> Traceback (most recent call last):
> 
>   File "<path_to_megalodon>/megalodon/scripts/merge_per_read_modified_base_dbs.py", line 60, in <module>
>     main()
>   File "<path_to_megalodon>/megalodon/scripts/merge_per_read_modified_base_dbs.py", line 54, in main
>     out_mods_db.create_data_covering_index()
>   File "~/tools/miniconda3/envs/megalodon_env/lib/python3.7/site-packages/megalodon/mods.py", line 373, in create_data_covering_index
>     self.cur.execute('CREATE INDEX data_cov_idx ON data(' +
> sqlite3.OperationalError: database or disk is full

Then I tried merging 10 of the *db files, which worked fine. But when I tried merging ~200 *.db files, I got a different error: 

> Modified base per-read database file (done/per_read_modified_base_calls.db) does not exist.
> Traceback (most recent call last):
>   File "<path_to_megalodon>/megalodon/scripts/merge_per_read_modified_base_dbs.py", line 60, in <module>
>     main()
>   File "<path_to_megalodon>/megalodon/scripts/merge_per_read_modified_base_dbs.py", line 38, in main
>     mod_index_in_memory=False, uuid_index_in_memory=False)
>   File "~/tools/miniconda3/envs/megalodon_env/lib/python3.7/site-packages/megalodon/mods.py", line 105, in __init__
>     raise mh.MegaError('Invalid mods DB filename.')
> megalodon.megalodon_helper.MegaError: Invalid mods DB filename.
> 

Do you have any idea what could be wrong ? 

Cheers

**Comment by marcus1487** [comment]
The first error appears to indicate that the disk (not RAM) is full. Could you check that the disk resource for the output directory has sufficient space for storage of the full database?

For the second error, this indicates that the directory does not contain the database file in the standard location (filenames within the megalodon_results directory are hard coded in megalodon and should not be changed if further megalodon processing is required). If you take a look at the log.txt file, there should be some more information concerning the database filename that was being searched for.

**Comment by sdemirci** [comment]
Hi, 

What happens is that sqlite3 tries to write at the very end of the process on /tmp which is the default after certain temp locations ( check nr. 5 Temporary File Storage Locations at https://www.sqlite.org/tempfiles.html ).  As the merged *db file is larger than the /tmp disk space, sqlite can not create database index and can not finalize the job so it deletes the merged *db file on the disk and then system gives stale file handle error. We see a sharp peak on /tmp usage at the time of crash. So, I've tried to set temp location to some other location and tested with small dataset. That didn't give any peak on the /tmp usage and so it worked.  For record, I've set `export TMPDIR=/new_temp_location ` on my shell environment then run megalodon. Now I am running the full dataset. I will keep you updated.

**Comment by marcus1487** [comment]
Was this workaround useful to solve this issue? If so I could add a note to the README/docs concerning this issue.

**Comment by sdemirci** [comment]
Yes, this solution worked for a larger dataset. Indeed, it is worth to write it down. Thanks for your availability.
