### ISSUE TITLE
error related to guppy version when trying to run megalodon

### ISSUE THREAD

**Issue by signor-molevol** [nanoporetech/megalodon#141]
This is the input and output. When I ask the system what version of guppy we have it says version 4.5. Please advise.  

megalodon fast5/ --outputs basecalls mappings mod_mappings mods --reference reference/reference.fa --mod-motif Z CG 0 --devices 0 1 --processes 40
[20:11:16] Running Megalodon version 2.3.1
[20:11:16] Loading guppy basecalling backend
****************************************************************************************************
	ERROR: Megalodon requires Guppy version>=4.0. Got: "3.4.5"
****************************************************************************************************

guppy_basecaller --version
: Guppy Basecalling Software, (C) Oxford Nanopore Technologies, Limited. Version 4.5.4+66c1a7753

**Comment by marcus1487** [comment]
Megalodon does not use the system install of guppy, but instead uses the default of `./ont-guppy/bin/guppy_basecall_server`, so there must be a copy of guppy extracted in the current working directory or megalodon would throw an error. You can run `./ont-guppy/bin/guppy_basecall_server --version` to see the version of this installation. Alternatively you can use the `--guppy-server-path` megalodon argument to point megalodon to another installation of guppy.
