### ISSUE TITLE
Help to train de novo modified base model

### ISSUE THREAD

**Issue by pterzian** [nanoporetech/megalodon#142]
Hi,

I am interested in training de novo CpG modified base models with megalodon.

After reading the documentation I have a couple of questions.

As an example, let's say I have two promethION runs of the same sample, but one has fully unmethylated CpGs  and the other has fully methylated CpGs.

I understand I should extract the mapped signal with megalodon but I don't understand which of the strategies I should use to build my training dataset.  

* Should I follow the one described in the "Modified Base in Known Context" section or the "Ground Truth Aided Bootstrap Modified Base Annotation"  one, considering my data? 
* Do I have to train the model using two datasets ? A "cannonical signal" dataset and a "modified signal" dataset ? Or is it only one dataset ?
*  I read that one training strategy uses a file called `ground_truth_methylation.CG.bed`. I didn't find an example of this file. Does it store the methylation status of the genomic positions in the training dataset ? 

best, 

Paul

**Comment by marcus1487** [comment]
Given the setup with known modified base context (100% CpG methylation) the "Modified Base in Known Context" section should be used.

The model will likely produced the best results using a dataset containing both of these runs. See the taiyaki script to merge mapped signal files: https://github.com/nanoporetech/taiyaki/blob/master/misc/merge_mappedsignalfiles.py

As noted in the docs this is a bedmethyl file containing the "ground truth" (really just an alternative method; e.g. bisulfite) percent methylation at each reference site from the same sample as the provided nanopore data. See an example from the ENCODE consortium here: https://www.encodeproject.org/data-standards/wgbs/ .
