### ISSUE TITLE
multiplexed fast5 barcode question

### ISSUE THREAD

**Issue by ruicatxiao** [nanoporetech/megalodon#144]
Hi,

When feeding multiplexed fast5 individually into megalodon for base modification, would the barcode present on the signal fast5 files hinder Megalodon's ability to anchor to reference sequence? If so, what would be the preferred tools to clip the fast5 files?

Thanks!

**Comment by marcus1487** [comment]
The barcodes should not cause any additional issues beyond standard adapters. Guppy (run within megalodon) trims adapters and barcodes in the basecalled reads and this clipping is reflected in the signal anchoring. Generally the effects of adapters and barcodes should be very minimal for reference mapping and anchoring. I would recommend no special steps for barcodes or adapters within megalodon.
