### ISSUE TITLE
mappings.summary.txt

### ISSUE THREAD

**Issue by jennyg86** [nanoporetech/megalodon#145]
Hi,
Can you please explain the meaning of each column in the "mappings.summary.txt" file?

read_id | pct_identity | num_align | num_match | num_del | num_ins | read_pct_coverage | chrom | strand | start | end | query_start | query_end | map_sig_start | map_sig_end | sig_len | map_num
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Thanks!

**Comment by marcus1487** [comment]
I've just added this information to the [file formats docs page here](https://nanoporetech.github.io/megalodon/file_formats.html#mapping-summary). If you need any further clarifications please re-open this issue.

**Comment by jennyg86** [comment]
Thank you for the detailed explanation!

Just one more question about it, can you please explain how the `query_start` and the `query_end` are calculated?

**Comment by marcus1487** [comment]
`query_start` and `query_end` are pythonic (0-based closed-open) interval coordinates into the basecalls for that read. These are reported as returned from the mapping produced by minimap2.
