### ISSUE TITLE
relative number of SNPs of six subtype

### ISSUE THREAD

**Issue by emily288** [nanoporetech/megalodon#147]
Hello,

I'm working on mutational signature analysis (I also put a picture down here), so I'm wondering if we can get these two kinds of data from megalodon: 1) exact total number of SNPs in each sample; 2) relative number of SNPs of each subtype (C>A, C>G, C>T, T>A, T>C, and T>G) in each sample?

Do we have an output file has data of exact number of SNPs, or which file (variants sorted vcf?) may act as input file for downstream analysis to get relative number of SNPs? I noticed we have num_del and num_ins in mapping summary.txt file. 

![image](https://user-images.githubusercontent.com/83426502/119399605-19012d80-bca7-11eb-9d77-753608abbd3f.png)
(https://cancer.sanger.ac.uk/signatures/sbs/sbs36/)
There are 6 classes of base substitutions and 16 possible sequence contexts for each mutated base (A, C, G or T at the 5ʹ base and A, C, G or T at the 3ʹ base), 96 different mutated trinucleotides are possible. 

Thank you!

**Comment by marcus1487** [comment]
While megalodon does output variant calls, it is not the recommendation for the highest accuracy variant calls. The current recommendation for the highest accuracy variants calls is medaka.

In terms of extracting this information from megalodon, I would suggest the `--outputs variants` output file (which is a VCF file). The mappings summary contains per-read mapping statistics. These are not likely as informative for this question as the aggregated variants calls.

As a further note, I believe these types of cancer variant analyses are made on tumor/normal pairs. Thus I would recommend creating a normal sample reference before performing the cancer mutational analyses as described above.

**Comment by emily288** [comment]
Thank you for your information. 
I have one more quality related question, here is the variants.sorted.vcf file I got. 
![image](https://user-images.githubusercontent.com/83426502/119867253-b056c280-beeb-11eb-9a87-6b436f478c50.png)
The sixth column (QUAL) is low or none. And the highest DP in this file is around 6 or 7, is that low or normal for nanopore sequencing? Besides DP, what other values in the vcf file can be used to estimate the quality of the vcf file?

Thank you!

**Comment by marcus1487** [comment]
The DP (=depth) field has a lot to do with the instrument run, sample quality and reference size. For a whole human genome on a single minion flowcell this sounds like a reasonable number. The low QUAL values indicate that the support for the variant specified is low. This does not mean that the call is of low quality, but that the likelihood of the variant is low.

Assessing the overall quality of the variant calls from a run would require a ground truth set of variants for a sample. If the reference provided is expected to match the sample perfectly then a VCF with all variants rejected (reference bases called) would be expected.
