### ISSUE TITLE
Out of memory: Kill process 20825 (megalodon)

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#148]
Hello all!

Recently set up a new workstation, but am having some issues with megalodon being killed when it uses up all RAM. 

PC Specs:

Megalodon version: 2.3.1
Guppy: 4.5.4
Ubuntu 16.04

GPU: 3080
CPU: 10700KF
RAM: 32gb DDR4
Storage: 1TB pvme

Running megalodon on some flongle data, approximately 3.5gb in size. 

Using the following commands, where I adjusted the number of processes, I tried to see if I could calibrate the system better... 

**Attempt 1**
megalodon AFN630/fast5/ --guppy-server-path ~/ont-guppy/bin/guppy_basecall_server --output-directory ./afn630-meg-out --overwrite --reference GRCh38.no_alt.fa --outputs basecalls mappings mod_mappings --processes 16 --devices cuda:0

made it to 18%
killed @ 2:10, 188.52 r/s, 3.23e+6

**Attempt 2**
megalodon AFN630/fast5/ --guppy-server-path ~/ont-guppy/bin/guppy_basecall_server --output-directory ./afn630-meg-out --overwrite --reference GRCh38.no_alt.fa --outputs basecalls mappings mod_mappings --processes 8 --devices cuda:0

made it to 42%
killed @ 10:00, 93.59, 1.5e +6

**Attempt 3**
megalodon AFN630/fast5/ --guppy-server-path ~/ont-guppy/bin/guppy_basecall_server --output-directory ./afn630-meg-out --overwrite --reference GRCh38.no_alt.fa --outputs basecalls mappings mod_mappings --processes 4 --devices cuda:0

made it to 75%
killed @ 35:01, 49.79reads/s, samples/s=8.29e+5

As you can see, by reducing the processes value, I've made able to make it further each time, but still, its crashing. 

The reference file being used in these examples, is ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz, clocking in at roughly 3.0gb.

I am aware that I can try chunking the data into smaller pieces, but I would like to know why I am having such issues running such a small dataset. 

Thanks so much!

**Comment by marcus1487** [comment]
Could you try to perform the same command using a minimap index of the reference as input instead of the fasta file?

**Comment by fidibidi** [comment]
I'm open to trying! But parden my ignorance, I'm not entirely sure how to generate that file... 

I have minimap2 installed, and I have the reference file on hand...

**Comment by fidibidi** [comment]
I will mess around for one sec..

**Comment by marcus1487** [comment]
Yes. That is the command. Hopefully this works. 

I've logged this issue in minimap2/mappy (linked here https://github.com/lh3/minimap2/issues/705), but have yet to be able to produce the smallest example to identify the memory leak in minimap2/mappy.

**Comment by fidibidi** [comment]
Well, 
The .mmi file is around 6gb, but the run was an absolute breeze... 

Ran command:
megalodon AFN630/fast5/ --guppy-server-path ~/ont-guppy/bin/guppy_basecall_server --output-directory ./afn630-meg-out --overwrite --reference GRCh38.noalt.mmi --outputs basecalls mappings mod_mappings --processes 16 --devices cuda:0

and the stats were:
11:16<00:00, 201.28reads/s, samples/s=3.33e+6

Memory never grew past around 20. 

Thanks so much!

My only question I guess, is there a significant difference in this output versus using the original reference file?

Thanks Marcus!

**Comment by marcus1487** [comment]
There is absolutely no difference in the results of the run using the fasta reference vs the minimap2 index (as long as you use the `-x map-ont` setting in the index step as you have done). 

I need to sit down and create the simple test case so this can be resolved in minimap2/mappy as it bites me from time to time as well.

Best of luck in your research!

**Comment by fidibidi** [comment]
Hey Marcus,

So the previous issues I experienced, have resurfaced!

Trying to run fast5 files from a minION run, clocking in at around 150 gb, and using essentially the same command as above, with the minimap2 indexed ref file, I got hit with the OOM: Process Killed. 

I'm aware that I can run the data in smaller chunks, and merge the output at the end, but I'd like to make sure that there isn't anything else I could be trying! 

Obviously, my ram could upgrade, which could resolve the issue, but why does it seem like no one else in the forums is experiencing this issue? Is there a step in this process I've messing up? 

Thanks!

**Comment by marcus1487** [comment]
I don't see anything that should be causing memory to build up over a megalodon run. The one bit that does increase the memory are the output queues. Are you seeing the output queues filling up during the run? These have a limit of 10k items to avoid OOM errors, but it is possible that this is too many for lower RAM usage settings. This is unfortunately hardcoded at the moment.

**Comment by fidibidi** [comment]
Hey Marcus, 

Thanks for response!

The output queues get to maybe 5/10000, but never approach full.

**Comment by marcus1487** [comment]
How about the input queue? Is this an ultra-long run by any chance? It could be that a stretch of longer signals was loaded and this overloaded the memory. If that is the case I might need to hook the input queue size into the command line.

I've been through rounds of searching for memory leaks, and have plugged most of them. The long reads input signal queue growing would be my best guess at this point.

**Comment by fidibidi** [comment]
Heyo!

The input queue is 10000/10000, as for whether it was ultra long run, I will ask the lab tech. 

I'm going to be downloading some promethion datasets from this link
aws s3 sync s3://ont-open-data/gm24385_2020.11/flowcells/20201102_1746_6C_PAG07506_acad8a68/fast5_pass/

And was going to see how megalodon did with it...

**Comment by vahidAK** [comment]
Hi @marcus1487 ,

I also faced the same issue. I even tried to give smaller chunk sizes and chunk numbers to guppy using --guppy-params but this also didn't work.
How can we run megalodon to use less RAM? I saw the number of --processes has already defaulted to 1!

Thanks,
Vahid
