### ISSUE TITLE
fast5s_dir error

### ISSUE THREAD

**Issue by marcDabad** [nanoporetech/megalodon#149]
Hi all, 

I am trying to run megalodon raw_fast5s specifying the fast5 paths but I have 
`megalodon: error: unrecognized arguments: ../4.4.2/fixed/ecoli_er2925.pcr.r9.timp.061716.fast5/pass/`

I've seen it's a positional argument and when I try to use:
```
megalodon \
raw_fast5s \
[args] \
${fast5_dir}
```

or 

```
megalodon \
raw_fast5s \
${fast5_dir} \
[args] 
```
I am trying to do what --help says:

```
usage: megalodon [-h] [--guppy-config GUPPY_CONFIG]
                 [--guppy-server-path GUPPY_SERVER_PATH] [--live-processing]
                 [--outputs {basecalls,mod_basecalls,mappings,per_read_variants,variants,variant_mappings,per_read_mods,mods,mod_mappings,signal_mappings,per_read_refs} [{basecalls,mod_basecalls,mappings,per_read_variants,variants,variant_mappings,per_read_mods,mods,mod_mappings,signal_mappings,per_read_refs} ...]]
                 [--output-directory OUTPUT_DIRECTORY] [--overwrite]
                 [--mappings-format {bam,cram,sam}] [--reference REFERENCE]
                 [--haploid] [--variant-filename VARIANT_FILENAME]
                 [--mod-motif BASE MOTIF REL_POSITION] [--processes PROCESSES]
                 [--devices DEVICES [DEVICES ...]] [--help-long] [--rna] [-v]
                 fast5s_dir
```

What I am doing wrong?

Thanks

**Comment by marcus1487** [comment]
The `raw_fast5s` should be removed from the command. I'm guessing in an example command this was used as a placeholder for the fast5s directory. Is there a location in the docs where this could be made clearer (or where was the example command you started from found)?

**Comment by marcDabad** [comment]
Maybe should be changed `raw_fast5s` by fast5s_dir`.

Thanks for your help.

**Comment by marcus1487** [comment]
@marcDabad Yes. I agree. Where did you see `raw_fast5s` in the docs? I only see it in the commands you've tried posted here.
