### ISSUE TITLE
Megalodon (and Guppy) hang only when running Rerio models

### ISSUE THREAD

**Issue by TromboneEngineer** [nanoporetech/megalodon#150]
Megalodon has been working for me using Guppy version 4.5.4 and more recently 4.5.2 (since I cannot run Guppy 5.0.7 on my GTX 1060 GPU), but hangs when I try to run a Rerio model. The following command without a Rerio model works:

`megalodon fast5_pass-wihtout-fast5_skip/barcode11/ --devices 0 --processes 8 --reference Reference_Genomes/barcode11.fasta --outputs basecalls mappings mod_mappings mods --overwrite --output-directory barcode11_testWOrerio/ --guppy-server-path guppy_basecall_server --write-mods-text | tee BC11testWOrerio.out`

But trying to specify any Rerio model:
`megalodon fast5_pass-wihtout-fast5_skip/barcode11/ --devices 0 --processes 8 --reference Reference_Genomes/barcode11.fasta --outputs basecalls mappings mod_mappings mods --overwrite --output-directory barcode11_mod_calls_rerio/ --guppy-server-path guppy_basecall_server --guppy-params "-d ~/rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg --write-mods-text | tee BC11rerio2.out`

fails with the following message:

>  ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.

> Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.

The command in the log is:
`guppy_basecall_server -p auto -l barcode11_mod_calls_rerio/guppy_log -c res_dna_r941_min_modbases-all-context_v001.cfg --post_out --quiet -x cuda:0 -d ~/rerio/basecall_models/`

but it never loads, just hangs. Previously when I got this terminal message, I was able to run the Guppy command inside the log and get an output within seconds that was helpful for troubleshooting. However now that I am trying to specify Rerio models to call something other than 5mC (interested in 6mA), Megalodon will not run. I tried updating Megalodon from 2.3.1 to 2.3.2, but the same issue persists. I also tested the above successful run after this update, so the update did not break my ability to run non-Rerio models.

**Comment by marcus1487** [comment]
So I understand correctly, the `guppy_basecall_server -p auto -l barcode11_mod_calls_rerio/guppy_log -c res_dna_r941_min_modbases-all-context_v001.cfg --post_out --quiet -x cuda:0 -d ~/rerio/basecall_models/` call just hangs when run independently from megalodon, correct?

I'm not sure about this, but could you try to run this command with the full path to the rerio directory (with the `~` expanded)?

**Comment by TromboneEngineer** [comment]
I did find it odd that the log from Megalodon changed my ~/ to /home/sam/ inside the log it made, only for the path to guppy_basecall_server and not to rerio. Just gave it a shot, and the behavior is the same (hanging)
`/home/sam/ont-guppy/bin/guppy_basecall_server -p auto -l barcode11_mod_calls_rerio5/guppy_log -c res_dna_r941_min_modbases-all-context_v001.cfg --post_out --quiet -x cuda:0 -d /home/sam/rerio/basecall_models/
`

**Comment by marcus1487** [comment]
Could you remove the `--quiet` argument to see if there might be some useful output. The `--quiet` argument is added in the guppy call in megalodon to try to suppress any additional messages from the server polluting the megalodon output.

**Comment by TromboneEngineer** [comment]
The output does indeed change without `--quiet`
`/home/sam/ont-guppy/bin/guppy_basecall_server -p auto -l barcode11_mod_calls_rerio5/guppy_log -c res_dna_r941_min_modbases-all-context_v001.cfg --post_out -x cuda:0 -d /home/sam/rerio/basecall_models/`

This is where it hangs now:

ONT Guppy basecall server software version 4.5.4+66c1a77, client-server API version 6.0.0
log path:            barcode11_mod_calls_rerio5/guppy_log
chunk size:          1000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  4

Config loaded:
config file:               /home/sam/rerio/basecall_models/res_dna_r941_min_modbases-all-context_v001.cfg
model file:                /home/sam/rerio/basecall_models/res_dna_r941_min_modbases-all-context_v001.jsn
model version id           None
adapter scaler model file: None
Starting server on port: 37937

**Comment by marcus1487** [comment]
This is actually the expected stall point for the guppy server call. This indicates that the server has been initialized and is ready to accept reads from clients. This process will thus hang indefinitely in this state waiting for reads or until it is killed.

Moving back to the megalodon call, could you have a look in the guppy log found within the megalodon output directory to see if there is anything useful there? Also is there any more information in the megalodon log.txt file that might be useful?

**Comment by TromboneEngineer** [comment]
Separately, I played around with a few things and got the error to change, but not resolve. I managed to find the download link for Guppy version 4.5.4, so I uninstalled 4.5.2, rebooted, and got 4.5.4 fully installed (no change in behavior observed, but it should be a net upgrade). I also made sure to run `pip install ont-pyguppy-client-lib==4.5.4`, so that shouldn't be the issue.

I also found that the Guppy command from Megalodon's log sometimes alters the way the config file is referred to, with -d -c and --guppy-config somewhat overwriting each other. When I rearrange the order of these three parameters passed, I get an actual error rather than hanging:
`>megalodon fast5_pass-wihtout-fast5_skip/barcode11/ --devices 0 --processes 8 --reference Reference_Genomes/barcode11.fasta --outputs basecalls mappings mod_mappings mods --overwrite --output-directory barcode11_mod_calls_rerio2/ --guppy-server-path ~/ont-guppy/bin/guppy_basecall_server --guppy-params "-d ~/rerio/basecall_models/ --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg" --write-mods-text | tee BC11rerio.out`

Megalodon has the same error, but the log it creates has a different command:
`/home/sam/ont-guppy/bin/guppy_basecall_server -p auto -l barcode11_mod_calls_rerio2/guppy_log -c dna_r9.4.1_450bps_modbases_5mc_hac.cfg --post_out --quiet -x cuda:0 -d ~/rerio/basecall_models/ --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg`

The error is then

> Config file: /home/sam/rerio/basecall_models/dna_r9.4.1_450bps_modbases_5mc_hac.cfg does not exist!
> Unexpected option '--guppy-config' found on command line.

So I rearranged the order of the arguments:
`/home/sam/ont-guppy/bin/guppy_basecall_server -p auto -l barcode11_mod_calls_rerio2/guppy_log -c ~/rerio/basecall_models/res_dna_r941_min_modbases-all-context_v001.cfg --post_out --quiet -x cuda:0`

The error then becomes:

> [guppy/error] main: Unable to parse json: /home/sam/ont-guppy/data/res_dna_r941_min_modbases-all-context_v001.jsn
> [guppy/warning] main: An error occurred initialising the basecaller. Aborting.

I took a look at [this rerio issue](https://github.com/nanoporetech/rerio/issues/4) and confirmed that my config file has more than a weblink inside it (not sure if it did initially, but I got rid of my rerio directory and redownloaded it, then ran the Python script to download the config file). Seems strange that I would see this error but not be able to resolve it with the described method.

**Comment by marcus1487** [comment]
Ah. The `--guppy-config` argument is a megalodon argument and not a guppy argument. The end `"` should be moved to exclude this argument. So the command should be `megalodon fast5_pass-wihtout-fast5_skip/barcode11/ --devices 0 --processes 8 --reference Reference_Genomes/barcode11.fasta --outputs basecalls mappings mod_mappings mods --overwrite --output-directory barcode11_mod_calls_rerio2/ --guppy-server-path ~/ont-guppy/bin/guppy_basecall_server --guppy-params "-d ~/rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg --write-mods-text | tee BC11rerio.out`

**Comment by TromboneEngineer** [comment]
Ah that would do it! Megalodon is finally running with a Rerio config file. I had been playing with the position of the second `"` because I wondered if memory problems/arguments might explain the issue. Now I have a final command and it is running:
`megalodon fast5_pass-wihtout-fast5_skip/barcode11/ --devices 0 --processes 8 --reference Reference_Genomes/barcode11.fasta --outputs basecalls mappings mod_mappings mods --overwrite --output-directory barcode11_mod_calls_rerio9/ --guppy-server-path /home/sam/ont-guppy/bin/guppy_basecall_server --guppy-params "-d /home/sam/rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg --write-mods-text | tee BC11rerio.out`

Not sure if the ~ was ever problematic, but it is running now. Thank you very much.

**Comment by Johnsonzcode** [comment]
Same error with `res_dna_r941_min_modbases-all-context_v001.cfg`

**Comment by marcus1487** [comment]
@Johnsonzcode Could you post the exact command entered into the command line? The above issue was resolved by moving the parentheses so the correct arguments were passed on to Guppy.
