### ISSUE TITLE
ERROR: Guppy server initialization failed. 

### ISSUE THREAD

**Issue by TerrenceT-79** [nanoporetech/megalodon#152]
Hello all, I got the following error while running Megalodon:

 ~ % megalodon fast5/ \

--guppy-server-path /Users/terrence.turner/ont-guppy-cpu/bin/guppy_basecall_server \

--guppy-params "--model_file /rerio/basecall_models/res_dna_r941_min_modbases-all-context_v001.jsn" \

--outputs mods \

--reference Rosa.fa \

--output-directory //Users/terrence.turner/megalodon_results \

--overwrite

--devices 0 --processes 16        

\[21:28:48] Running Megalodon version 2.3.1

[21:28:48] Loading guppy basecalling backend

****************************************************************************************************

    ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.

        Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.

****************************************************************************************************

The error on the log file was:

2021-05-19 21:28:48.920330 [guppy/message] ONT Guppy basecall server software version 4.5.4+66c1a7753, client-server API version 6.0.0log path:            //Users/terrence.turner/megalodon_results/guppy_logchunk size:          2000chunks per runner:   512max queued reads:    2000num basecallers:     1num socket threads:  2max returned events: 50000cpu mode:             ONthreads per caller:  4
2021-05-19 21:28:48.921460 [guppy/info] crashpad_handler not supported on this platform.2021-05-19 21:28:48.922162 [guppy/info] Listening on port 52259.2021-05-19 21:28:48.952446 [guppy/error] Unable to parse json: /rerio/basecall_models/res_dna_r941_min_modbases-all-context_v001.jsn2021-05-19 21:28:48.952495 [guppy/warning] An error occurred initialising the basecaller. Aborting.

Any ideas? Thanks

**Comment by fidibidi** [comment]
What is your OS? System Specifics?

**Comment by marcus1487** [comment]
This might be unrelated, but it looks like you are using a CPU guppy installation (`ont-guppy-cpu`), but specifying GPU resources (`--devices`). If this is the issue this is certainly not an ideal error message, but it would be good to resolve this issue. Can you confirm that you can run the above call without the `--guppy-params "--model_file /rerio/basecall_models/res_dna_r941_min_modbases-all-context_v001.jsn"` setting?

**Comment by Johnsonzcode** [comment]
Same error and log file. I guess maybe something wrong with the model `res_dna_r941_min_modbases-all-context_v001`. I will try anothor , but I want to find out 6mA since only it can be used for calling 6mA.

**Comment by peralesvilchezl** [comment]
hi, I have the same problem when I run guppy. Is there anything else apart from unzipping the ont-guppy-cpu in a MAC?
2021-09-16 17:54:37.928712 [guppy/info] crashpad_handler not supported on this platform.
2021-09-16 17:54:37.930003 [guppy/error] Unable to parse json:
2021-09-16 17:54:37.930045 [guppy/warning] An error has occurred. Aborting.

**Comment by marcus1487** [comment]
@peralesvilchezl This looks like the model files may not have been downloaded correctly. Was the requested model downloaded via rerio as instructed there?

**Comment by elirandv** [comment]
Hi there, I got the following log error while running Megalodon:

```
[14:25:44] Running Megalodon version 2.4.2
DBG 14:25:44 : Command: """/home/nano/miniconda3/bin/megalodon Fast5_files/ --guppy-config dna_r9.4.1_450bps_fast.cfg --remora-modified-bases dna_r9.4.1_e8 fast 0.0.0 5hmc_5mc CG 0 --outputs basecalls mappings mod_mappings mods --reference r --devices 0 --processes 20 --guppy-server-path /home/nano/Downloads/ont-guppy/bin/guppy_basecaller --output-directory mega_test""" --- MainProcess-MainThread megalodon.py:1791
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[14:25:44] Loading guppy basecalling backend
DBG 14:25:45 : Guppy version: "4.2.2" --- MainProcess-MainThread backends.py:939
DBG 14:25:45 : Pyguppy version: "4.2.2" --- MainProcess-MainThread backends.py:940
DBG 14:25:45 : guppy server init command: "/home/nano/Downloads/ont-guppy/bin/guppy_basecaller -p auto -l mega_test/guppy_log -c dna_r9.4.1_450bps_fast.cfg --quiet -x cuda:0" --- MainProcess-MainThread backends.py:1018
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************
```

While running guppy server initialization command manually:
"/home/nano/Downloads/ont-guppy/bin/guppy_basecaller -p auto -l mega_test/guppy_log -c dna_r9.4.1_450bps_fast.cfg --quiet -x cuda:0"

I got "Unexpected option '-p' found on command line." is -p  (port) is supported in other guppy versions?

Thanks

**Comment by marcus1487** [comment]
@elirandv the `--guppy-server-path` command expects the path to the `guppy_basecall_server` executable, not the `guppy_basecaller`. This should resolve your issue.
