### ISSUE TITLE
 mimic bisulfite output after a run has completed?

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#158]
hello!

Quick question:

I started a run ( a few hours in) and realized that I want to try out the following tags, based on this segment from the documents. 
`In addition, the --mod-map-base-conv is provided to modulate the bases output by this format. This option is useful since the BAM and CRAM formats do not support modified bases and will convert all alternative bases to N for storage. For example, to mimic bisulfite output use --mod-map-base-conv C T --mod-map-base-conv Z C This can then be visualized by a genome browser as with standard bisulfite data.`

Is it possible to generate this mimiced bisulfite output, once a run is completed? Or should I just restart with the appropriate tags?

thanks!

**Comment by marcus1487** [comment]
It is not currently possible to create the bisulfite emulated output after a run is complete and the run should be restarted to obtain this output.

But I would not currently recommend this output. The bisulfite emulation mode was a stopgap until the downstream tools could handle the new BAM spec tag which holds per-read modified base calls. The most recent versions of IGV and JBrowse (popular genome browsers) now support visualization of the modified base BAM tag. This tag is output by the default `mod_mappings` output and this is now the recommendation for visualizing per-read modified base calls.

**Comment by fidibidi** [comment]
Thanks!
