### ISSUE TITLE
Specifying GPU devices

### ISSUE THREAD

**Issue by wentski** [nanoporetech/megalodon#160]
Hello,

We have recently upgraded our hardware in order to take advantage of GPU processing with our nanopore data. I am having trouble specifying GPU devices to use however. I am running the following command (which runs fine for CPU basecalling if I omit the "--devices" parameter):

megalodon test --outputs basecalls mappings mod_mappings mods --reference ER2796_reference_genome.fasta --guppy-server-path /bin/guppy_basecall_server --overwrite --devices 0

The guppy server fails to initialise and spits out the error in the guppy basecall server log: CUDA_ERROR_NO_DEVICE

It is entirely possible that I am making some obvious error as I am still very new to python. Any suggestions or advice are much appreciated. Please let me know if you need any more info.

**Comment by fidibidi** [comment]
Give this a try? 
--devices cuda:0

Also do you get any output when you type 
nvidia-smi 

in your command line?

**Comment by wentski** [comment]
Issue is solved. Turns out I didn't have the CUDA tookit/drivers installed on this machine. Thanks for the suggestions.
