### ISSUE TITLE
megalodon keeps running "Loading guppy basecalling backend"

### ISSUE THREAD

**Issue by AnunayS** [nanoporetech/megalodon#161]
![error](https://user-images.githubusercontent.com/85170013/123535018-e67fa000-d73e-11eb-84bc-e16ed5a743a1.png)

The above process keeps on running for more than 12 hours.

**Comment by AnunayS** [comment]
the log file is attached here.

thanks.

[log.txt](https://github.com/nanoporetech/megalodon/files/6728003/log.txt)

**Comment by marcus1487** [comment]
It appears megalodon is stuck waiting for the guppy server to startup. Could you provide the output in the guppy_log file (should also be in the megalodon output directory).Could you also give the output of the guppy server command found in the log file (`/opt/ont/guppy/bin/guppy_basecall_server -p auto -l megalodon_results/guppy_log -c dna_r9.4.1_450bps_modbases_5mc_hac.cfg --post_out --quiet`)

**Comment by AnunayS** [comment]
Sorry to say but there is no log file generated for guppy.

Is there anything I can do, maybe reinstalling guppy or installing a previous version of guppy.

Currently I have guppy version 5.0.11.

**Comment by marcus1487** [comment]
What output do you get when you run the guppy server command? Note that the successful command will hang waiting for clients to pass reads in and need to be killed manually. I just want to confirm that this guppy command works.

**Comment by AnunayS** [comment]
This is the output for guppy server command.

![Untitled](https://user-images.githubusercontent.com/85170013/123848083-ed700380-d934-11eb-8322-71406a206c50.png)

Is this the one you were expecting?

**Comment by marcus1487** [comment]
This is not the expected output. It appears there is an issue with your guppy installation. I will forward this issue on to the guppy support team.

**Comment by AnunayS** [comment]
Okay.

Thanks a lot.

Please let me know the guppy support team's response.

**Comment by fbrennen** [comment]
Hi @AnunayS -- just to check, can you try starting the basecall server using the precise command that @marcus1487 posted above?

`/opt/ont/guppy/bin/guppy_basecall_server -p auto -l megalodon_results/guppy_log -c dna_r9.4.1_450bps_modbases_5mc_hac.cfg --post_out --quiet`

**Comment by fbrennen** [comment]
Ah, can you also confirm for me:
* What operating system you're using, including its version
* How you installed guppy, including whether you're using the GPU (`ont-guppy`) or CPU (`ont-guppy-cpu`) version
* The full contents of the folder that megalodon saved the guppy logs to (that's the `megalodon_results/guppy_log` folder)
* Whether or not you can perform some normal basecalling with guppy (`guppy_basecaller -i <folder with some fast5 files> -s /tmp -c dna_r9.4.1_450bps_fast.cfg`, plus `-x cuda:all` if you're using the GPU version of guppy)

**Comment by AnunayS** [comment]
I am using Ubuntu 20.04 (installed from windows store) on Windows 10 laptop.

I have installed GPU (ont-guppy) version.

The contents of megalodon_results folder are as follows:
 - log.txt
 - guppy_log (folder) :
           - guppy_basecall_server-core-dump-db(folder) :
                          - attachments (folder) (empty)
                          - completed (folder) (empty)
                          - new (folder) (empty)
                          - pending (folder) (empty)
                          - settings.dat
                          
Also the guppy cannot do simple basecalling, the same error pops up.

**Comment by fbrennen** [comment]
Hi @AnunayS -- thanks for the quick response. How are you running Ubuntu? Are you dual-booting, or using something like WSL?

**Comment by AnunayS** [comment]
I am using WSL

**Comment by fbrennen** [comment]
Thanks for that -- we have unfortunately not tested guppy on WSL, and I can't assist with any debugging of that at the moment. What I can do is point you to a [guide](https://hackmd.io/@Miles/rkYKDHPsO) written by Miles Benton (@sirselim) -- you might be able to make some progress using that. We are planning on having Windows GPU support available very soon as well, so you may be able to cut out the WSL part of the loop entirely.

**Comment by marcus1487** [comment]
Given that this appears to be a guppy not megalodon issue I am going to close this issue. If further issues arise once the guppy installation is fixed please re-open this issue.

**Comment by AnunayS** [comment]
Thanks for the information.
