### ISSUE TITLE
Bioinformatic pipeline help

### ISSUE THREAD

**Issue by wentski** [nanoporetech/megalodon#165]
Our lab is completely new to analysing our own modified sequencing data. We have been trying to use megalodon to analyse our sequencing data on and of for some time now with no real success. I am hoping that someone here will at least be able to give us some advice on the correct bioinformatics pipeline to be using and how to interpret the output files produced. 

Firstly, some context. We have, in an otherwise DNA modification deficient host strain, sequencing data for our sample of interest, a positive control which we know should be modified at a specific motif and a negative control which should have no modification at all. What we need to find out is whether or not our sample of interest is modified at a specific motif and is so, what percentage is modified. 

I have (I think) managed to run megalodon on our data (command below) which has produced modified_bases.6mA.bed files. 

megalodon barcode01 --guppy-params "-d ./rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg --outputs basecalls mods mod_basecalls mappings mod_mappings --reference ER2796_reference_genome.fasta --guppy-server-path ~/Documents/MinIon/sequencing_files/ont-guppy/bin/guppy_basecall_server --overwrite --devices 0 --processes 100 --mod-motif Y GGTAAT 4

Someone had previously suggested using the “megalodon_extras validate” command to compare out negative control to our test sample. When passing both .bed files to this command I get the error:

AttributeError: 'NoneType' object has no attribute 'test_sites'

I have no idea what this is referring to. It is entirely possible that I am using the command incorrectly.

This is how far I have got so far. As I say, I have been attempting to analyse this data on and off in my down time, but we are reaching a point where I can’t really do much else until we figure out an effective pipeline for analysing our sequencing results. I would really appreciate any help/advice/suggestions on the following points:

1. Is the pipeline I am attempting to use appropriate for our analysis?
2. Are the commands I have used so far correct in terms of the parameters and outputs used?
3. If both of the above points are correct, how can I pass this data into “megalodon_extras validate”?
4. How do I interpret the results produced? (This point may become obvious to me once I have the correct pipeline and output files.)

Let me know if any more information is needed. Any help at all is most welcome.

**Comment by marcus1487** [comment]
This pipeline does look appropriate for this analysis. 

The megalodon command posted here looks reasonable. The final processing summary (number of different error types) would help confirm a successful run.

The `megalodon validate` command group is indeed the right next step for this setup. The `megalodon_extras validate aggregated_modified_bases` command will validate aggregated results against a known ground truth. In the setup described this would require the modified sample megalodon run passed to `--modified-bed-methyl-files` and the control sample passed to `--control-bed-methyl-files`. This command assumes that all call in the modified sample should be 100% modified and that all control sites called should be 0% modified. For fractionally modified samples (likely not applicable here) the `megalodon_extras validate compare_modified_bases` command would be used. Finally the `megalodon_extras validate results` command will provide validation of per-read modified base calls. Again modified sample megalodon results should be passed as the main argument and the control samples should be passed to `--control-megalodon-results-dirs`.

Hopefully this help. If you can post the full submitted commands and full error stack trace I can help further. This is likely a poorly worded error message indicating that control data was not specified. Also note that you can add the `-h` flag to any megalodon command to get detailed help for that command.

**Comment by wentski** [comment]
Thank you for the swift reply. That what I have done so far seems correct is in itself a relief. As I say, I have little linux/python experience so I am approaching this fairly blind. The -h help oputputs have indeed been very helpful in getting this far.

Apologies, I should have posted my command for the megalodon_extras validate aggregated_modified_bases command.:

megalodon_extras validate aggregated_modified_bases --modified-bed-methyl-files megalodon_results/modified_bases.6mA.bed --control-bed-methyl-files megalodon_results_wt/modified_bases.6mA.bed


Which seems quite similar to what you had suggested. The full output this gives me is:


Optimal_F1  Optimal_Threshold  Mean_Avg_Precision  ROC_AUC  Num_Modified_Stats  Num_Control_Stats  Sample
megalodon_results/modified_bases.6mA.bed: 3369it [00:00, 246680.69it/s]
[11:50:30] Mod coverage median: 10.00   mean: 10.94
Traceback (most recent call last):
  File "/home/sxtm38/tutorial-env/bin/megalodon_extras", line 8, in <module>
    sys.exit(_main())
  File "/home/sxtm38/tutorial-env/lib/python3.8/site-packages/megalodon_extras/__main__.py", line 225, in _main
    module._main(args)
  File "/home/sxtm38/tutorial-env/lib/python3.8/site-packages/megalodon_extras/validate_aggregated_modified_bases.py", line 337, in _main
    compute_val_metrics(
  File "/home/sxtm38/tutorial-env/lib/python3.8/site-packages/megalodon_extras/validate_aggregated_modified_bases.py", line 134, in compute_val_metrics
    for ctg, ctg_poss in ctrl_samp.test_sites.items()
AttributeError: 'NoneType' object has no attribute 'test_sites'


As far as I know there is no log file to accompany this command (?). It does create an output .pdf file but this is unable to open as it is damaged. Is there another parameter that I have missed here?

**Comment by marcus1487** [comment]
I've tracked down the bug in this command leading to your error. If you could re-install megalodon from the current github version (`pip install git+https://github.com/nanoporetech/megalodon`) and re-run your command it should work without error. Please do post if an error does occur.

**Comment by wentski** [comment]
Hi Marcus, many thanks, the re-install does seem to have fixed the issue with the `megalodon_extras validate aggregated_modified_bases` command. We are now getting a .pdf with results from the comparison (below). Unfortunately, it seems to be showing no modification from our positive control, both when calling for the specific motif and in all contexts. The control has previously been sequenced by pac-bio (although not the same physical sample) and have shown around 98% of sites methylated in the genome. I ran megalodon with the `res_dna_r941_min_modbases-all-context_v001.cfg` reiro model which I think should be correct. 

![image](https://user-images.githubusercontent.com/78024165/126164145-a541a2b8-a5c3-4ee5-9d7d-6cdbc7a68204.png)


Is there any obvious reason/error causing a lack of modified base detection? Any parameters which need to be altered for detection of modification in certain motifs? If not it seems that I will have to go back and re-sequence with fresh samples.

**Comment by marcus1487** [comment]
This does indeed appear to show that the modified sample does not show presence of 6mA. The one point would be to double check the motif offset. The integer is 0-based, so in your case refers to the second A in the motif. If the first A is intended then the value should be changed to `--mod-motif Y GGTAAT 3`.

We are also working on a newer version of this model in research. While we do not have a concrete timeline on this release, be on the look out for an updated model in Rerio and/or Guppy in the future.

**Comment by wentski** [comment]
Yes, I was specifying the correct base in the motif. Just one more question to clarify: when the samples were initially sequenced I used the modified base calling model in Minknow - would this in some way make the fast5 files incompatible with megalodon basecalling? (Though as I understand megalodon re-basecalls the raw data anyway, so probably not).

**Comment by marcus1487** [comment]
Yes you are correct. Megalodon re-basecalls from the raw data, so there should be no issues with running megalodon on reads that were called with a different model in minknow.
