### ISSUE TITLE
No alignment for 5mC and 5hmC modified base calling

### ISSUE THREAD

**Issue by rajitz** [nanoporetech/megalodon#167]
Hi, 

I'm trying to run the following command to get 5mC and 5hmC modified base calling:

megalodon /Users/rajats/Documents/Projects/MinION_Runs/ZymoControl/20210628_1515_MC-111208_0_AGW628_dbf99d27-20210630T144847Z/20210628_1515_MC-111208_0_AGW628_dbf99d27/fast5_pass/   --guppy-params "-d ./rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases_5mC_5hmC_CpG_v001.cfg  --outputs basecalls mappings mod_mappings mods per_read_mods  --reference /Users/rajats/Documents/RefData/hg38.fa --mod-motif mh CG 0  --processes 8 --guppy-server-path /Users/rajats/Documents/Software/ont-guppy-cpu/bin/guppy_basecall_server --verbose-read-progress 3 --output-directory /Users/rajats/Documents/Projects/MinION_Runs/ZymoControl/ZymoControl_Results --overwrite

I get 105990 reads with basecalls but "100.0% ( 103248 reads) : No alignment" (not sure why these two number of reads is different).  All the reads only have the canonical base C called despite message "Loaded model calls canonical alphabet ACGT and modified bases m=5mC (alt to C); h=5hmC (alt to C)".

I'm trying to align it to the hg38.fa reference file from UCSC.  Maybe I need to use a minimap2 index file instead?  Would mapping produce the modified base calls even though these are not present in the basecalls?  That seems to be the case from the documentation at https://nanoporetech.github.io/megalodon/algorithm_details.html - "Modified bases can also be output anchored to the basecalls as in Guppy, but these calls are generally not as accurate than the reference anchored calls."

Lastly, the data directory has folders fast5_pass and fast5_fail, and I'm only using the former - is that OK?  Also, can I skip the basecalling since the fastq file is already there/use the produced fastq file as a start for the mapping?  The initial command took 23 hours so it would be good to save some time.

Thanks!
Rajat

**Comment by marcus1487** [comment]
I’ll try to address each of the questions, but I’m on vacation this week, so I am not at my computer and might not have all the details. 

I’m not sure why the total and unaligned reads counts are off. It could be rounding error or some reads that were not accounted for in the tracking process. 

For the modified bases output, this is a bit of a new file format. The modified bases are not stored directly in the fastq (in basecalls) or the seq field in a mappings output bam file. Instead modified basecalls are stored in a custom tag in the bam file (in either basecalls or mappings). This tag is described in the hrs-spec GitHub pages. See some details here: https://nanoporetech.github.io/megalodon/file_formats.html#modified-base-mapping

The reason for these reads not mapping could have many sources. I’d have a try with a more standard production basecalling model to see if the model is really the issue or if maybe these reads possibly don’t originate from this reference. 

For the fast5_pass, this should certainly be fine. Depending on the analysis it mag make sense to use both folders, but this is not necessary for a large number of analyses. 

For the issue of starting from

**Comment by rajitz** [comment]
So I was aligning to the wrong sequence :-/.  Good to know about the other questions in the process.  I am just aligning to a 897 bp control sequence without any barcodes.  From the Nanopore forums, it's clear that barcode trimming removes the adapter as well, but there seems to be no standard tool any more to remove just the adapter.  It looks like it used to be porechop but it is not actively maintained any more/the author has discontinued it due to issues.  But I'm reading that the adapters can be taken care off by soft-clipping during alignment.  Any insight on that?  Thank you!

**Comment by marcus1487** [comment]
The adapters and barcodes are generally trimmed due to the fact that they do not align to the reference (and minimap2 trims quite aggressively with default parameters). There are always outlier cases where they may map, but these should be exceedingly rare. For most all use cases this is not a concern.

**Comment by rajitz** [comment]
Thanks - that's good to know!
