### ISSUE TITLE
Malformated files

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/megalodon#169]
HI,

Any suggestions as to what might be causing this?
```
DBG 16:07:27 : Encountered malformated fast5: raw_fast5/filtered26.fast5 4535f916-3694-43b6-af0a-852f235ba70b --- SignalExtractor000-ExtractSigThread000 fast5_io.py:209
```

These are fast5 files that have been filtered from a larger dataset using ont-fast5-api - they contain basecalling information and so are not - strictly "raw fast5". I can't work out from code inspection why these are failing - they work in all other tools - nanopolish etc etc.

Thanks,

Matt

**Comment by marcus1487** [comment]
This shouldn’t be doing much more than using the ont_fast5_api to extract the raw signal. I’m off this week so can’t give the exact commands, but if you could check that the `ont_fast5_api.get_fast5_file(“ raw_fast5/filtered26.fast5”).get_read(“ 4535f916-3694-43b6-af0a-852f235ba70b”)` call works that would be a good first step. If this fails hopefully that could help track down the issue.

**Comment by mattloose** [comment]
I've partially resolved it now - the issue is VBZ compression - if I switch the files back then it works.

**Comment by liuyangzzu** [comment]
Hi, I encountered the same error, how do you solve this problem? Thank you!

**Comment by mattloose** [comment]
From memory the issue was that I was using a VBZ compressed file in an environment that didn't have the VBZ compression plugin installed. So either install the VBZ plugin in whichever environment you are in or try checking the compression format of the fast5 file you are looking at.
