### ISSUE TITLE
Some confusion about the result of Aggregated modification call

### ISSUE THREAD

**Issue by weir12** [nanoporetech/megalodon#17]
Hi:
@marcus1487  I'm glad to experience the amazing new tool you developed ,bravo!
I have some questions about column definitions in output file that is meet   **bedMethyl format**.
```
line 5:Score from 0-1000. Capped number of reads
```
What exactly does this score mean?score of methylation?regularization depth?
```
line Percentage of reads that show methylation at this position in the genome
```
Does this percentage refer to the num_mod_read/num_coverage in Specified site?
So are both of these numerical indicators used to measure the reliability and degree of the modification?
Thanks again for your help!

**Comment by marcus1487** [comment]
Hi @weir12 , I'm glad you have find megalodon a useful tool!

For these scores, the "Capped number of reads" is the valid* coverage at the site. The `percentage of reads that show methylation at this position in the genome` is indeed the fraction of modified over total valid* coverage at a site.

Thus your interpretation that these values "measure the reliability and degree of the modification" is correct.

* - For the default aggregation method (binary threshold) only read/site combinations where the predicted state (modified or canonical) is >75% confident are included in these values. Thus the coverage value may not match the raw coverage for the site.

A second aggregation method (expectation_maximization) was added in the most recent release. With this method the coverage value should match the raw coverage, but this method has some issues pushing the estimated proportion towards 0 or 1 and has thus not been made the default for now.

**Comment by weir12** [comment]
Thank you for your support!
My interpretation : 

**valid coverage = raw coverage - ambiguous part**
**percentage = num of modified / valid coverage * 100 %**

Am I right?

**Comment by marcus1487** [comment]
Yes. That is correct.
