### ISSUE TITLE
Guppy server timeout

### ISSUE THREAD

**Issue by rajitz** [nanoporetech/megalodon#172]
Hi, I'm getting the following error message running megalodon to do modified base calling:

    54.2% ( 233824 reads) : Guppy server timeout (see --guppy-timeout argument)                             
    45.8% ( 197361 reads) : Guppy server unable to recieve read 

So it seems that all reads are either getting timed out or Guppy isn't able to receive them - is that indeed the case?  From the doc:

--guppy-timeout
Timeout to wait for guppy server to call a single read in seconds.
Default: 5.0

Would you suggest increasing this parameter or can I get around the error message in some other way by say setting it to 0?  It was running for more than 2 days before crashing.  I'm running it with 15 out of 16 processing threads available (I don't have access to a GPU).  The command is:

megalodon /Users/rajats/Documents/Projects/MinION_Runs/ZymoControl/20210628_1515_MC-111208_0_AGW628_dbf99d27-20210630T144847Z/20210628_1515_MC-111208_0_AGW628_dbf99d27/   --guppy-params "-d ./rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases_5mC_5hmC_CpG_v001.cfg  --outputs basecalls mappings mod_mappings mods per_read_mods  --reference /Users/rajats/Documents/RefData/ZymoControl.fa --mod-binary-threshold 0 --mod-motif mh CG 0  --processes 15 --guppy-server-path /Users/rajats/Documents/Software/ont-guppy-cpu/bin/guppy_basecall_server --verbose-read-progress 3 --output-directory /Users/rajats/Documents/Projects/MinION_Runs/ZymoControl/ZymoControl_Results --overwrite

Thanks!

**Comment by marcus1487** [comment]
I would recommend upgrading megalodon to the most recent version. There were some changes made recently to more effectively handle CPU basecalling (though it is still quite slow without GPU resources).

Using the most recent version I would recommend decreasing the number of reads submitted simultaneously in each processes (e.g. `--guppy-concurrent-reads 4`), increasing the guppy timeout (e.g. `--guppy-timeout 300`). You may also have some luck lowering the number of processes (e.g. `--processes 4`).

**Comment by rajitz** [comment]
I have version 2.3.3, which is the latest one, correct?  

I'm now actively looking for GPU machines.  How many GPUs would you recommend?  I see that "Device names can be provided in the following formats: 0, cuda0 or cuda:0".  I'm wondering if the --devices parameter will have to specify the number of GPUs or if it will automatically use all of them.  The --processes parameter seems to be only for CPUs.

Thank you.

**Comment by rajitz** [comment]
Would even 1 GPU provide orders of magnitude speed-up?  Thanks.

**Comment by marcus1487** [comment]
Yes. Even a single GPU allows for about an order or two faster processing times (depending upon the quality of CPU and GPU resources).

For the `--devices` and `--processes` arguments, by default megalodon uses a single CPU process and no GPU devices. The `--devices` argument takes multiple arguments, so to specify devices 0, 1 and 3 specify `--devices 0 1 3`. Though CPU alone is not fast enough, specifying a reasonable number of megalodon workers via `--processes` can still help to speed up processing. There is not a robust formula for how to identify the optimal number of worker processes, but for a single GPU generally 4-16 works well.

**Comment by rajitz** [comment]
So if I'm reading this correctly 1 GPU can work alongside say 4 CPUs, correct?  If there is only one GPU on the machine, would it always be specified with "--devices 0"?  I've never used GPUs before so just wanted to be sure.  Cheers.

**Comment by marcus1487** [comment]
Yes. The GPU is used to accelerate the basecalling neural network, but most all other computations use CPU resources.

Yes generally `--devices 0` would specify a lone GPU on a node, but systems can be setup in many different ways. Best to check with your sys admin to be sure.
