### ISSUE TITLE
m6A & mitochondrial DNA

### ISSUE THREAD

**Issue by TheresaLueth** [nanoporetech/megalodon#173]
Thanks a lot for providing this great tool. 
I have a question regarding the detection of m6A. My colleagues and I have sequenced mitochondrial DNA (MinION/GridION, r9.4.1 flow cell) and previously only analyzed DNA methylation in a CpG context with Megalodon but now we would like to also look at m6A. Which base calling model would you recommend with the new Guppy version (5.0.11) to detect m6A?
Thank you for your help.

**Comment by marcus1487** [comment]
The current recommendation for 6mA DNA calling is the `res_dna_r941_min_modbases-all-context_v001.cfg` model from [Rerio](https://github.com/nanoporetech/rerio). We are working to improve this model (and likely generate a dedicated 6mA DNA model; current version calls 5mC+6mA in all contexts) and will initially deposit a new model into rerio when it is trained.

**Comment by TheresaLueth** [comment]
Thank you very much for the quick answer.
Good to know. Can you perhaps give an estimation of when this new model will be available?

**Comment by marcus1487** [comment]
Training and release of new models is an active area of research, but unfortunately we do not have a concrete timeline for the release of this model at this time.
