### ISSUE TITLE
Methylation Analysis - Validating methylation results 

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#174]
Hello Marcus!

Megalodon has been working splendidly, so this is more so a question. 

With our bedmethyl output files, we are trying to do some validation on the results, so we have an idea of the quality of results we've gotten. 

We processed HG002 Promethion (s3://ont-open-data/gm24385_2020.09/flowcells/20200914_1354_6B_PAF27096_e7c9eae6/) 

**We were wondering if you may have any thoughts or suggestions on where we might be able to find methylation disorder data sets that we might be able to use as a control for comparative analysis.** 

For context, we've been playing around with methylkit for our downstream methylation analysis pipelines... 

Thanks!

**Comment by marcus1487** [comment]
Hi @fidibidi , I don't have any particularly great pointers for control data to match this sample. Methylation control samples can be tricky to figure out and matching the right validation/analysis with the right samples is very important. If you have any questions on how to perform validation analyses based on a given set of samples I would be happy to provide guidance.

**Comment by fidibidi** [comment]
So to summarize:

We have a HG002 Promethion Flowcell which we ran through Meg, (found from the ONT Open Datasets)

And after some time searching, links to the rest of the HG00* family, run on Promethion ( found here [https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=NHGRI_UCSC_panel/] )

We are currently planning on running the Mother ( HG004) through Meg, and use that as a way to do differential methylation analysis via MethylKit

But any thoughts about the datasets we have, and how to perform validation analyses, would be much appreciated!

**Comment by marcus1487** [comment]
If you are looking for results from alternative technologies, the ENCODE consortium performed WGBS on HG001 ([see here](https://www.encodeproject.org/experiments/ENCSR890UQO/)). I don't see any public experiments there for HG002 or HG004 unfortunately. Hopefully another consortium might have public data for these samples. Is there another type of validation data in which you were interested.

I would also suggest having a look at the suite of tools within megalodon to validating results. `megalodon_extras validate -h` and `megalodon_extras modified_bases create_ground_truth/create_motif_bed -h`.
