### ISSUE TITLE
QC Metrics of Megalodon runs

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#177]
Is there a way to generate a QC summary of the Megalodon run? 

Total read length, percent aligned,  and coverage depth? 

Thanks!

**Comment by marcus1487** [comment]
Megalodon has a number of validation commands. The first one to look at is `megalodon_extras validate results`. This will produce a text report and a set of plots. [See docs here](https://nanoporetech.github.io/megalodon/extras_validate.html).

**Comment by fidibidi** [comment]
Thanks, sorry for the obvious question! 🤦
