### ISSUE TITLE
 Data covering index does not exist.

### ISSUE THREAD

**Issue by hy-Yang** [nanoporetech/megalodon#178]
Hi, recently I encountered this data covering index not exist error. 

The commend I used are:
$megalodon $fast5 \
--guppy-server-path /the/path/ \
--guppy-params "-d /pathto/rerio/basecall_models/ --num_callers 20" \
--guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg \
--output-directory $outdir \
--write-mods-text \
--sort-mappings \
\--outputs mod_mappings mods per_read_mods \
--reference $ref \
--mod-motif m CG 0  \
--mod-map-emulate-bisulfite  \
--devices 0 1 2 3 \
--processes 20 \
--overwrite

The **mod_mapping.5mC.bam** was generated, and the **per_read_modified_base_calls.db**  **per_read_modified_base_calls.txt** are also created. The bed file is missing.

It seems that the .bd file does not have cov_index
How could I manually get the bed file?

also what does the --ipc_threads influence.

Thanks

**Comment by marcus1487** [comment]
Was the run cut short for some reason? The last line of output should read `Mega Done` for a successfully completed run. 

As long as the database is not corrupted you should be able to run the `megalodon_extras modified_bases index_database` command to compute the index for the `.db` (database) file. Then the `megalodon_extras aggregate run` command will produce the aggregated results (`.bed` file for mods).

As for the `--ipc_threads` option, this stands for inter-process communication threads. I don't have a great idea what the exact behaviors are for this option as it is an option for guppy and not megalodon. I would suggest to post on the community for help with this option.

**Comment by hy-Yang** [comment]
The run was terminated early, not sure why. The `Mega Done` was not shown.

I tried `megalodon_extras modified_bases index_database --megalodon-directory /the/directory/to/.db` on hpc, but it returns back 
`[12:22:26] Creating modified bases database index
Segmentation fault (core dumped)
` 
Do you have any suggestions why this happens?

Thanks a lot!!

**Comment by marcus1487** [comment]
This unfortunately looks as though the database has been corrupted. This command makes only a single call to sqlite from python and this is almost certainly the source of this segmentation fault. From here the best course of action would unfortunately be to run the megalodon call again. You can set the `--database-safety` option to `1` or `2` (see `megalodon --help-long` for details) in order to avoid a corrupted database on unexpected exits in the future, but note that his may slow storage speeds.
