### ISSUE TITLE
Can't kill guppy_basecall_server

### ISSUE THREAD

**Issue by Predbio** [nanoporetech/megalodon#179]
I am not an ONT/minion user though I may have installed software at some point in the past to try it out. I am running MacOS 15.1. My problem is that guppy_basecall_server is run by root and I cannot kill the process. When I kill it in Activity Monitor it almost immediately returns, with user Root. I am not running any ONT software though i do have MinKNOW in my applications folder. It is not an active process at the moment. How do I remove this process?

**Comment by marcus1487** [comment]
This is likely related to the MinKNOW installation and not megalodon. I'm not sure what the correct course of action would be here. I would recommend posting on the nanopore community page (https://community.nanoporetech.com/) with the question. Note that a login is required to post on the community page, but I believe no purchase is necessary to create an account.
