### ISSUE TITLE
Variant Calling/Phasing Issue with Reference

### ISSUE THREAD

**Issue by jgribble67** [nanoporetech/megalodon#180]
I am running Megalodon with a list of candidate variants in a VCF file. I created the VCF file using BBMap's mutate.sh, so I know it's from the right reference. Here is my megalodon command:
megalodon 6-1-1/ --outputs mappings variants variant_mappings --reference SARSCoV2.fasta --variant-filename SARS2_nsp12_candidate_sort.vcf --output-directory 6-1-1-megalodon/ --processes 32 --devices 0 --verbose-read-progress 3 --guppy-config dna_r9.4.1_450bps_hac.cfg --haploid --guppy-server-path /home/denison-thelio/ont-guppy/bin/guppy_basecall_server --overwrite --not_recursive

And every time, I get the following error:

[16:10:56] Running Megalodon version 2.3.1
[16:10:56] Loading guppy basecalling backend
[2021-08-04 16:10:57.897911] [0x00007f3394491700] [info]    Connecting to server as ''
[2021-08-04 16:10:57.899013] [0x00007f3394491700] [info]    Connected to server as ''. Connection id: fab25e62-bcfa-4abc-a202-010e9e75a556
[16:10:57] Loading reference
[16:10:57] Loaded model calls canonical alphabet ACGT and no modified bases
******************** WARNING: Adding "per_read_variants" to --outputs since "variant_mappings" was requested. For full phased variant pipeline add "variants" or run aggregation after run is complete. ********************
[16:10:58] Loading variants
******************** WARNING: Variants file must be indexed. Performing indexing now. ********************
****************************************************************************************************
	ERROR: Reference sequence file does not match reference sequence from variants file.
****************************************************************************************************

**Comment by marcus1487** [comment]
The megalodon `log.txt` output file should contain information on the offending VCF record. If you can post the log.txt file I can have a look. It should be rather short since this error occurred during initialization. You should see a line with the text `VarSeqMismatchError` in it containing information about the variant containing reference sequence mismatched to the VCF file (e.g. extract with `grep VarSeqMismatchError mega_res/log.txt`).

**Comment by jgribble67** [comment]
Here is the log.txt file! Thank you so much for looking at it.

[16:10:56] Running Megalodon version 2.3.1
DBG 16:10:56 : Command: """/home/denison-thelio/anaconda3/bin/megalodon 6-1-1/ --outputs mappings variants variant_mappings --reference SARSCoV2.fasta --variant-filename SARS2_nsp12_candidate_sort.vcf --output-directory 6-1-1-megalodon/ --processes 32 --devices 0 --verbose-read-progress 3 --guppy-config dna_r9.4.1_450bps_hac.cfg --haploid --guppy-server-path /home/denison-thelio/ont-guppy/bin/guppy_basecall_server --overwrite --not-recursive""" --- MainProcess-MainThread megalodon.py:1743
[16:10:56] Loading guppy basecalling backend
DBG 16:10:56 : Guppy version: "4.5.4" --- MainProcess-MainThread backends.py:828
DBG 16:10:56 : Pyguppy version: "4.5.4" --- MainProcess-MainThread backends.py:829
DBG 16:10:56 : guppy server init command: "/home/denison-thelio/ont-guppy/bin/guppy_basecall_server -p auto -l 6-1-1-megalodon/guppy_log -c dna_r9.4.1_450bps_hac.cfg --post_out --quiet -x cuda:0" --- MainProcess-MainThread backends.py:904
DBG 16:10:56 : Found guppy log file: 6-1-1-megalodon/guppy_log/guppy_basecall_server_log-2021-08-04_16-10-56.log --- MainProcess-MainThread backends.py:919
DBG 16:10:57 : Connecting to server --- MainProcess-MainThread backends.py:776
DBG 16:10:57 : init_test_read BasecallingCompleted --- MainProcess-MainThread backends.py:1065
[16:10:57] Loading reference
[16:10:57] Loaded model calls canonical alphabet ACGT and no modified bases
******************** WARNING: Adding "per_read_variants" to --outputs since "variant_mappings" was requested. For full phased variant pipeline add "variants" or run aggregation after run is complete. ********************
[16:10:58] Loading variants
******************** WARNING: Variants file must be indexed. Performing indexing now. ********************
DBG 16:10:58 : VarSeqMismatchError 13846:G:A --- MainProcess-MainThread variants.py:1604
****************************************************************************************************
	ERROR: Reference sequence file does not match reference sequence from variants file.
****************************************************************************************************

**Comment by marcus1487** [comment]
This bit `VarSeqMismatchError 13846:G:A` indicates that a variant at position 13846 contains a G as the reference base in the VCF file and an A as the reference base in the VCF file. This is the reason for the error being raised. If it can be confirmed that this is not the case for the given inputs I can have a look at this to see if there is a bug in the megalodon code to parse these inputs.

P.S. This logging line is not all that informative. This will be corrected in the next release.

**Comment by marcus1487** [comment]
No problem. There is not explicit code to separate megalodon results by barcode, but the `megalodon_extras aggregate run` command accepts the `--read-ids-filename` argument which could include the read ids for a barcode. This can then be run for each barcode to produce the desired results. Best of luck in your research!
