### ISSUE TITLE
devices argument returning syntax error 

### ISSUE THREAD

**Issue by malonematt** [nanoporetech/megalodon#182]
When I run this script on a HPC 
`megalodon /scratch/teefy/ \
   --guppy-server-path /project/bbenayou_34/malone/nanopore/pkgs/guppy_v5/ont-guppy/bin/guppy_basecaller \
  --reference /project/bbenayou_34/teefy/RNA_seq/killifish_RNA_seq/Masked_Genome/Masked_061021/Masked_Genome_061021.fa \
 --devices 1 1 \
  --output basecalls mod-basecalls per_read_mods mods  \
 --ouput-directory /project/bbenayou_34/malone/nanopore/methylation/megalodon_results210810/`
I get this error and it returns with an error code 1
`==========================================
SLURM_JOB_ID = 5447433
SLURM_JOB_NODELIST = d14-14
TMPDIR = /tmp/SLURM_5447433
==========================================
  File "/project/bbenayou_34/malone/nanopore/scripts/meg0810.sh", line 8
    --devices 1 1 \
              ^
SyntaxError: invalid syntax
~                             ` 
I checked to make sure the GPUs really were named 0 and 1 and they are.  
I have also tried entering 0, cuda0, and cuda:0. None of those worked either. 
Does anyone know what might be causing this error and how I might fix it?
Many thanks

**Comment by marcus1487** [comment]
This is indicating a bash script syntax error. This does not have to do with megalodon on the devices argument. I would suggest removing line break formatting from the command (there is likely a space after a line break or some thing similar which is causing this invalid bash syntax error).

**Comment by malonematt** [comment]
I tried that and am still getting the same issue. 
Here is the error log from slurm: 

`==========================================
SLURM_JOB_ID = 5477964
SLURM_JOB_NODELIST = d11-03
TMPDIR = /tmp/SLURM_5477964
==========================================
  File "/project/bbenayou_34/malone/nanopore/scripts/meg0810.sh", line 3
    megalodon /scratch/teefy/ --guppy-server-path /project/bbenayou_34/malone/nanopore/pkgs/guppy_v5/ont-guppy/bin/guppy_basecaller --reference /project/bbenayou_34/teefy/RNA_seq/killifish_RNA_seq/Masked_Genome/Masked_061021/Masked_Genome_061021.fa --devices 1 1 --output basecalls mod-basecalls per_read_mods mods --output-directory /project/bbenayou_34/malone/nanopore/methylation/meg_results210811


                                             ^
SyntaxError: invalid syntax
~                               `

And here is the script :  

`#!/bin/bash 

megalodon /scratch/teefy/ --guppy-server-path /project/bbenayou_34/malone/nanopore/pkgs/guppy_v5/ont-guppy/bin/guppy_basecaller --reference /project/bbenayou_34/teefy/RNA_seq/killifish_RNA_seq/Masked_Genome/Masked_061021/Masked_Genome_061021.fa --devices 1 1 --output basecalls mod-basecalls per_read_mods mods --output-directory /project/bbenayou_34/malone/nanopore/methylation/meg_results210811
~                                                                            `

**Comment by marcus1487** [comment]
This is again a bash syntax error. You have a tilde on the last line of the script. This is not valid bash syntax.
