### ISSUE TITLE
guppy 5.0.11 model vs rerio [question]

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/megalodon#187]
Hi,
I've returned to megalodon after a while and was wondering if `dna_r9.4.1_450bps_modbases_5mc_hac.cfg` from guppy 5.0.11 is now more appropriate than the `res_dna_r941_min_modbases_5mC_CpG_v001` rerio file, which is now 15 months old. 
Cheers

**Comment by JWDebler** [comment]
I guess this question answered itself at last nights Nanopore webinar. It was mentioned that the model file in guppy 5 is what was previous the rerio file.

**Comment by marcus1487** [comment]
Yes. This is correct. Once Rerio models are verified to a greater extent they are transferred into the production Guppy basecaller. These files are not equivalent though. The `dna_r9.4.1_450bps_modbases_5mc_hac.cfg` should be the same as the `res_dna_r941_min_modbases_5mC_v001` model from rerio.
