### ISSUE TITLE
[Question] What is the command run for the alignment step?

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#189]
Hi, sorry the title of this is maybe a little confusing. 

I'm just wondering, is the alignment step in megalodon doing essentially the same thing as this command?

minimap2 -a -x map-ont reference.fasta output.fastq | samtools sort -T tmp -o output.sorted.bam
samtools index output.sorted.bam

I'm trying to compare Nanopolish and Megalodon pipelines, and was curious if at least up to the alignment step, the outputs should be almost identical?

Seeing as both require:
1. guppy for basecalling
2. minimap2 ( or mappy) to do alignment

Just trying to get a better understanding!

Thanks!

**Comment by marcus1487** [comment]
Yes. This is essentially the mapping step performed in megalodon, but there are a couple of caveats. 

The first is multi-mapping reads. By default megalodon only takes the primary alignment. Set `--allow-supplementary-alignments` to output all mappings produced (but note that this may cause tricky to track down issues for downstream analysis; e.g. single nanopore signal locations indicating modifications on many reference positions). Note also that the primary mapping from the python interface to minimap2 used by megalodon does not necessarily produce the same primary alignments as the command line minimap2 (see minimap2 issues pages).

The second caveat is that the python interface to minimap2 does not produce identical mappings to the command line interface. I believe this has to do with how mappings to different shards of the data are processed (again minimap issues pages).

I hope this helps!
