### ISSUE TITLE
Generate mod_mappings.bam after a megalodon run?

### ISSUE THREAD

**Issue by fidibidi** [nanoporetech/megalodon#190]
Hello!

Perhaps a silly question, but I ran a sample through megalodon and forgot to include the mod_mappings as one of my desired outputs, although I did include mods. 

I have the per_read_modified_basecalls.db file, and I was wondering was it possible to generate the mod_mappings.bam without having to re-run the whole sample? 

Thanks!

**Comment by marcus1487** [comment]
This is not currently implemented, but the information to produce this output is in the combination of the mappings and the per_read_mods outputs. It would not be too much work to get a working version of this, but an efficient version would take a bit longer. The main bottleneck will likely be the extraction of the per-read modified base calls. We will add this to the requested feature list for s future release.
