### ISSUE TITLE
How to control the minimap2 parameters?

### ISSUE THREAD

**Issue by MeHelmy** [nanoporetech/megalodon#193]
Thank you for the efforts,

What was the minimap command used to produce `mappings.bam` file. Is there a way to pass specific parameters to miniamp like `--MD`?

Thanks,
Medhat

**Comment by marcus1487** [comment]
The `mappings.bam` file is created using the pysam python package and mappings are produced via the `mappy` interface to `minimap2`. This output is not intended to support all features of the command line minimap2 interface as the mappy results must follow certain specifications within megalodon (i.e. splice mode is not supported and would cause megalodon fail in unexpected ways).

For the MD tag specifically, I would recommend the `samtools calmd` command (http://www.htslib.org/doc/samtools-calmd.html) to annotate the mappings.bam file with the MD tag.

**Comment by MeHelmy** [comment]
Thank you,
So, we can not change how the megalodon produces the alignment, right?

Best,
Medhat

**Comment by marcus1487** [comment]
There are a number of options to adjust the mapping output. Run `megalodon --help-long` and see all applicable options under the mapping section.

**Comment by MeHelmy** [comment]
Thank you!
