### ISSUE TITLE
Calling 5mC methylation in AT rich regions

### ISSUE THREAD

**Issue by jcolicchio-soundag** [nanoporetech/megalodon#196]
We are using megalodon to call methylation using the rerio all context 5mC model in a plant system, and generally having pretty good success.  However, we have noticed, that in a few regions of the genome that have very high A/T levels (over 70%) megaldon is not making any methylation calls one way or another.  We have tried this for many samples and it is always the case.  Sequencing was done using an r9.4.1 flow cell.

Is the model trained to not make calls in regions with low-complexity/low CG levels?  
Are there any parameters to be tweaked to get calls in these regions, or does the model to call methylation break down in these sorts of regions?

**Comment by marcus1487** [comment]
If reads are mapping to these locations, but modified base calls are not found in the modified base bedmethyl output it is most likely that the calls are not confident and are being filtered at the aggregation step. The `--mod-binary-threshold` parameter sets this hard cutoff. The default value is 0.8. This means that any call (canonical or modified) with a probability < 0.8 is not included in the aggregated count. Setting this parameter to a lower value should resolve the issue, though it may introduce more noise from lower quality calls.

I have not done a specific analysis of the released models in AT rich regions, but it is possible the model has a bias to make poor quality calls in these regions. we are working internally on solutions to remove bias such as this with a new model framework.

**Comment by marcus1487** [comment]
The new methylation calling models provided by Remora (integrated in Megalodon and Bonito) should improve this performance. This is included in the latest 2.4.0 release.
