### ISSUE TITLE
Megalodon/Guppy server still running when finished processing

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/megalodon#199]
I'm running the latest version of megalodon with guppy (v5.0.16), and one of my runs finished but megalodon/guppy_basecall_server is still running and not doing anything. It made all the output files that's normally generated at the end (eg. per_read_mods text), but it just appears to pause. Otherwise it doesn't appear that anything went wrong since I received all the output files. The weird thing is that I was running megalodon using another GPU on the same server and that one finished fine with the "Mega done" at the end. Where can I look to see what's causing this issue?

**Comment by alvinwt** [comment]
Hi @billytcl, did you get the mods_mapping output as well? I am having the same issue and the bam file is missing the EOF. I think megalodon is not exiting properly in this case.

**Comment by marcus1487** [comment]
I understand that this is very frustrating and will attempt to fix this before the next release. Could you have a look in the log file to see if there are any errors near the end of the log file? If you could post the log file I'd be happy to take a look and see if I can find any clues to help debug this issue.
