### ISSUE TITLE
How to interpret basecall anchored modification scores.

### ISSUE THREAD

**Issue by utrori** [nanoporetech/megalodon#20]
Hi,

I have successfully called bases along with modification using Megalodon.
However I am not sure how to interpret the HDF5 data.
In the documentation, the values are decscribed as "similar to the guppy output format descibed on the community page", but I could not find the corresponding guppy documentation.

Is the number something like log10 value of the posterior probability of the base being edited?

Thank you.

**Comment by marcus1487** [comment]
These scores are the natural log of the posterior probability that a base is modified or canonical. 

If you are mapping the reads to a reference genome, I would recommend that you use the `mods` or `per_read_mods` output as these calls generally improve the modified base scores over the basecall anchored calls. This also removes the ambiguity around mapping basecall-anchored mod calls onto a reference genome.

**Comment by utrori** [comment]
Thank you very much for the answer.
With the value interpreted as natural log of the posterior probability of a base is edited (I got just one value for 5mC), the analysis of my data seems to be consistent and fine.
Since the genomic region that I am interested in is highly variable, the full-length mapping seems to be a bit unstable. That is why I want to try software that does not require mapping.
