### ISSUE TITLE
Changing mapping parameters - 50x coverage - regions with 0 cov paramter

### ISSUE THREAD

**Issue by mvolar** [nanoporetech/megalodon#201]
Hello,

I am using latest Megalodon version in order to detect 6mA and 5mC methylation levels in a genome of interest, and have already obtained (some) results. The expected coverage of the genome is (based on base pair count and the relative genome size) around 50x (11gb). However when I calculate the coverage of all the bases as provided by the *.6mA.bed file I get:

```summary(cov):  
Min.    1st Qu.   Median   Mean     3rd Qu.     Max. 
0.000    1.000    3.000    4.571    6.000      1317.000 
```

The problem here is that my genome is heavily repetitive (30% of main satellite) but the reference genome only has around 2% of the same satellite assembled, BUT the assembled genome is fairly contiguous with less than a 100N's in its entirety, so minimap2 shouldn't be braking the mapped reads as much as is does and produce such low coverage levels in some regions. (only 6% of the reads were disregarded as "no alignment" in the mapping log), so the only possibility is that most of the reads were erroneously mapped to the reference genome, or there are a lot of errors in the sequences themselves.

Additionally by examining coverage levels we have also found that even in regions which are know euchromatic and very gene rich (almost no repetitions) the remains fairly low (<6) instead what we expected 50x. So either the reads disappeared or they get erroneously mapped to individual regions comprising of the main satellite (regions with 700x coverage). 

I was wondering if there is a way to talk to "mappy" directly from the command line in order to tweak the parameters of the mapping in order to produce more contiguous mappings OR disregard those with very high secondary scores (which would insinuate that they are bad reads/entirely satellite covered)

**Comment by mvolar** [comment]
I forgot to mention the --outputs were specified and the .bam files showed the 50x average coverage, which enticed me to make this post. In other news I have only managed to rerun the complete process and solved the problem of low coverage, the aggregate run has been a complete failure (hadn't been able to even run it with different settings) can you provide any guidance on how to run it?

**Comment by marcus1487** [comment]
If you've run megalodon with the `--outputs per_read_mods` (or `mods`) then you should be able to re-aggregate the per-read mods with the following command `megalodon_extras aggregate run --outputs mods --megalodon-directory path/to/megalodon/results --mod-binary-threshold 0.6 --processes 8`. The new results will be written out to the same megalodon results directory.

You might also have a look at the https://github.com/epi2me-labs/modbam2bed package for aggregation from modbam outputs (either mod_basecalls or mod_mappings) if you've output these from megalodon. This is likely the future direction for aggregation of per-read results.

**Comment by mvolar** [comment]
Thanks for the fast response!

Both the megalodon_extras and modbam2bed seem to work fine for now, just one more question and you can close the thread, is there a way to stop the megalodon after the GPU test automatically or do we have to manually find the end of the step and then kill the process?

**Comment by marcus1487** [comment]
I'm not exactly sure about this last question. Megalodon should shut down any guppy servers spawned. There may be edge cases when this happens, but all efforts have been made in the current release to close all GPU connections opened within megalodon. This includes if megalodon is killed via a sigterm or similar method. Older versions of megalodon may not close such resources as robustly. I hope that helps, but if this issue is of larger concern I would recommend opening a new issue to avoid sidetracking this thread.
