### ISSUE TITLE
Seek suggestions on variant calling?

### ISSUE THREAD

**Issue by zhanxw** [nanoporetech/megalodon#21]
Hello, megalodon 2.0.0 requires a variant file in VCF format (`--variant-filename VARIANT_FILENAME`) for variant calling.
Can you provide advices on how to prepare that variant file?

**Comment by marcus1487** [comment]
This depends a lot on the biological question being asked. 

We currently do not have a data/sample driven method to produce potential variants to feed into megalodon. This is an area of active research. 

Megalodon is currently designed to make calls at a set of variants known before sequencing the sample. As an example, when sequencing a human sample one might want to test a set of known clinically relevant SNPs from public databases.

It is also possible to create a VCF with a large number of proposed variants, but note that this may slow compute performance. Follow this [section from the README](https://github.com/nanoporetech/megalodon#high-density-variants) for processing high-density variants.

**Comment by zhanxw** [comment]
Thank you.
