### ISSUE TITLE
Can't install megalodon 

### ISSUE THREAD

**Issue by juliofinalet** [nanoporetech/megalodon#211]
Hi There,

I need some help installing megalodon. I could installed conda and created an enviroment "megalodon" which was activated, but when I use conda install megalodon I get the error shown below. 
Any help will be welcome.

Thanks in advance !

Julio

[Nov/06 16:19] vsc30851@tier2-p-login-1 /lustre1/project/stg_00019/research/Nanopore/Julio/miniconda3/envs/megalodon $ conda install megalodon
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - megalodon

Current channels:

  - https://conda.anaconda.org/intel/linux-64
  - https://conda.anaconda.org/intel/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by marcus1487** [comment]
Megalodon is on the bioconda channel. Run `conda config --add channels bioconda` Before trying to install megalodon.

**Comment by juliofinalet** [comment]
Hi Marcus,
Thanks for your quick reply. I have tried also to install from there but it did not work using:
conda install -n megalodon -c bioconda megalod
now I have done what you suggested and still nothing:


 [Nov/06 16:30] vsc30851@tier2-p-login-1 /lustre1/project/stg_00019/research/Nanopore/Julio/miniconda3/envs/megalodon $ conda config --add channels bioconda
✔ [Nov/06 16:33] vsc30851@tier2-p-login-1 /lustre1/project/stg_00019/research/Nanopore/Julio/miniconda3/envs/megalodon $ conda install megalodon
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                                                                                               failed

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - megalodon -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17

**Comment by juliofinalet** [comment]
**Also here more info on the error. I seems to be an issue with the python version:**

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - megalodon -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0
  - megalodon -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17

**Comment by marcus1487** [comment]
One of megalodon’s dependencies, and therefore megalodon, is not compatible with python 3.9. You’ll have to downgrade your python installation in order to rum megalodon at this time.
