### ISSUE TITLE
Can we take aligned BAM file as input to generate variant calls by megalodon?                                                                           

### ISSUE THREAD

**Issue by emily288** [nanoporetech/megalodon#216]
Dear developers,

I'm trying to demonstrate megalodon performance by using PCAWG public database. But they only have aligned BWA files rather than fastq or fast5 files. So can I take BWA file as input to generate variant calls in megalodon?
Or do you know a doable method that converts BWA to fastq?

Thank you for your help,
Emily

**Comment by marcus1487** [comment]
Megalodon requires the raw nanopore signal input in order to produce variant calls. Thus FAST5 is the only currently acceptable input to megalodon and addition of called/mapped read input is not within the scope of megalodon's functionality.
