### ISSUE TITLE
Performing ONLY modified basecalling (terminating before aggregation)

### ISSUE THREAD

**Issue by mvolar** [nanoporetech/megalodon#223]
Hello,

I am currently running megalodon 2.3.3 on a SGE cluster with dedicated different GPU and CPU nodes. Because of this (and the polaritiy in the CPU/GPU needs of the Megalodon program depending on the run state)  I was wondering is there any way to terminate a Megalodon run automatically after the .bam files are finished so I can transfer the aggregation step  from a GPU node (which has very poor CPU performance and low disk space) onto a more general-purpose CPU node in order not to clog up the cluster, and not having to monitor the cluster constantly in order for manual cancellation?

**Comment by marcus1487** [comment]
The `--outputs per_read_mods` will output only the per-read mods database. Aggregation can then be performed at a later time. Note also that the `--outputs mod_basecalls` (basecall anchored mods; need to be mapped for aggregation) and `--outputs mod_mappings` (reference anchored) can now be aggregated using the modbam2bed packages (this will be the recommendation for aggregation going forward).

Additionally, the `--skip-database-index` argument will skip the per-read mods database indexing step. If aggregating from the modbam outputs then this database indexing step will not be necessary. Alternatively the `megalodon_extras modified_bases index_database` command can be run on CPU resources after the main megalodon run is complete.

**Comment by colindaven** [comment]
Just a note for others: I believe the modbam2bed packages referred to here is available at 
https://github.com/epi2me-labs/modbam2bed

**Comment by marcus1487** [comment]
Yes. This is correct. Note also that the pysam package should now support access to the modbam tag. The megalodon format was a bit of a stopgap until a community solution was arrived at.
