### ISSUE TITLE
Guppy server initialization failed.

### ISSUE THREAD

**Issue by twslocum** [nanoporetech/megalodon#229]
Hello,

I have encountered the following issue when running the following megalodon command. 
Here is the command:

> megalodon ecoli_ci_test_fast5/ --guppy-params "-d ./rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --outputs basecalls mappings mod_mappings mods --reference /projects/li-lab/Nanopore_compare/nf_input/reference_genome/ecoli/Ecoli_k12_mg1655.fasta --mod-motif m CG 0 --devices 0 --processes 20 --guppy-server-path  /projects/li-lab/software/ont-guppy-gpu_5.0.16/bin/guppy_basecall_server --overwrite

And here is the error message:

> [19:20:32] Running Megalodon version 2.4.1
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[19:20:32] Loading guppy basecalling backend
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************

I have checked the log.txt file and ensured that PyGuppy and Guppy versions are matching (both 5.0.16). I ran the guppy server initialization command which resulted in the following error: 

> /projects/li-lab/software/ont-guppy-gpu_5.0.16/bin/guppy_basecall_server -p auto -l megalodon_results/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --quiet --post_out -x cuda:0 -d /projects/li-lab/software/rerio/basecall_models/
Config file: /projects/li-lab/software/rerio/basecall_models/res_dna_r941_min_modbases_5mC_CpG_v001.cfg does not exist!

However, rerio is installed, and the similar config, res_dna_r941_min_modbases_5mC_v001.cfg, exists, and a res_dna_r941_min_modbases_5mC_CpG_v001 file exists. How do I go about getting the res_dna_r941_min_modbases_5mC_CpG_v001.cfg file? Could this be the source of the issue?

I also checked the guppy_log directory, but it was empty. 

Thank you for any help!

**Comment by jolbi** [comment]
Hi, I am also struggling with making guppy server to work with rerio models. As you said, the file is actually missing. In my rerio/basecall_models/ dir this file exists. Maybe try to redownload all the rerio models, as described here: https://github.com/nanoporetech/rerio#installation
Cheers

**Comment by twslocum** [comment]
Hi @jolbi,

Thank you for this advice! I now have the proper model and .cfg file downloaded, so this is no longer an issue. While the "does not exist" error is no longer occurring, I am still having an issue with initializing the Guppy server. When running the Guppy init command, it appears to become unresponsive. Here is the init command I am running from the log.txt file:
>/projects/li-lab/software/ont-guppy-gpu_5.0.16/bin/guppy_basecall_server -p auto -l megalon_results/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --quiet --post_out -x cuda:0 -d /projects/li-lab/yang/academic_fellows/thatcher/software/rerio/basecall_models/
Is this command supposed to take a long time to run? Is there anything wrong with the above command?

**Comment by jolbi** [comment]
Hi @twslocum, command looks ok and should work. What does your guppy log in megalon_results/guppy_log says?
If the server started you log should have something like:

2022-01-0510:59:15.075917 [guppy/message] ONT Guppy basecall server software version 6.0.0+ab79250, client-server API version 10.0.0
log path:            output/megalodon_5mC_CpG/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  4
2022-01-05 10:59:15.076110 [guppy/info] crashpad_handler not supported on this platform.
2022-01-05 10:59:15.077017 [guppy/info] Listening on port ipc:///tmp/1128-612c-f6bf-625e.
2022-01-05 10:59:15.078232 [guppy/info] lamp_arrangements arrangement folder not found: /DKHA/swalt/guppy-6.0.0/data/read_splitting/lamp_arrangements
2022-01-05 10:59:15.244063 [guppy/info] CUDA device 0 (compute 7.5) initialised, memory limit 8370061312B (8268480512B free)
2022-01-05 10:59:16.036436 [guppy/message] 
Config loaded:
config file:               /DKHA/swalt/guppy-6.0.0/data/dna_r9.4.1_450bps_modbases_5mc_hac.cfg
model file:                /DKHA/swalt/guppy-6.0.0/data/template_r9.4.1_450bps_modbases_5mc_hac.jsn
model version id           None
adapter scaler model file: /DKHA/swalt/guppy-6.0.0/data/adapter_scaling_dna_r9.4.1_min.jsn
**2022-01-05 10:59:16.040198 [guppy/message] Starting server on port: ipc:///tmp/1128-612c-f6bf-625e**
Last line tells you the server is active.
You can also check your if your GPU is running any processes with:
`nvidia-smi` command

**Comment by marcus1487** [comment]
The issue here is likely that the quoted guppy server path does not get expanded. Specifying the full path to the guppy basecall server should resolve this issue.

**Comment by twslocum** [comment]
Hi @marcus1487,

It appears that the path specified in --guppy-params "-d ./rerio/basecall_models/" was the issue. Before downloading the proper .cfg file, I moved rerio to a new location and forgot to update the above path for subsequent runs, fixing one problem but creating another. After updating the path to the correct location, everything is running smoothly. 

Thank you @jolbi and @marcus1487 for the help!

**Comment by netwon123** [comment]
> Hi @twslocum, command looks ok and should work. What does your guppy log in megalon_results/guppy_log says? If the server started you log should have something like:
> 
> > 2022-01-0510:59:15.075917 [guppy/message] ONT Guppy basecall server software version 6.0.0+ab79250, client-server API version 10.0.0
> > log path:            output/megalodon_5mC_CpG/guppy_log
> > chunk size:          2000
> > chunks per runner:   512
> > max queued reads:    2000
> > num basecallers:     4
> > num socket threads:  2
> > max returned events: 50000
> > gpu device:          cuda:0
> > kernel path:
> > runners per device:  4
> > 2022-01-05 10:59:15.076110 [guppy/info] crashpad_handler not supported on this platform.
> > 2022-01-05 10:59:15.077017 [guppy/info] Listening on port ipc:///tmp/1128-612c-f6bf-625e.
> > 2022-01-05 10:59:15.078232 [guppy/info] lamp_arrangements arrangement folder not found: /DKHA/swalt/guppy-6.0.0/data/read_splitting/lamp_arrangements
> > 2022-01-05 10:59:15.244063 [guppy/info] CUDA device 0 (compute 7.5) initialised, memory limit 8370061312B (8268480512B free)
> > 2022-01-05 10:59:16.036436 [guppy/message]
> > Config loaded:
> > config file:               /DKHA/swalt/guppy-6.0.0/data/dna_r9.4.1_450bps_modbases_5mc_hac.cfg
> > model file:                /DKHA/swalt/guppy-6.0.0/data/template_r9.4.1_450bps_modbases_5mc_hac.jsn
> > model version id           None
> > adapter scaler model file: /DKHA/swalt/guppy-6.0.0/data/adapter_scaling_dna_r9.4.1_min.jsn
> > **2022-01-05 10:59:16.040198 [guppy/message] Starting server on port: ipc:///tmp/1128-612c-f6bf-625e**
> 
> Last line tells you the server is active.
> 
> You can also check if your GPU is running any processes with `nvidia-smi` command

I have a problem. According your report, my guppy-server is still runing, could you tell me why. Thanks！
