### ISSUE TITLE
Experimental RNA branch install procedure fails/instructions lacking

### ISSUE THREAD

**Issue by patbohn** [nanoporetech/megalodon#23]
As mentioned at the bottom of the readme, direct RNA "support can be accessed within the rna github branch (access via git clone --branch rna https://github.com/nanoporetech/megalodon")." However, there aren't install instructions for how to install the RNA branch, and running setup.py fails as described below. 

After cloning the branch, the install into a conda env with python 3.6 on Ubuntu 18.04.3 with 

`python setup.py build`

fails with:

`gcc -pthread -B /home/user/miniconda3/envs/megalodon_p36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/.local/lib/python3.6/site-packages/numpy/core/include -I/home/user/miniconda3/envs/megalodon_p36/include/python3.6m -c megalodon/_decode.c -o build/temp.linux-x86_64-3.6/megalodon/_decode.o -std=c99`

The conda package of megalodon were already installed with
`conda install -c megalodon`
 as were build pre-requisites with
`sudo apt install build-essential python3-dev libevent-dev`

**Comment by marcus1487** [comment]
I would recommend not installing megalodon from conda for installation of the RNA branch (just to avoid confusion about which installation is being accessed). I would recommend installation via 
```pip install numpy cython
pip install megalodon/```
from the directory where the repository was cloned into and from you desired environment. Hopefully this will resolve the installation issues.

For the `python setupy.py` install error, what is the actual error. Generally, megalodon should not require the `build` step using `setup.py`. I would recommend installing via `python setup.py install` if this installation method is desired.

**Comment by marcus1487** [comment]
Were you able to install the `RNA` branch successfully?

**Comment by patbohn** [comment]
Thank you, this indeed worked flawlessly in a new environment with python 3.6!
