### ISSUE TITLE
Could I use config file for MinION/GridION to deal with fast5 produced by PromethION? 

### ISSUE THREAD

**Issue by mantonglaw** [nanoporetech/megalodon#230]
Hi,I wonder whether I could use res_dna_r941_min_modbases_5mC_v001.cfg to call methylation for data produced by PromethION?
Or do you have some suggestions for me to call 6mA methylation for PromethION data?

**Comment by marcus1487** [comment]
This model should work reasonably well for promethion data, but I would strongly recommend moving to the remora models (integrated into megalodon) for 5mC in CG context moving forward. We are working to add additional features for mod detection including all-context 5mC and additional modified bases including 6mA.
