### ISSUE TITLE
guppy_server_initialization

### ISSUE THREAD

**Issue by 0Bernhard** [nanoporetech/megalodon#232]
Hello 
I am relatively new to the world of bioinformatics. I am trying to reanalize a dataset. 
megalodon \
>     ./barcode01/ \
>     --guppy-params "-d ./rerio/basecall_models/" \
>     --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg \
>     --outputs basecalls mappings mod_mappings mods \
>     --reference J1074.fasta --mod-motif m CG 0 \
>     --guppy-server-path /usr/bin/guppy_basecall_server \
>      --output-directory ./megalodon \
>     --devices 0  --processes 40 --overwrite
08:24:53] Running Megalodon version 2.4.1
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[08:24:53] Loading guppy basecalling backend
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************

when i run the guppy_barcoder command it initialized fine. The guppy_log folder in the output-directory is empty. Could somebody please help me with pinpointing the source of my problem. I am sorry if this is a trivial question. 

I would be grateful for any help.

**Comment by mantonglaw** [comment]
Hi @0Bernhard !
You can check the "log.txt" in your output-dirctory. You should try to run the command of "guppy server init command" independently. Maybe it could help you pinpoint the source of this issue.
Wish it helps, Thanks

**Comment by 0Bernhard** [comment]
Hello 

Thank you for your help. The command 
/usr/bin/guppy_basecall_server
: Guppy Basecall Service Software, (C) Oxford Nanopore Technologies, Limited. Version 6.0.1+652ffd179, client-server API version 10.0.0

gives the perfect output so it finds the path and initializes it fine. The log.txt file gies the same output as above 
08:35:08] Running Megalodon version 2.4.1
DBG 08:35:08 : Command: """/home/holly/miniconda3/bin/megalodon ./barcode01/*.fast5 --guppy-params -d ./rerio/basecall_models/ --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --outputs basecalls mappings mod_mappings mods --reference J1074.fasta --mod-motif m CG 0 --guppy
-server-path /usr/bin/guppy_basecall_server --output-directory ./megalodon --devices 0 --processes 40 --overwrite""" --- MainProcess-MainThread megalodon.py:1793
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[08:35:08] Loading guppy basecalling backend
DBG 08:35:08 : Guppy version: "6.0.1" --- MainProcess-MainThread backends.py:939
DBG 08:35:08 : Pyguppy version: "6.0.1" --- MainProcess-MainThread backends.py:940
DBG 08:35:08 : guppy server init command: "/usr/bin/guppy_basecall_server -p auto -l ./megalodon/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --quiet --post_out -x cuda:0 -d ./rerio/basecall_models/" --- MainProcess-MainThread backends.py:1017
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************


the guppy log folder is empty. 
Thank you very much,
Bernhard

**Comment by mantonglaw** [comment]
@0Bernhard 
You can try to run the following command:
"/usr/bin/guppy_basecall_server -p auto -l ./megalodon/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --quiet --post_out -x cuda:0 -d ./rerio/basecall_models"
and see what Error happens

**Comment by 0Bernhard** [comment]
Hello 

It gives 
/usr/bin/guppy_basecall_server -p auto -l ./megalodon/guppy_log -c ./res_dna_r941_min_modbases_5mC_CpG_v001 --quiet --post_out -x cuda:0
Error parsing config file: 'the options configuration file contains an invalid line 'https://nanoporetech.box.com/shared/static/w3evfipd4211orr1u6ew2r4dvcn774tl.tgz''.

Would you recommend installing both programms differently?

**Comment by mantonglaw** [comment]
@0Bernhard 
You should cheek whether "./rerio/basecall_models/res_dna_r941_min_modbases_5mC_CpG_v001.cfg" exits or not. If it doesn't exit, you can use following command to download the config file and try to run megalodon again:
"git clone https://github.com/nanoporetech/rerio
rerio/download_model.py rerio/basecall_models/res_dna_r941_min_modbases_5mC_CpG_v001"
