### ISSUE TITLE
Question on mappings.bed output formats

### ISSUE THREAD

**Issue by wentski** [nanoporetech/megalodon#233]
Hello,
I have a query on the data produced in the modified_bases.6mA.bed files. I am viewing these files as tab delimited so I can see what fraction are modified at individual locations. Would someone be able to tell me what each of the columns in these files represent?

I am trying to get an average value for the percentage of motif sites in the whole genome that are modified. I was working under the impression that columns 10 and 11 were coverage and fraction of reads modified for each site, respectively. I have now realised that column ten corresponds to "score" which is visible in IGV (I have no idea what this relates to), so I am looking to clarify so that I know for certain what I am working with.

![Screenshot from 2022-01-12 14-03-14](https://user-images.githubusercontent.com/78024165/149155374-2737134d-885d-44f4-b145-846b32650013.png)

Many thanks,
Sam

**Comment by marcus1487** [comment]
This is the standard bedmethyl file format (see [docs here](https://nanoporetech.github.io/megalodon/file_formats.html#aggregated-modified-bases)). The score field is field 5 and is not strictly defined in the bedmehtyl format. In megalodon the score copies the value from the 10th field which is the coverage which contributed to the percent methylated in field 11.

**Comment by wentski** [comment]
Hi Marcus, thanks for the clarification, it was the repeated score field that was throwing me off. I am curious how/why the valid sites for the coverage is calculated or decided. I read elsewhere that megalodon only uses reads for which a site has >75% certainty or being modified or not modified (is this still correct?). This results in the dataset I am currently processing showing areas of zero coverage, despite having read coverage of around 100X at some of these sites. This seems like an awful lot of data to just discard but I suppose ensures a higher degree of confidence.

For some context, I am trying to establish MinIon/megalodon as an alternative method to sending our samples for Pac Bio sequencing and I am trying to get an understanding of how the two methods work and how they differ in processing the data. We are awaiting results for a full comparison but from our initial observations, Pac Bio seems to predict higher levels of methylation.

**Comment by marcus1487** [comment]
I believe the current threshold is 80% confidence, but you can always check this by reading the command line help documentation. The current 6mA modified base model released in Rerio is considered a research model and may produce results such as this "out-of-the-box". I would recommend setting this confidence threshold parameter to a lower value (say 60%).

I would also say that we are working hard to improve the modified base detection algorithms via the Remora framework. This has been shown to greatly increase the accuracy of 5mC in CG-contexts, and we are working to extend this to all-contexts in 5mC as well as other modified bases including 6mA.
