### ISSUE TITLE
[guppy/error] File name too long. Error initialising basecall server using port:

### ISSUE THREAD

**Issue by uros-sipetic** [nanoporetech/megalodon#235]
Hi, I installed Megalodon in a docker image (by following the instructions for both Megalodon and Guppy installations), and when I spin up a container on my local machine (just for testing, with CPU mode only), I am able to successfully start it. 
However, when I try this on an AWS instance, I get the following error
`[guppy/error] File name too long. Error initialising basecall server using port: ipc://auto. Aborting.`

My command line is:
`megalodon /path/to/fast5_folder --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server --guppy-config dna_r9.4.1_450bps_hac_prom_fw205.cfg`

The content of the `log.txt` file is 
```
[19:48:33] Running Megalodon version 2.4.1
DBG 19:48:33 : Command: """/usr/local/bin/megalodon fast5_folder --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server --guppy-config dna_r9.4.1_450bps_hac_prom_fw205.cfg""" --- MainProcess-MainThread megalodon.py:1793
[19:48:33] Loading guppy basecalling backend
DBG 19:48:33 : Guppy version: "6.0.1" --- MainProcess-MainThread backends.py:939
DBG 19:48:33 : Pyguppy version: "6.0.1" --- MainProcess-MainThread backends.py:940
DBG 19:48:33 : guppy server init command: "/opt/ont/guppy/bin/guppy_basecall_server -p auto -l megalodon_results/guppy_log -c dna_r9.4.1_450bps_hac_prom_fw205.cfg --quiet" --- MainProcess-MainThread backends.py:1017
DBG 19:48:33 : Found guppy log file: megalodon_results/guppy_log/guppy_basecall_server_log-2022-01-19_19-48-33.log --- MainProcess-MainThread backends.py:1033
****************************************************************************************************
	ERROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.
		Try running the guppy server initialization command found in log.txt in order to pinpoint the source of this issue.
****************************************************************************************************

```

and the content of the `guppy_basecall_server_log-*.log` file is:
```
2022-01-19 19:48:33.207497 [guppy/message] ONT Guppy basecall server software version 6.0.1+652ffd179, client-server API version 10.0.0
log path:            megalodon_results/guppy_log
chunk size:          2000
chunks per runner:   1664
max queued reads:    2000
num basecallers:     1
num socket threads:  2
max returned events: 50000
cpu mode:             ON
threads per caller:  4
2022-01-19 19:48:33.207601 [guppy/info] crashpad_handler successfully launched.
2022-01-19 19:48:33.208762 [guppy/error] File name too long. Error initialising basecall server using port: ipc://auto. Aborting.
2022-01-19 19:48:33.208809 [guppy/message] The basecall server has shut down successfully.

```

Am I missing some step on configuration here or...? It puzzles me because with the same docker image locally I have no issues..

**Comment by marcus1487** [comment]
Would you mind posting the result of the guppy server command run outside of megalodon? From the log file it should be `/opt/ont/guppy/bin/guppy_basecall_server -p auto -l megalodon_results/guppy_log -c dna_r9.4.1_450bps_hac_prom_fw205.cfg --quiet`

**Comment by uros-sipetic** [comment]
Hey yes of course, I can run that command, but the log file looks similar as to the one from before
```
2022-01-20 23:20:30.651505 [guppy/message] ONT Guppy basecall server software version 6.0.1+652ffd179, client-server API version 10.0.0
log path:            guppy_log
chunk size:          2000
chunks per runner:   1664
max queued reads:    2000
num basecallers:     1
num socket threads:  2
max returned events: 50000
cpu mode:             ON
threads per caller:  4
2022-01-20 23:20:30.651662 [guppy/info] crashpad_handler successfully launched.
2022-01-20 23:20:30.652824 [guppy/error] File name too long. Error initialising basecall server using port: ipc://auto. Aborting.
2022-01-20 23:20:30.652879 [guppy/message] The basecall server has shut down successfully.
```
I'm not sure what this `File name too long.` means. Which file is it referring to?

**Comment by uros-sipetic** [comment]
Hey I was able to get this to work. Here's a quick rundown in case anyone else encounters a similar issue.
Basically, my guess is that the instance where I was trying to start the `guppy_basecall_server` perhaps did not allow for opening certain ports. 

When starting the `guppy_basecall_server` locally with `-p auto`, I get the message back:
`2022-01-19 20:09:13.447295 [guppy/info] Listening on port ipc:///tmp/ce54-984a-4cff-78fb.`
If I try any other value (like `-p 8080`), it still works:
`2022-01-19 20:09:13.447295 [guppy/info] Listening on port ipc:///my_folder/8080.`
where`my_folder` is the one that I mounted to the docker container. 

However, running this from the instance returns:
`[guppy/error] File name too long. Error initialising basecall server using port: ipc://auto. Aborting.`
or if `-p 8080`:
`[guppy/error] File name too long. Error initialising basecall server using port: ipc://8080. Aborting.`

So I tried to give it `-p /tmp/ce54-984a-4cff-78fb` (which is the value that I got when leaving `-p auto` locally), and now it worked fine, it was able to listen. 

Then finally, when I ran `megalodon` with `--guppy-server-port /tmp/ce54-984a-4cff-78fb`, the issue was that this command line argument expects an integer, as from line 64 in `__main__.py` you can see:
```
pyg_grp.add_argument(
        "--guppy-server-port",
        type=int,
        help=hidden_help("Guppy server port. Default: Guppy auto"),
    )
```

So I just deleted the `type=int,` line in my instalation, and continued on. 

I'm not able to really explain why certain options here worked and why others didn't, so if anyone with the proper background and knowledge can explain, I'll gladly listen :) But other than that, you can consider this issue done. I'll close it in a day or two, just to see if anyone has anything else to add.
