### ISSUE TITLE
generate sequencing_summary.txt file?

### ISSUE THREAD

**Issue by zhanxw** [nanoporetech/megalodon#24]
Just want to know if megalodon plans to produce sequencing_summary.txt.
This file is used for quality control of nanopore reads by many software tools.
But it does not seems to be generated by megalodon 2.0.

**Comment by marcus1487** [comment]
Some version of this could be added, but is not a high priority at the moment. Looking into this briefly there are a number of components that would contribute to these output values. Are there specific fields that are most useful from this file that could be added as a starting point?

**Comment by zhanxw** [comment]
Currently many QC software requires that file to produce plots. So it would be nice to have it. 
Or is there another way to check qc statistics? Eg. yield vs time, yield per cell.

**Comment by marcus1487** [comment]
The start time is currently not output in any of the megalodon output files. This field should not be too hard to include in a sequencing summary output. I will have a look to see if there are any fields which are particularly difficult to obtain within the megalodon framework.

**Comment by marcus1487** [comment]
Fixed in release 2.1.
