### ISSUE TITLE
Unlimited CPU use with remora

### ISSUE THREAD

**Issue by kpalin** [nanoporetech/megalodon#242]
Not sure this should be posted with remora but I noticed with megalodon that the remora analysis tries to use unlimited CPU resources.  Just one megalodon worker process easily uses >4000% CPU. It is so bad that I can run sup models faster than hac since it doesn't saturate that badly.

Tried to limit torch cpu use in the source code but failed.  Some option or guidance would be nice.

K

**Comment by marcus1487** [comment]
This is likely related to the Remora models backend (ONNXruntime). A new Remora release (0.1.2) has pushed a fix for related issues and may resolve this issue as well. Please re-open this issue if this issue persists after updating Remora.
