### ISSUE TITLE
Why do some reference CGs not have Mm/Ml entries in mod_mappings.bam?

### ISSUE THREAD

**Issue by benbfly** [nanoporetech/megalodon#249]
Hi,

I see lots of reference CGs covered by a read but without an entry in the Mm/Ml field.  See attached screenshot, where a read covers 4 CGs, but only the final 3 have entries in the Mm/Ml field.  I circled the "missing" CG.

I assume this is because of some kind of poor quality, but I can't really tell.  The base quality seems ok (Q22,23).  I thought maybe it was it was near the beginning of the read and doesn't have enough "context" (there is a context parameter set to 15). Maybe some other filter?

My main issue is how I should interpret these in terms of methylation.  _Do I assume that this is "missing data" from the methylation perspective?_  _Or should I interpret this as an unmethylated CG?_   I would interpret the htslib spec to be that these are missing data.  But I wanted to check with the Megaldon team because there are quite a lot of these in my reads and I'd like to interpret them correctly.

![image](https://user-images.githubusercontent.com/1547787/153454310-08893aa9-717d-4dda-a4f4-12b4765ab511.png)

Thanks!
Ben.

**Comment by benbfly** [comment]
Just to follow up on how modbam2bed deals with this.  It treats it as a canonical (unmethylated) call.

In the --help description, modbam2bed says: "Positions absent from the methylation tags are assumed to be canonical."

![image](https://user-images.githubusercontent.com/1547787/153454428-723978a7-dcdd-4888-9003-7db151ad99cd.png)

@cjw85

**Comment by cjw85** [comment]
Marcus is correct. @jts and I discussed how the initial proposal for the Mm/Ml tags tacitly implies that missing data should be treated as canonical, though this wasn't explicitely referenced in the documentation. Jared proposed an extension to the spec, which if I recall correctly has been accepted, to allow a caller to record the implication of absent data:

Section 2.1 of [SAMtags](https://samtools.github.io/hts-specs/SAMtags.pdf):

> Following the base modification codes is an optional ‘.’ or ‘?’ describing how skipped seq bases of the stated base
> type should be interpreted by downstream tools. When this flag is ‘?’ there is no information about
> the modification status of the skipped bases provided. When this flag is not present, or it is ‘.’, these
> bases should be assumed to have low probability of modification.

**Comment by benbfly** [comment]
@marcus1487 But this one are missing from `modified_based.5mC.bed`. See below, it includes CpGs 2,3, and 4 (which have Mm tags), but not CpG 1 (which is at position chr1:596372). I haven't checked more than this one, but I think there are a lot like this since I see a large number covered by modbam2bed and not `modified_based.5mC.bed`.

I uploaded the BAM file in #247 , it's the same dataset for this example.  Let me know if there's something else I can send you to reproduce. I can send you the megalodon log file or even the fast5s - whatever you need.

![image](https://user-images.githubusercontent.com/1547787/153473544-c3614854-a2f2-4bf8-9520-ba8f80dbd66a.png)

**Comment by marcus1487** [comment]
Right. That is what my last comment mentioned. Any base within 30 bases of the edge of a read will be skipped by megalodon (change this via the `--edge-buffer` option). But the mod_mappings.bam still covers this position and thus is output by modbam2bed. So in your example here CG 1 is near the edge of the read and thus skipped in megalodon processing.

**Comment by benbfly** [comment]
Sorry, in the flurry of activity I missed that comment.  I suspected something like that initially because the missing one was close to the beginning of the read. 

I believe this probably accounts for most of the missing CGs in my data. Since this is plasma cfDNA, the reads have a mean length somewhere around 175bp, so missing 30bp per read would be almost 20% of the data.  I assume this only applied to the start of the read and not the end, or does it apply to both?  How dangerous would it be for me to relax this (this is all R9.4/LSK109).

Thanks!
Ben.

**Comment by benbfly** [comment]
As a datapoint, i set `--edge-buffer 5 --mod-min-prob 0` and got an increase from 103,768 CpGs covered to 139,118 (an increase of 34%).  We have low coverage and need all the CpGs we can get, so as long as they are even so so quality, they will help.  I am also thinking about using the probability scores to weight them rather than a hard threshold .

Again , this is pretty non-typical since we are doing short fragments. It might be a good idea to add a "settings for short fragments" section to the documentation.

**Comment by marcus1487** [comment]
For reference anchored outputs it is from the edge of the mapping for basecall anchored mods it is from the edge of the read (since there is no mapping). The calls near the edge of reads are not particularly poor, so I would recommend you can probably set this to 0 for your purposes. Yes this section may be helpful to others. We will attempt to include this in the next release.

**Comment by benbfly** [comment]
Great.

I think the main "issue" that remains is that how will downstream applications like modbam2bed know how to inrerpret CGs without an Mm/Ml tag?  For ones due to `--mod-min-prob`, these should be interpreted as unmodified ('.').  But when it is because of `--edge-buffer`, it should be interpreted as missing ('?').  How to solve this?

**Comment by marcus1487** [comment]
For the issues with the missing data, this is an issue with the file format and there is likely nothing that megalodon can do without an updated file format from hts-spec. This is part of the reason for maintaining the aggregation from the binary megalodon format as opposed to moving completely to dependence on tools like modbam2bed. 

For the default parameter values, the options are available for users to change as they wish. We can look into updating these default parameters to remove filters which may lead users down this line of analysis in the next release.
