### ISSUE TITLE
megalodon --list-supported-guppy-configs doesn't return config list

### ISSUE THREAD

**Issue by kkowalden** [nanoporetech/megalodon#25]
Hello,

We have DNA R10.1 GridION microbial data for which we would like to use Megalodon to call 6mA and 5mC modified bases.  However, it appears that the default guppy config file is dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg. 

I am trying to check the other available config files using "megalodon --list-supported-guppy-configs".  This command doesn't return a config file list for me; instead it returns the default argument list followed by "megalodon: error: the following arguments are required: fast5s_dir".

Any thoughts on if this is a bug, or if there is an installation problem?

Thanks,
Kim

**Comment by marcus1487** [comment]
The `--list-supported-guppy-configs` behavior is bug. A fix for this will be pushed to the github repo shortly, and included in the next release.

For your query though, unfortunately there is not a guppy modified base model or megalodon modified base config currently available for R10.1 MinION/GridION platform. We could look into adding this model. What is your use case? If your use case is confidential could you reach out via email (support@nanoporetech.com and reference this issue).

**Comment by kkowalden** [comment]
Thanks for the info on the bug.

We are a service core providing methylation analyses for a client.  Our sequencing core switched to the 10.1 flowcells early in 2020.  Prior to that, we had provided methylation analyses using both tombo and Megalodon from R9.4.1 flowcells.
From the documentation, it does not look like tombo is compatible with R10.1 flowcells, either.  Are there any methods to convert 9.4.1 modified base models to a version compatible with R10.1?  Taiyaki?

Thanks!

**Comment by marcus1487** [comment]
Neither tombo or Megalodon currently have r10 modified base models. Unfortunately it is a bit more complicated than converting the models. The signal is quite different from R9 to R10, so models must likely be trained from new data for this purpose. Taiyaki would be the correct tool to train a new Megalodon/Guppy modified base model, but this requires accurately marked up ground truth per-read references (see more in the [taiyaki docs here](https://github.com/nanoporetech/taiyaki#modified-bases)).

**Comment by kkowalden** [comment]
Ok, thanks.  I will check with Oxford Nanopore directly to see if they have any plans to provide R10 modified base models for guppy any time soon.

**Comment by marcus1487** [comment]
I've pushed a fix for this issue (c204f53) and this will be included in the next release.
