### ISSUE TITLE
python3.9 update README

### ISSUE THREAD

**Issue by pur80a** [nanoporetech/megalodon#253]
Hi,
since guppy 6.0.1 there seems to be a ont_pyguppy_client_lib-6.0.1-cp39-cp39-manylinux2014_x86_64.whl (see bottom of [this page](https://pypi.org/project/ont-pyguppy-client-lib/)) which is for python3.9. I could successfully install megalodon in a python3.9 environment. The README file could therefore be updated:
> ont-pyguppy-client-api does not currently provide a python 3.10 release, so python < 3.10 is required for use with the guppy backend.

**Comment by marcus1487** [comment]
Updated in 2.5.0 release.
