### ISSUE TITLE
Bam with IGV has different results from modified_bases.5mc.bed

### ISSUE THREAD

**Issue by muguading** [nanoporetech/megalodon#256]
I used IGV to confirm the proportion of CpG sites mentioned in the BED file，I find that the number of sequences that support methylation sites on igV is always higher than in bed file。So is this a bug or is there something wrong with my IGV Settings?
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/34020478/154929364-0976cc46-af66-4f29-b366-e08599bc929b.png">
<img width="195" alt="image" src="https://user-images.githubusercontent.com/34020478/154929443-0531c26a-7ad8-43fc-b9cf-37cf7bdf15b4.png">

**Comment by marcus1487** [comment]
The fraction of reads reported in the bedmethyl file is after a hard thresholding (`--mod-binary-threshold` parameter in ` megalodon --help-long and docs [here](https://nanoporetech.github.io/megalodon/advanced_arguments.html#modified-base-arguments)). As part of this thresholding ambiguous calls are filtered/ignored (usually ~10% of total calls). This results in a more accurate estimate of the fraction of reads modified.
