### ISSUE TITLE
Output and method to quantify percent methylation 

### ISSUE THREAD

**Issue by simpsonbp** [nanoporetech/megalodon#258]
I successfully ran megalodon on Nanopore data and was able to visualize the 5mC mod_mapping .bam with IGV bisulfite-seq mode. 

Is there a megalodon output with the methylation percentage across the reference gene? Or another method to quantify the methylation percentage from the megalodon outputs?

**Comment by marcus1487** [comment]
The `modified_bases.bed` file contains this aggregated output. I am not certain how much support genome browsers have for this output type. Megalodon also allows the output in wiggle file format (one file per-strand) which has wider genome browser support. These outputs are triggered by the `--outputs mods` option and can be generated using the `megalodon_extras aggregate run` command from a previous megalodon run without need to re-run basecalling/mapping.

**Comment by simpsonbp** [comment]
Thank you!
