### ISSUE TITLE
thresholding the scores from per-read-mods

### ISSUE THREAD

**Issue by rrazaghi** [nanoporetech/megalodon#26]
Hi Marcus,
Do you have a recommendation for a threshold to call modified/unmodified from the output log probability per position per read?

Thanks,
Roham

**Comment by marcus1487** [comment]
The default value in the aggregation step as well as independently in the aggregation script (`scripts/run_aggregation`) is `0.75`. This should work well with the released models (with megalodon calibration files), but note that when calling from newly trained models this threshold may not perform as well. Hoping to add documentation to this effect soon.

**Comment by rrazaghi** [comment]
Thanks Marcus, this makes sense. Would you also define an ambiguous interval as well? 
For example, everything above 0.75 is modified, below 0.25 unmodified, and everything in between ambiguous?

**Comment by marcus1487** [comment]
Yes. Meant to elaborate on that in the last response. Megalodon is built with an eye towards multiple alternatives to any canonical base. So for a call to be made the highest probability base (canonical or modified) must be above 0.75 probability. This doesn’t leave room for unbalanced thresholds, but the goal of the calibration step after model training is intended to balance this (docs forthcoming on this process).
