### ISSUE TITLE
Version matching problem

### ISSUE THREAD

**Issue by ctl43** [nanoporetech/megalodon#262]
Guppy has changed their version output in 6.0.6 from `Oxford Nanopore Technologies, Limited. ` to `Oxford Nanopore Technologies plc. `, so the version matching pattern is not working now.

Otherwise, users will just get an error message, `ERROR: Guppy version string does not match expected pattern: `

**Comment by Kirk3gaard** [comment]
Hopefully an update of megalodon to match the 6.0.6 version of guppy will then will solve #243

**Comment by marcus1487** [comment]
Thank you for raising this issue. We have encountered this and a few other issues with the latest Guppy. A new version of Megalodon will be pushed shortly.

**Comment by marcus1487** [comment]
This should be fixed in the 2.5.0 release. Please reopen if this issue persists.
