### ISSUE TITLE
How to generate bed file from sql database

### ISSUE THREAD

**Issue by m0nib** [nanoporetech/megalodon#264]
Hi,

is it possible to construct or generate bed file or extract modified bases from the sql database, that is created as part of the megalodon pipeline?

We can start the liveprocessing with megalodon but our downstream pipeline analysis requires bed file. 

Could provide instructions on how to achieve this?

thank you
Monib

**Comment by marcus1487** [comment]
The `megalodon_extras aggregate run` command will compute the bed file from the produced sql modified base data base. See docs here: https://nanoporetech.github.io/megalodon/extras_aggregate.html
