### ISSUE TITLE
Version mismatch: Guppy version 6.0.6+8a98bbcbd

### ISSUE THREAD

**Issue by ysuzuki1978** [nanoporetech/megalodon#265]
I am trying to start an analysis of methylation, but it is not working because the version display is mismatched.
Please let me know the solution.

****************************************************************************************************
        ERROR: Guppy version string does not match expected pattern: "b': Guppy Basecall Service Software, (C) Oxford Nanopore Technologies plc. Version 6.0.6+8a98bbcbd, client-server API version 10.1.0\n\n'"
****************************************************************************************************

**Comment by jrhendrix** [comment]
Check out issue #262 
Try updating Megalodon to the newest version

**Comment by ysuzuki1978** [comment]
Thank you for your comment.
The version is 2.4.1 as it is installed with conda.
Should I clone it from github and reinstall it?

I think one of the causes is
pip install ont_pyguppy_client_lib==6.0.6

I think the command "pip install ont_pyguppy_client_lib==6.0.0.6" can specify "6.0.6" but not "6.0.6+8a98bbcbd". What do you think?
