### ISSUE TITLE
Does the bed methyl file contain both the fast5_fail and fast5_pass outputs?

### ISSUE THREAD

**Issue by m0nib** [nanoporetech/megalodon#267]
During live processing does the final bed methyl contain CoGs from only fast5_pass? 

I ran live processing and pointed to the output of minknow folder, followed by nanodx pipeline. Final report shows both fast5_fail and fast5_pass reads. I know megalodon can’t distinguish barcodes but what about the pass or fail fast5? 

This lead me to try pointing to the fast5_pass directory, but since minknow final summary is generated in the base directory (couple of directories up the fast5_pass directory) when minknow stops sequenceing the megalodon never finishes. As it cannot find the final summary file. 

If megalodon cannot distinguish between pass and fail reads then using minknow to do live basecalling and producing fast5 pass files seems like waist of resources. 

So the real question is, is this a normal behaviour of megalodon? If not then what commands or settings can be used to mitigate this behaviour? 

I have not been able to locate a command in either basic usage or advance that can help with this.

**Comment by marcus1487** [comment]
Megalodon will recursively search below the directory for FAST5 files, so when pointed to the minkown root directory this will include pass and fail reads. I understand the live processing requires pointing to this directory. For aggregating from live basecalling with Megalodon I would recommend not outputting aggregated outputs (`--outputs mods`) during the run and then running `megalodon_extras aggregate run` after the run is complete. This command can be supplied a list of read ids (which can contain any set of reads included barcodes or pass/fail) to include in the aggregation output. I think this should allow the outputs you require, but please post if this does not satisfy your run requirements.

**Comment by m0nib** [comment]
Hi @marcus1487 thank you for the suggestion I certainly will give that a try. I just checked the megalodon documentation and it does not document how to pass list of reads or barcode to the aggregate commas. 

Could you kindly provide an example on using this command. 

Also how can I obtain the read ids of fast5_pass files? 

thank you

**Comment by m0nib** [comment]
Ps. If this works then this will be ideal for our live downstream analysis pipeline. As I can direct the aggregation at certain reads and generate required report.

**Comment by marcus1487** [comment]
Running `megalodon_extras aggregate run -h` shows the documentation for the `--read-ids-filename` argument which should suffice for your purposes here. The list IDs can probably be extracted from the sequencing summary file produced by guppy/minknow. Pass/fail reads are generally identified by the average q-score field for the read.
