### ISSUE TITLE
Model for variant calls

### ISSUE THREAD

**Issue by esteinig** [nanoporetech/megalodon#27]
Awesome work on this, quick question: which model is preferable for the variant calling workflow on haploid (bacterial) genomes - methylation-aware or the standard HAC?

**Comment by marcus1487** [comment]
At the moment, only the default mod base model has a calibration file for variant calling. So this would be the model to use for right now. 

I’m hoping to include default megalodon variant calibration files for most models in the next megalodon release (as well as better documentation on calibration).

**Comment by esteinig** [comment]
Thanks Marcus! Appreciate the quick reply, looking forward to more config files :)
