### ISSUE TITLE
About speed and result format for Megalodon 

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/megalodon#272]
Hi, thank you very much for sharing this useful tool.
When I run Megalodon, I find if I provide Megalodon with multiple .fast5 files, the result will put them together to generate one .fastq file (basecalls.fastq). I would like to know if there is any way to generate multiple .fastq files, which correspond to .fast5 files.
By the way, I find Megalodon is very slow, even if I run it on 3 GPUs, is it normal?
Thank you very much!

**Comment by sklages** [comment]
> [...] By the way, I find Megalodon is very slow, even if I run it on 3 GPUs, is it normal? Thank you very much!

Guppy (basecalling) is the only part of `megalodon`which uses GPUs AFAIK, all other parts are run on CPUs. Keep in mind that if you omit `--devices cuda:N` even `guppy`is run on CPUs which extremely slows down the whole process.

Use `--processes N` to control the "Number of CPU read-processing workers to spawn."

**Comment by Flower9618** [comment]
Thank you very much for your reply. Because my .fast5 files already include the basecalling information, which is basecalled by Guppy integrated in MinKNOW, I would like to know if I can skip the basecalling step when running Megalodon. And if yes, which setting can help do it. Thanks.

**Comment by sklages** [comment]
That is currently not yet possible, see #240

**Comment by marcus1487** [comment]
As @sklages notes most Megalodon outputs require the intermediate basecalling data. We are moving towards a new data workflow with Remora modified base models (which are separated from the basecalling model) and the new signal file format POD5 (which will allow random access to signal data) which will allow us to run modified base calling after a basecalling run (as long as the "move table" (link between signal and basecalls) was saved at basecalling time. This is not currently implemented though it is high on our priority list.
