### ISSUE TITLE
Guppy version string does not match expected pattern:

### ISSUE THREAD

**Issue by Fatihlrcfs** [nanoporetech/megalodon#281]
Hi Dear,

I am working on Megalodon analysis and all my packages are updated but ı am getting this error below.  thanks 
Megalodon v=2.4.1
guppy version= 6.1.2
ont-pyguppy-client-lib 6.1.3

ERROR: Guppy version string does not match expected pattern: "b': Guppy Basecall Service Software, (C) Oxford Nanopore Technologies plc. Version 6.1.2+e0556ff, client-server API version 11.0.0\n\nUse of this software is permitted solely under the terms of the end user license agreement (EULA).By running, copying or accessing this software, you are demonstrating your acceptance of the EULA.\nThe EULA may be found in /cluster/lrcfs/2397405/bin/ont-guppy_gpu-6.1.2/bin\n'"

**Comment by marcus1487** [comment]
This is fixed in the latest megalodon version. Please upgrade to 2.5.0.

**Comment by Arkadiy-Garber** [comment]
The latest conda install installs version 2.4.1. Please fix this in that version, or update the conda recipe.
