### ISSUE TITLE
Does megalodon take into account qscore filtering with Guppy?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/megalodon#282]
This isn't clear to me in the documentation -- if I point megalodon to a run folder, does it only take into account the "passing" reads from Guppy via q-score metrics or does it use everything? Right now I am pointing it at the "fast5_pass" folder, but if I want to do something like live processing, or point to an experiment containing many different flow cells, does it use all of the fast5s?

**Comment by marcus1487** [comment]
Megalodon will search recursively from the input directory for all fast5 files. If pointed to the pass directory, only those reads will be processed. If pointed to a directory containing several, runs all runs will be processed. Subsets can be created without copying files by using soft links.

**Comment by billytcl** [comment]
Is it possible to run with live processing on a fast5_pass folder, and then
put in a dummy final_summary file into the folder to trick it into stopping?

**Comment by marcus1487** [comment]
I'm not sure what the use case is here, but if you start a megalodon run in live mode, then this would work. In fact the dummy final summary file could be there at the start of the run for this since megalodon does one more sweep for fast5 files after encountering the final_summary file. Again I'm not sure what the use case is here.

**Comment by billytcl** [comment]
Thanks!

Our use case is that we do offloading of fast5s as soon as they come off
the PromethION using the onboard data-offload script. Because megalodon
takes such a long time to run, having it run live on the fast5_pass folder
would be really useful for saving time (as opposed to running it only when
the run is finished, or pointing it at the whole folder which would include
the failed reads in the analysis).

**Comment by marcus1487** [comment]
Ah. I see. Indeed this sounds like a good use case for the live mode then! So writing a dummy final_summary file in the pass folder after the run has completed should work.
