### ISSUE TITLE
Assertion alphabet error with all context 6mA/5mC rerio model

### ISSUE THREAD

**Issue by HJeffery** [nanoporetech/megalodon#289]
Similar to issue #53. I'm using the all-context 5mC and 6mA rerio model which is resulting in an assertion error suggesting the given mod-motif bases are incorrect.

Command:
```
megalodon
  --devices 0
  --processes 8
  --guppy-server-path /path/to/ont-guppy6.0.1/bin/guppy_basecall_server
  --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg   
  --outputs mod_basecalls
  --mod-motif Z C 0
  --mod-motif Y A 0
  --output-directory /path/to/output_folder
  --overwrite /path/to/fast5s
```

Using:
Python: 3.7.12
Guppy: 6.0.1
Pyguppy: 6.0.1
Megalodon: 2.5.0 (pip install)
Rerio model: res_dna_r941_min_modbases-all-context_v001.cfg

Error:
```
Loaded model calls canonical alphabet ACGT and modified bases Y=6mA (alt to A); Z=5mC (alt to C)
Traceback (most recent call last):
  File "/path/to/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/path/to/python3.7/site-packages/megalodon/__main__.py", line 754, in _main
    megalodon._main(args)
  File "/path/to/python3.7/site-packages/megalodon/megalodon.py", line 1807, in _main
    args, mods_info = parse_mod_args(args, model_info, map_info)
  File "/path/to/python3.7/site-packages/megalodon/megalodon.py", line 1500, in parse_mod_args
    remora_sig_map_offset=sig_map_shift,
  File "/path/to/python3.7/site-packages/megalodon/mods.py", line 2359, in __init__
    self.alphabet, model_info.output_size - self.n_can_state - 1
AssertionError: Alphabet (ACGT) and model number of modified bases (-41) do not agree
```

I checked the alphabet expected for this model:
`megalodon_extras modified_bases describe_alphabet --guppy-server-path /path/to/ont-guppy6.0.1/bin/guppy_basecall_server --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg`

Which gave:
`Loaded model calls canonical alphabet ACGT and modified bases Y=6mA (alt to A); Z=5mC (alt to C)`

This suggests that Y and Z are the correct alphabet to use for this model, could you shed any light on how to fix this?

**Comment by marcus1487** [comment]
This is an issue with how megalodon processes flip-flop modbase models. Adding `per_read_mods` to `--outputs` should resolve this issue. Additionally, this model has now been deprecated. We don't have a current replacement for all-context 6mA, but a research all-context 5mC Remora model has been added to Rerio. We are working hard to get an all-context 6mA model released as well.

**Comment by vivekbhr** [comment]
@marcus1487 could you point me to the all-C context remora model for pore 9.4.1 ? [Models in rerio](https://github.com/nanoporetech/rerio/tree/master/basecall_models) seem to be atleast 13 months old, and models in remora (below) seem to be in CG context only?

```
dna_r9.4.1_e8     fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8     fast                   0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8     hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8     hac                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8     sup                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8     sup                    0.0.0                     5hmc_5mc          CG                                        0
dna_r9.4.1_e8.1   fast                   0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8.1   hac                    0.0.0                     5mc               CG                                        0
dna_r9.4.1_e8.1   sup                    0.0.0                     5mc               CG                                        0
```

**Comment by marcus1487** [comment]
We do not have an all-context Remora model for R9 flowcells. We have a research model for kit14 in Rerio (see Remora model section) and will be following up with more kit14 all-context Remora models, but we are unlikely to produce an R9 all-context Remora model at this time. The process to produce the all-context training dataset is currently quite laborious, so we would like to focus these efforts on the current best quality of data.

**Comment by vivekbhr** [comment]
Makes sense.. Thanks for the reply
