### ISSUE TITLE
GPU Memory limit

### ISSUE THREAD

**Issue by Lucas-Servi** [nanoporetech/megalodon#297]
I've being trying to run megalodon on my asus G14 (Ryzen 7 5800hs + RTX 3050 mobile 4GB). I'm struggling with GPU RAM, always receiving this error (or a variation of it):

**Guppy** 6.1.7
**Megalodon** 2.5.0

**Guppy Log**
`2022-06-13 21:39:17.216041 [guppy/info] client connection request. ["dna_r10.4_e8.1_hac:>timeout_interval=15000>client_name=>barcode_kits=>detect_barcodes=0>move_and_trace_enabled=1>post_out=0"]`
`2022-06-13 21:39:17.216973 [guppy/info] New client connected Client 15 anonymous_client_15 id: 31d5c03f-d3d5-44a6-b99e-6dccc076905c (connection string = 'dna_r10.4_e8.1_hac:>timeout_interval=15000>client_name=>barcode_kits=>detect_barcodes=0>move_and_trace_enabled=1>post_out=0').`
`2022-06-13 21:39:18.761342 [guppy/info] CUDA device 0 reached memory limit while trying to allocate 414853888 bytes, currently at 3317279728/4100456448`

**megalodon log**
`DBG 21:40:19 : 8382f4a8-5e0a-48a7-b5a3-e315da2ca7ab Success --- ReadWorker013-MainThread megalodon.py:505`
`DBG 21:40:19 : 68d4d5b1-f5c0-4e89-b0ad-4c224e31c234 BasecallingCompleted --- ReadWorker013-MainThread backends.py:1256`
`DBG 21:40:19 : 56fa1d4d-28a9-4cea-9b2b-6a91b7d34fda Failed No alignment --- ReadWorker012-MainThread megalodon.py:533`
`DBG 21:40:19 : 00b01cef-933f-42bd-9283-632f463ff79d BasecallingCompleted --- ReadWorker012-MainThread backends.py:1256`
`DBG 21:40:19 : 1561ab8d-4304-47c6-962c-b5832c646090 Processing --- ReadWorker004-MainThread megalodon.py:474`

After this error, computer totally freezes and I need to hard-reset it.

I have set the config file I'm using (dna_r10.4_e8.1_hac.cfg) to: `chunks_per_runner = 64`  to help in memory handling.

Is there anything i can do to run megalodon on my GPU (guppy runs perfectly fine)?

I have followed some of these suggestions([https://hackmd.io/@Miles/S12SKP115](https://hackmd.io/@Miles/S12SKP115)), but this is for guppy (which works perfectly fine).

**Comment by marcus1487** [comment]
GPU memory is handled completely by the guppy server and not by Megalodon, so there is not much from the megalodon side (aside from settings in the guppy config specified) which should help here. Could you raise this issue on the community site in order to enable guppy support.
