### ISSUE TITLE
GPU nodes

### ISSUE THREAD

**Issue by javiersanchezlor** [nanoporetech/megalodon#299]
Hi,

I am trying to run Megalodon with 1 GPU node, but it is not able to identify the GPU node, how can I do it? Also, it is possible to obtain more information about the speed and time it takes to analyse for example 1GB of data? 

Thank you in advance !

**Comment by marcus1487** [comment]
The `--devices 0` value should specify to use the cuda:0 device on your machine. The default is CPU only computation. There are far too many systems and settings within megalodon to provide sufficient computational benchmarks. Please see the production Guppy basecaller benchmarks for this purpose.
