### ISSUE TITLE
Connection error. [basecall_config_unavailable]

### ISSUE THREAD

**Issue by GeoMicroSoares** [nanoporetech/megalodon#301]
Hi there,

Trying to run `megalodon` on my machine atm and getting a connection error. First time user so please let me know if I'm setting this up incorrectly. 

- I'm running `guppy_basecall_server` on a screen as such: `guppy_basecall_server --config /opt/ont/guppy/data/dna_r9.4.1_450bps_sup.cfg -p auto -l /tmp/guppy/ -x 'cuda:0'`

Which returns `Starting server on port: ipc:///tmp/622d-72d7-e516-0eb1`

- In another screen, following advice from [here](https://github.com/nanoporetech/megalodon/issues/235), I've edited the `__main.py__` to make sure I could set the port with `megalodon` and my command is as follows: `megalodon ../fast5_barcodes/barcode02/ --reference ../E_coli_K12_reference/GCF_000005845.2_ASM584v2_genomic.fna --devices 0 --processes 10 --mod-motif U BrdU 0 --guppy-server-path /usr/bin/guppy_basecall_server --overwrite --guppy-config /opt/ont/guppy/data/dna_r9.4.1_450bps_sup.cfg --guppy-server-port /tmp/f935-d4af-acd6-393d`

With this however, I'm getting the following error message:
```
[16:37:39] Running Megalodon version 2.5.0
[16:37:39] Loading guppy basecalling backend
[guppy/error] basecall_service::BasecallClient::worker_loop: Connection error. [basecall_config_unavailable] could not retrieve details for config from server: /opt/ont/guppy/data/dna_r9.4.1_450bps_sup
[guppy/error] basecall_service::BasecallClient::worker_loop: Connection error. [basecall_config_unavailable] could not retrieve details for config from server: /opt/ont/guppy/data/dna_r9.4.1_450bps_sup
...
****************************************************************************************************
        ERROR: Error connecting to Guppy server. Undefined error: "Basecalling config unavailable: <result.basecall_config_unavailable: 6>"
****************************************************************************************************
```

Does this make sense? With this output, I'm clueless as to what to do. I don't see any useful output that can tell me what to change, etc. Anything you see that I could improve on? Thanks in advance for the help and let me know what else I could provide to help you help me...! Cheers.

**Comment by marcus1487** [comment]
Megalodon will startup the guppy server internally and spin up one connection to this server for each `--processes` workers. There is no need to start the guppy server externally (and this is in fact likely causing the observed issue since the specified port is already in use). The request to run the guppy server command in that issue is simply for debugging purposes and not required for a successful megalodon run.
