### ISSUE TITLE
Could not load guppy server configuration state

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/megalodon#303]
Hi There,
I ran megalodon with below command:
```
megalodon \
       FAQ32172/ \
       --outputs basecalls mappings mod_basecalls mod_mappings mods \
       --guppy-config dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_hac.cfg \
       --remora-modified-bases dna_r9.4.1_e8 hac 0.0.0 5hmc_5mc CG 0 \
       --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server \
       --reference ENSEMBL.GRCh38.fa \
       --device cuda:0 --processes 10 \
       --overwrite --output-directory megalodon_GMtests/
```
And it get some outputs there. But when I inspect the log.txt file, I found a message:

```
#Warning message: DBG 22:13:20 : Could not load guppy server configuration state: 'Configurations' --- MainProcess-MainThread backends.py:913
```

I also tried to use --guppy-params to add the "-d /opt/ont/guppy/data/" directory, 
Or use the example code with "--guppy-config dna_r9.4.1_450bps_fast.cfg"
but the warning is still there.

Is this a crucial message? Or should I just leave it?

**Comment by marcus1487** [comment]
This is a bug in Guppy and is being worked on internally. It is not crucial and can be ignored. This line is intended to provide useful information for debugging any issues with the loaded Guppy settings.
