### ISSUE TITLE
Generate mod_mapping with both options

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/megalodon#307]
Hi Marcus,
In megalodon mod_mapping output, is there a easy way to generate BAM **with and without** bisulfite emulative styles at one run?
Or can we start from some intermediate data to generate one from the other?
Thanks,
Yijun

**Comment by marcus1487** [comment]
There is no way to get both outputs from one run. In theory one could use the modbam output to create the bisulfite emulation output, but there is no implementation of this of which I am aware. The bisulfite emulation was intended as a stopgap until alternative specs/visualizations were made available. Now that the modbam spec is released and genome browsers generally support this format, the bisulfite emulation output should be considered deprecated.

**Comment by marcus1487** [comment]
Unfortunately megalodon is in the process of being deprecated and not under active development. I appreciate that using existing bisulfite pipelines may be attractive, but I would consider this outside the scope of this project certainly. We are moving in the direction of storing modified bases in the modified base BAM tag format and hoping that future tools will be developed against this standard. This tag has the benefit of working for any modified base while bisulfite emulation would only work for 5mC data and thus serving a limited (though certainly important) use case.
