### ISSUE TITLE
RROR: Guppy server initialization failed. See guppy logs in [--output-directory] for more details.

### ISSUE THREAD

**Issue by fire-activate** [nanoporetech/megalodon#309]
I had a problem and looked at log.txt ：
2022-07-19 08:11:06.103067 [guppy/message] ONT Guppy basecall server software version 6.2.1+6588110, client-server API version 11.0.0, minimap2 version 2.22-r1101
log path:            megalodon_results/guppy_log
chunk size:          2000
chunks per runner:   256
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  4
Use of this software is permitted solely under the terms of the end user license agreement (EULA).By running, copying or accessing this software, you are demonstrating your acceptance of the EULA.
The EULA may be found in /public/home/qiulimei/softwore/ont-guppy/bin

2022-07-19 08:11:06.104300 [guppy/info] crashpad_handler not supported on this platform.
2022-07-19 08:11:06.115249 [guppy/info] Listening on port ipc:///tmp/c520-5658-f963-80ac.
2022-07-19 08:11:06.432148 [guppy/message] 
Config loaded:
config file:               /public/home/qiulimei/softwore/ont-guppy/data/dna_r9.4.1_450bps_hac.cfg
model file:                /public/home/qiulimei/softwore/ont-guppy/data/template_r9.4.1_450bps_hac.jsn
model version id           2021-05-17_dna_r9.4.1_minion_384_d37a2ab9
adapter scaler model file: None
2022-07-19 08:11:06.458605 [guppy/error] CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.cpp:234: CUDA_ERROR_NO_DEVICE. Error initialising basecall server using port: ipc:///tmp/c520-5658-f963-80ac. Aborting.
2022-07-19 08:11:06.473372 [guppy/message] The basecall server has shut down successfully.

 
I can't understand what seems to be wrong and I've looked at issues but I still can't fix it. 
Can you help me with this? I look forward to your reply!

**Comment by marcus1487** [comment]
It looks as though guppy cannot find a GPU on this node and the device "cuda:0" has been set. Please ensure that a GPU is available. Also note that megalodon is being deprecated and standalone guppy should be used moving forward.

**Comment by fire-activate** [comment]
So do I just need to do the methylation analysis with guppy now and not use megalodon in combination with guppy?

**Comment by fire-activate** [comment]
> It looks as though guppy cannot find a GPU on this node and the device "cuda:0" has been set. Please ensure that a GPU is available. Also note that megalodon is being deprecated and standalone guppy should be used moving forward.

So do I just need to do the methylation analysis with guppy now and not use megalodon in combination with guppy?

**Comment by marcus1487** [comment]
Yes. That is correct. The recommendation is now to use Guppy which will output bam files with the modbase tags which are now widely supported in the community (pysam, IGV, jbrowse).

**Comment by fire-activate** [comment]
thank you for your answer

> Yes. That is correct. The recommendation is now to use Guppy which will output bam files with the modbase tags which are now widely supported in the community (pysam, IGV, jbrowse).

thank you for your answer

**Comment by sklages** [comment]
> Yes. That is correct. The recommendation is now to use Guppy which will output bam files with the modbase tags which are now widely supported in the community (pysam, IGV, jbrowse).

@marcus1487  ... not sure if I got you right: `megalodon` is not further developed, instead the recommendation is to use `guppy_basecaller` alone for methylation analysis?
