### ISSUE TITLE
Restarting aggregation using run_aggregation.py

### ISSUE THREAD

**Issue by Naish-M** [nanoporetech/megalodon#31]
Hi,

I am trying to detect methylation in our reads but the node crashed after the all the reads were analysed and outputted to the .db but before the modified positions has started being outputted to the .bed (I guess while the .dp was indexing). Can you use the run_aggregation.py scrip to restart the modified base output in this case?

I am trying to run the script using:
python ~/megalodon/scripts/run_aggregation.py --megalodon-directory ~/Documents/Megalodon/megalodon_results --output-suffix recalled --outputs mods --processes 7 

but get the following error:

Traceback (most recent call last):
  File "/home/group/megalodon/scripts/run_aggregation.py", line 126, in <module>
    main()
  File "/home/group/megalodon/scripts/run_aggregation.py", line 110, in main
    args.suppress_progress, valid_read_ids, args.output_suffix)
  File "/home/group/anaconda3/lib/python3.7/site-packages/megalodon/aggregate.py", line 312, in aggregate_stats
    agg_mods = mods.AggMods(mods_db_fn, load_in_mem_indices=False)
  File "/home/group/anaconda3/lib/python3.7/site-packages/megalodon/mods.py", line 1291, in __init__
    self._mod_long_names = self.mods_db.get_mod_long_names()
  File "/home/group/anaconda3/lib/python3.7/site-packages/megalodon/mods.py", line 214, in get_mod_long_names
    'SELECT mod_base, mod_long_name FROM mod_long_names').fetchall())
sqlite3.OperationalError: no such table: mod_long_names

This also happens when I try run the command with .dp files that have gone all the way through the pipeline - so I don't think it is related to the indexing.

Any help would be appreciated.

Best,

Matt

**Comment by marcus1487** [comment]
The `mod_long_names` table was added with the 2.0 release. This is a breaking change from databases created with Megalodon <2.0. My best guess is that this database was created before Megalodon 2.0 and is being analyzed with Megalodon 2.0.

In general, aggregation without the data index is possible, but will likely be incredibly slow. There is not currently the functionality to create the index upon a crash. This could be added in the future, but checks to ensure the database validity would need to be considered for this feature request.

**Comment by Naish-M** [comment]
Hi Marcus,
Yes that was the problem with the database thanks. Another thing I have noticed is the reads will be processed but the output will stop even when within queue capacity - Is there a way to resume the output?

Read Processing: 100%|█| 8000/8000 [1:27:10<00:00,  1.53 read(s)/s, ksamp/s=440]
output queue capacity per_read_mods       :  10%|█▉                  | 978/10000

**Comment by marcus1487** [comment]
This is an issue with `tqdm` (the progress bar package; or more precisely the use of `tqdm` in Megalodon). The output queue is likely processing the "left over" reads in the queue. I have tried to re-work the queue progress bars to update even when the main processing loop has completed (as in the base posted here), but have not found a robust solution for this yet. The run should complete once the output queue has been cleared, though there is no visual indication that the output queue is clearing.

**Comment by marcus1487** [comment]
The progress bars and queue output speeds have been optimized with release 2.1. This issue should be resolved, but please reopen this issue if further issues persist.
