### ISSUE TITLE
multiple input folders ?

### ISSUE THREAD

**Issue by colindaven** [nanoporetech/megalodon#310]
Hi,

I've got a lot of input fast5 data, and some are in two folders (this is Prometh data).

Now I have previously just copied the files together, but we're talking TB here. Is there any scope for megalodon to accept 2+ folders eg as a comma separated string ?

eg 
`fast5s_dir1,fast5s_dir2`

Thanks

**Comment by marcus1487** [comment]
You should be able to soft-link the multiple directories into a new location without copying the data and point megalodon to this new location. Please reach out if this solution does not work for you.

**Comment by colindaven** [comment]
Very true, now why didn't I think of that first ? Thanks.
