### ISSUE TITLE
Guppy server initialization failed

### ISSUE THREAD

**Issue by jorisbalc** [nanoporetech/megalodon#311]
Hello,

I'm trying to train a remora model and for that I must first prepare a dataset. I'm also still learning to work with data and more importantly other OS. To do so, I run the following command 
`megalodon input01 --reference m1.fasta --output-directory mega_res_m1 --outputs mappings signal_mappings --num-reads 10000 --guppy-config dna_r10.4_e8.1_hac_prom.cfg --devices 0 --processes 16 --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server --overwrite`

I'm running the CPU version of guppy installed on ubuntu20.04 on a vmbox with win11 as host (ryzen 3700x cpu). The basecall server initialization fails with the following error "Guppy server initialization failed". After investigating the log I try to launch the command to see what's wrong and it looks like it is unable to find/read some required files.

> /opt/ont/guppy/bin/guppy_basecall_server -p auto -l mega_res_m1/guppy_log -c dna_r10.4_e8.1_hac_prom.cfg --quiet -x cuda:0
terminate called after throwing an instance of 'std::runtime_error'
  what():  This build does not support GPU basecalling mode.
[27589:27589:20220803,102429.875724:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[27589:27589:20220803,102429.875828:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Aborted (core dumped)

I investigated the directories manually and noticed the cpufreq dir is located in the common /cpu directory instead, while the cpu0/cpufreq directories do not exist. Is it likely that this is a vmbox issue, unrelated to guppy?

**Comment by sklages** [comment]
well, the main problem is that you want to run the CPU version but you are actually trying to run the GPU version:
```
what(): This build does not support GPU basecalling mode
```
Just omit `--devices 0` ...

But keep in mind that basecallling with `guppy` without GPU usually takes ages to finish ..
