### ISSUE TITLE
sqlite3.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by xinkaitong** [nanoporetech/megalodon#316]
**Excuse me! I want to get methylation information from fast5 file and execute the following command. But it returns to an error with sqlite3.OperationalError: disk I/O error. Can you tell me how to solve it?**

megalodon \
$f5 \
--guppy-server-path $guppy \
--guppy-config dna_r9.4.1_450bps_fast.cfg \
--remora-modified-bases dna_r9.4.1_e8 fast 0.0.0 5hmc_5mc CG 0 \
--outputs basecalls mappings mod_mappings mods \
--reference $ref \
--processes 20 \
--overwrite

[12:01:04] Running Megalodon version 2.5.0
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[12:01:04] Loading guppy basecalling backend
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an error set
[12:01:54] Loading reference
[12:01:56] Loaded Remora model calls modified bases: h=5hmC (alt to C); m=5mC (alt to C)
Traceback (most recent call last):
  File "/home/goldenpigs/.local/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/home/goldenpigs/.local/lib/python3.7/site-packages/megalodon/__main__.py", line 754, in _main
    megalodon._main(args)
  File "/home/goldenpigs/.local/lib/python3.7/site-packages/megalodon/megalodon.py", line 1807, in _main
    args, mods_info = parse_mod_args(args, model_info, map_info)
  File "/home/goldenpigs/.local/lib/python3.7/site-packages/megalodon/megalodon.py", line 1504, in parse_mod_args
    mods.init_mods_db(mods_info, map_info.ref_names_and_lens)
  File "/home/goldenpigs/.local/lib/python3.7/site-packages/megalodon/mods.py", line 1868, in init_mods_db
    init_db_tables=True,
  File "/home/goldenpigs/.local/lib/python3.7/site-packages/megalodon/mods.py", line 191, in __init__
    self.establish_db_conn()
  File "/home/goldenpigs/.local/lib/python3.7/site-packages/megalodon/mods.py", line 238, in establish_db_conn
    "PRAGMA max_page_count = {}".format(mh.SQLITE_MAX_PAGE_COUNT)
sqlite3.OperationalError: disk I/O error

**Comment by marcus1487** [comment]
This looks like an issue with the sqlite3 package compilation in your python version. I don't think this is something we will be able to fix in megalodon. Megalodon is being deprecated. I would recommend using Guppy to call modified bases.

**Comment by xinkaitong** [comment]
@marcus1487 
I just can't understand why you deprecated Megalodon. A paper from _Genome Biology_, titled DNA methylation-calling tools for Oxford Nanopore sequencing: a survey and human epigenome-wide evaluation, compared seven analytic tools (including Guppy) for detecting DNA methylation from nanopore long-read sequencing data. The results show that the Mogalodon has the most excellent performance.

**Comment by marcus1487** [comment]
The reason for the deprecation of Megalodon is that the features which have recently improved performance of both Guppy and Megalodon modified base detection (Remora algorithms) are now built underneath both Guppy ([as of version 6.1.1](https://community.nanoporetech.com/posts/guppy-v6-1-1-release)) and Megalodon. The manuscript cited uses Guppy version 4.2.2. Additionally the canonical basecalling accuracy has drastically increased with recent Guppy versions reducing the need for the extra research features in Megalodon. Finally, I would note that we are transitioning from Guppy to Dorado in the near future with a primary aim to decrease the time to incorporate such features which previously required initial research implementations (such as Megalodon). 

I hope that this helps in understanding the decision to deprecate Megalodon and we do expect that with the current technology and Remora algorithms that the results will be much better than manuscripts submitted over a year ago.
