### ISSUE TITLE
using custom remora models with megalodon

### ISSUE THREAD

**Issue by jorisbalc** [nanoporetech/megalodon#317]
Greetings,
I have a few questions regarding remora and megalodon. As I understand, the final remora model for identifying custom base modifications is saved in an onnx format. How is megalodon able to acquire this file? I'm mostly just not sure where to put it while running the megalodon command. Secondly, what would be a simple way of comparing two remora generated models with megalodon? Still very new to this.

Thank you in advance!

**Comment by marcus1487** [comment]
Provide a Remora model to Megalodon via the `--remora-modified-bases` argument. See all Megalodon arguments with the `megalodon --help-long` command.

Megalodon has a number of tools to explore the performance of a Remora model via `megalodon_extras validate -h`. See the megalodon documentation for more details.

Additionally megalodon is being deprecated so some of this functionality will be ported over to remora moving forward.
