### ISSUE TITLE
the difference between running megaodon with CPU and GPU?

### ISSUE THREAD

**Issue by kir1to455** [nanoporetech/megalodon#318]
Hi, marcus
I want to know what is the difference between running megaodon with CPU and GPU？
Basecalling with CPU only resources is very very slow.
The only difference is that time is slow？
The CPU Basecalling result will be different from GPU Basecalling result?

Thanks you,
Kirito

**Comment by marcus1487** [comment]
The difference between CPU and GPU implementations should be minimal, but they are fundamentally different so results are not expected to match 100%. As you note the major difference is in running time. Note also that the GPU resources are only consumed by Guppy within Megalodon, so any results that are different will be on the Guppy side.

**Comment by kir1to455** [comment]
Thanks for your reply!
