### ISSUE TITLE
Different genomic coordinates between mappings.bam and mod_mappings.bam

### ISSUE THREAD

**Issue by DidiCi** [nanoporetech/megalodon#320]
Good morning,
I am using Megalodon for the detection of modified bases in human samples.
I noticed that for some reads there is a difference in genomic coordinates (reference start, end and chromosome) between mappings.bam and mod_mappings.bam. Is this normal? If yes, why they change between the two files?
Thank you in advance
Diletta

**Comment by marcus1487** [comment]
My best guess would be multi-mapping reads. The genomic coordinates should be the exact same for the same reads for these two outputs.
