### ISSUE TITLE
the results about  basecalls of megalodon

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/megalodon#322]
Hi, thank you very much for sharing this very powerful tool. 
When I use megalodon to do basecalling, which is achieved by setting '--output' including basecalls, I will get the file called 'basecalls.fastq'. I would like to know whether the result includes all the reads, or just includes the 'pass' reads based on qscore filtering. 
Because when running guppy individually, it will result in two folds, 'pass' and 'fail'. So, I wonder if the basecalling result of megalodon have the similar filtering mechanism.
And if I also include 'signal mapping' in output, does the resulting 'signal_mappings.hdf5' include all the reads or just the 'pass' reads ?
Thank you very much.

**Comment by marcus1487** [comment]
Megalodon does not perform q-score filtering.
