### ISSUE TITLE
Variant phasing on 2.5.0

### ISSUE THREAD

**Issue by gokalpyildirir** [nanoporetech/megalodon#323]
Hello,

I'm trying to apply the variant phasing pipeline using megalodon 2.5.0 and guppy 6.3.7. I am having difficulty finding the right config file. When I try to use the default config (`dna_r9.4.1_450bps_modbases_5mc_hac.cfg` - which is not used anymore, but I got it from an earlier guppy tar) I get an error.

My command: 
```
reads_dir="A4_fast5/fast5"
ref="A4_diploid_sorted.fasta.masked"
variants_vcf="a4_variants.vcf.gz"
out_dir="a4_phased_megalodon_results"
nproc=5
gpu_devices="cuda:all:80%"

# run megalodon to produce variant_mappings
megalodon \
        $reads_dir --outputs mappings variants variant_mappings \
        --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server \
        --reference $ref --variant-filename $variants_vcf \
        --output-directory $out_dir \
        --processes $nproc --devices $gpu_devices \
        --verbose-read-progress 3 --overwrite
```

My error:
[14:20:32] Running Megalodon version 2.5.0
[14:20:32] Loading guppy basecalling backend
./phased_megalodon_2.sh: line 15: 12995 Segmentation fault      (core dumped) megalodon $reads_dir --outputs mappings variants variant_mappings --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server --reference $ref --variant-filename $variants_vcf --output-directory $out_dir --processes $nproc --devices $gpu_devices --verbose-read-progress 3 --overwrite

The log file looks like this:
[14:20:32] Running Megalodon version 2.5.0
DBG 14:20:32 : Command: """/home/science/miniconda3/envs/megalodon/bin/megalodon A4_fast5/fast5 --outputs mappings variants variant_mappings --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server --reference A4_diploid_sorted.fasta.masked --variant-filename a4_variants.vcf.gz --output-directory a4_phased_megalodon_results --processes 5 --devices cuda:all:80% --verbose-read-progress 3 --overwrite""" --- MainProcess-MainThread megalodon.py:1787
[14:20:32] Loading guppy basecalling backend
DBG 14:20:32 : Guppy version: "6.3.7" --- MainProcess-MainThread backends.py:938
DBG 14:20:32 : Pyguppy version: "6.3.7" --- MainProcess-MainThread backends.py:939
DBG 14:20:32 : guppy server init command: "/opt/ont/guppy/bin/guppy_basecall_server -p auto -l a4_phased_megalodon_results/guppy_log -c dna_r9.4.1_450bps_modbases_5mc_hac.cfg --quiet -x cuda:all:80%" --- MainProcess-MainThread backends.py:1017
DBG 14:20:32 : Found guppy log file: a4_phased_megalodon_results/guppy_log/guppy_basecall_server_log-2022-09-28_14-20-32.log --- MainProcess-MainThread backends.py:1032
DBG 14:20:32 : Guppy server started on port ipc:///tmp/4753-3fb1-9577-281e --- MainProcess-MainThread backends.py:973
DBG 14:20:32 : Connecting to server --- MainProcess-MainThread backends.py:872
DBG 14:20:32 : pyguppy server status: result.success --- MainProcess-MainThread backends.py:909
DBG 14:20:32 : Could not load guppy server configuration state: 'Configurations' --- MainProcess-MainThread backends.py:914

Then I try to run using other configs:
```
reads_dir="A4_fast5/fast5"
ref="A4_diploid_sorted.fasta.masked"
variants_vcf="a4_variants.vcf.gz"
out_dir="a4_phased_megalodon_results"
nproc=5
gpu_devices="cuda:all:80%"

# run megalodon to produce variant_mappings
megalodon \
        $reads_dir --outputs mappings variants variant_mappings \
        --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server \
        --guppy-config dna_r9.4.1_450bps_modbases_5mc_cg_hac.cfg \
        --reference $ref --variant-filename $variants_vcf \
        --output-directory $out_dir \
        --processes $nproc --devices $gpu_devices \
        --verbose-read-progress 3 --overwrite
```

This time I get the AssertionError:
[14:34:40] Running Megalodon version 2.5.0
[14:34:40] Loading guppy basecalling backend
[14:34:41] Loading reference
******************** WARNING: Model supporting modified base calling specified, but no modified base outputs requested. This is fine; just wanted to let you know. ********************
[14:34:47] Loaded model calls canonical alphabet ACGT and modified bases m=5mC (alt to C)
Traceback (most recent call last):
  File "/home/science/miniconda3/envs/megalodon/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/home/science/miniconda3/envs/megalodon/lib/python3.7/site-packages/megalodon/__main__.py", line 754, in _main
    megalodon._main(args)
  File "/home/science/miniconda3/envs/megalodon/lib/python3.7/site-packages/megalodon/megalodon.py", line 1807, in _main
    args, mods_info = parse_mod_args(args, model_info, map_info)
  File "/home/science/miniconda3/envs/megalodon/lib/python3.7/site-packages/megalodon/megalodon.py", line 1500, in parse_mod_args
    remora_sig_map_offset=sig_map_shift,
  File "/home/science/miniconda3/envs/megalodon/lib/python3.7/site-packages/megalodon/mods.py", line 2359, in __init__
    self.alphabet, model_info.output_size - self.n_can_state - 1
AssertionError: Alphabet (ACGT) and model number of modified bases (-41) do not agree.

Which contig should I use to solve this? Or do you suggest I use an older guppy version for this analysis?

Thanks for the help!

**Comment by marcus1487** [comment]
The variant calling in megalodon is an experimental feature and unfortunately unsupported. Megalodon as a whole is being deprecated as well. I would recommend looking to the community for the current variant calling recommendations.
