### ISSUE TITLE
input of already guppy called fast5s?

### ISSUE THREAD

**Issue by inijman** [nanoporetech/megalodon#33]
Hi,
We are considering processing 166 promethion runs with megaldon but can much more efficiently basecall the raw data on our GPU cluster (where we cannot install the guppy server). Is there a way to provide these -already mod called- fast5s to megaldon?

**Comment by marcus1487** [comment]
Megalodon does provide an interface for reading the necessary basecalling information from a fast5 file. See some documentation [here](https://nanoporetech.github.io/megalodon/advanced_arguments.html#guppy-backend-argument). Note that this interface requires the `—post_out` argument to be specified in the guppy caller which can increase both disk usage and decrease performance by 5-10X. Note that this is additional information than the default information stored via the `—fast5_out` option. 

What is blocking the installation of the guppy server on the gpu cluster? I believe running the regular guppy basecalls runs the guppy server in the background. I would highly recommend getting the guppy server installed to most efficiently process this data with Megalodon. 

On an additional note for processing this amount of data, a new Megalodon version and updated 5mC modified base model will be released soon. This new model will drastically increase the performance of Megalodon modified base detection. Thus I would recommend waiting to process this data for this release in the next week or so.

**Comment by inijman** [comment]
thanks. very unfortunate that another setting is required with such a penalty in runtime and footprint. on the GPU cluster we send jobs with guppy script into the queue and cannot predict where the land and on which node etc. Therefore the port handling will be very difficult.

But we will definately wait for the new version.

**Comment by acibadem** [comment]
Hi,
I have same guppy server problem with megalodon. I also need your advide how to address fast5 directory in the batch.
See below log
/var/spool/slurmd/job12151017/slurm_script: line 16: cd: /home/p289325/Programs/ont-guppy/bin/guppy_basecall_server: Not a directory
usage: megalodon [-h] [--guppy-config GUPPY_CONFIG]
                 [--guppy-server-path GUPPY_SERVER_PATH]
                 [--guppy-server-port GUPPY_SERVER_PORT]
                 [--outputs {basecalls,mod_basecalls,mappings,per_read_variants,variants,whatshap_mappings,per_read_mods,mods,signal_mappings,per_read_refs} [{basecalls,mod_basecalls,mappings,per_read_variants,variants,whatshap_mappings,per_read_mods,mods,signal_mappings,per_read_refs} ...]]
                 [--output-directory OUTPUT_DIRECTORY] [--overwrite]
                 [--mappings-format {bam,cram,sam}] [--reference REFERENCE]
                 [--haploid] [--variant-filename VARIANT_FILENAME]
                 [--variant-calibration-filename VARIANT_CALIBRATION_FILENAME]
                 [--mod-motif BASE MOTIF REL_POSITION]
                 [--mod-calibration-filename MOD_CALIBRATION_FILENAME]
                 [--help-long] [--processes PROCESSES]
                 [--devices DEVICES [DEVICES ...]]
                 [--verbose-read-progress VERBOSE_READ_PROGRESS] [-v]
                 fast5s_dir
megalodon: error: the following arguments are required: fast5s_dir
/var/spool/slurmd/job12151017/slurm_script: line 23: fast5s_dir: command not found

**Comment by marcus1487** [comment]
@acibadem this looks like an invalid megalodon command. This error indicates that the directory of reads to be called is not provided. Could you post the full command for this attempted megalodon run?

**Comment by acibadem** [comment]
#!/bin/bash

#SBATCH --partition=gpu

#SBATCH --gres=gpu:v100:1

#SBATCH --time=23:59:00

#SBATCH --cpus-per-task=12

#SBATCH --mem=120GB

#SBATCH --job-name=megalodon_MT

#SBATCH --output=/data/p289325/megalodon/megalodon_gpu_160620T_MT.log

module load Python/3.8.2-GCCcore-9.3.0

# Make sure that the megalodon executable can be found

export PATH=~/.local/bin:/home/p289325/Programs/ont-guppy/

# Make sure that the megalodon executable can be found

export PATH=~/.local/bin:/home/p289325/.conda/envs/megalodon

# Example command to output basecalls, mappings, variants and CpG methylation

# Compute settings: GPU device 0 with all 12 CPU cores

cd /home/p289325/Programs/ont-guppy/bin/guppy_basecall_server

megalodon /data/p289325/Nanopore_mt/fast5_old/ \

  --guppy-server-path=/home/p289325/Programs/ont-guppy/bin/ --guppy-server-port --guppy-config dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --mappings-format bam --reference /data/p289325/Human_Genome/MT/rCRS$

  --basecalls-format fasta --outputs "basecalls" "mod_basecalls" "per_read_mods" "mappings" "mods" "per_read_refs" "signal_mappings" "per_read_mods" "mods" "per_read_refs" \

  --mod-motif Z CG 0 --mod-motif Z CCWGG 1 --mod-motif Y GATC 1 --mod-output-formats "bedmethyl" "modvcf" \

  --taiyaki-model-filename /data/p289325/megalodon/megalodon_results_test_080820_Taiyaki --mod-calibration-filename /data/p289325/megalodon/megalodon_results_test_080820_1 --mod-binary-threshold 0.75 --mod-outp$

  --write-mod-log-probs --write-mods-text --edge-buffer 2 --output-directory /data/p289325/megalodon/megalodon_results_test_080820_1 --overwrite --devices 0 –processes

**Comment by marcus1487** [comment]
This command does not seem to agree with the previously posted error. The error indicates that `fast5s_dir` was attempted as a command, but that string does not appear in the command posted. Additionally, it appears that there is an attempt to `cd` to the guppy server file which is raising and error. Also the path to the guppy server directory not the executable is passed to the megalodon command which may cause an issue once these other issues are resolved.

Could you try a single command outside of your slurm script to ensure the correct syntax for this command? 

Additionally, these errors do not seem related to the original post in this issue. If these issues remain, could you start a new issue pertaining to the megalodon command syntax?

**Comment by marcus1487** [comment]
Fixed in release 2.1.

**Comment by acibadem** [comment]
megalodon ./data/p289325/Nanopore_mt/test_fast5/tar_files_nanopore_barcoded_HepG2/wt/ \
--guppy-server-path ~/Programs/ont-guppy/bin/guppy_basecall_server --live-processing \
--guppy-params "-d ./rerio/basecall_models/ --num_callers 5 --ipc_threads 6" \
--guppy-config res_dna_r941_min_modbases-all-context_v001.cfg \
--outputs mods --output-directory /data/p289325/Nanopore_mt/basecalled_fast5s_MeTeOr/ \
--reference /data/p289325/Human_Genome/chrM.fasta \
--mod-motif Z CG 0 \
--write-mods-text \
--mod-aggregate-method binary_threshold \
--mod-binary-threshold 0.7 \
--mod-output-formats bedmethyl \
--devices 0 --processes 8 --overwrite \

After running above,

What below message could mean?

[18:45:43] Running Megalodon version 2.2.4
[18:45:43] Loading guppy basecalling backend
[18:46:33] Loading reference
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[18:46:33] Using canonical alphabet ACGT and modified bases Y=6mA (alt to A); Z=5mC (alt to C)
[18:46:33] Preparing workers to process reads
[18:46:33] Processing reads
Full output or empty input queues indicate I/O bottleneck
3 most common unsuccessful processing stages:

    -----

    -----[A


    -----[A[A



Read Processing: 0reads [00:00, ?reads/s][A[A[A




input queue capacity extract_signal      :   0%|          | 0/10000[A[A[A[A





output queue capacity per_read_mods       :   0%|          | 0/10000[A[A[A[A[A[18:46:34] Waiting for mods database to complete indexing

    -----

    -----

    -----

Read Processing: 0reads [00:01, ?reads/s]

input queue capacity extract_signal      :   0%|          | 0/10000

output queue capacity per_read_mods       :   0%|          | 0/10000
[18:46:34] All reads processed successfully
[18:46:34] Spawning modified base aggregation processes
******************** WARNING: No per-read variants or modified base statistics found for aggregation. ********************
[18:46:34] Mega Done
[2020-11-13 18:46:32.255643] [0x00007f261415a740] [info]    Connecting to server as 


###############################################################################

**Comment by marcus1487** [comment]
This indicates that Megalodon did not find any fast5 files with reads to process. The log.txt file may have some information about how this happened. E.g. if any fast5 files were found or if there were no reads found in the fast5 files.

**Comment by acibadem** [comment]
[23:17:08] Running Megalodon version 2.2.4
DBG 23:17:08 : Command: """/home/p289325/Programs/megalodon_env/bin/megalodon ./data/p289325/Nanopore_mt/test_fast5/multi_reads_b1_new/HepG2_wt/ --guppy-server-path /home/p289325/Programs/ont-guppy/bin/guppy_basecall_server --live-processing --guppy-params -d ./rerio/basecall_models/ --num_callers 5 --ipc_threads 6 --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg --outputs mods --output-directory /data/p289325/Nanopore_mt/basecalled_fast5s_MeTeOr/ --reference /data/p289325/Human_Genome/chrM.fasta --mod-motif Z CG 0 --write-mods-text --mod-aggregate-method binary_threshold --mod-binary-threshold 0.7 --mod-output-formats bedmethyl --devices 0 --processes 8 --overwrite""" --- MainProcess-MainThread megalodon.py:1219
[23:17:08] Loading guppy basecalling backend
DBG 23:17:52 : Guppy version: "4.2.2" --- MainProcess-MainThread backends.py:500
DBG 23:17:52 : Pyguppy version: "4.2.2" --- MainProcess-MainThread backends.py:501
DBG 23:17:52 : guppy server init command: "/home/p289325/Programs/ont-guppy/bin/guppy_basecall_server -p auto -l /data/p289325/Nanopore_mt/basecalled_fast5s_MeTeOr/guppy_log -c res_dna_r941_min_modbases-all-context_v001.cfg --post_out -x cuda:0 -d ./rerio/basecall_models/ --num_callers 5 --ipc_threads 6" --- MainProcess-MainThread backends.py:559
DBG 23:18:25 : init_test_read BasecallingCompleted --- MainProcess-MainThread backends.py:887
[23:18:25] Loading reference
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[23:18:26] Using canonical alphabet ACGT and modified bases Y=6mA (alt to A); Z=5mC (alt to C)
[23:18:26] Preparing workers to process reads
DBG 23:18:26 : Starting --- FileFiller-MainThread fast5_io.py:331
DBG 23:18:26 : Starting --- FileFiller-FileEnum fast5_io.py:294
DBG 23:18:26 : Starting --- FileFiller-ReadEnumThread000 fast5_io.py:277
DBG 23:18:26 : Starting --- FileFiller-ReadEnumThread001 fast5_io.py:277
DBG 23:18:26 : Starting --- FileFiller-ReadEnumThread002 fast5_io.py:277
DBG 23:18:26 : Starting --- FileFiller-ReadEnumThread003 fast5_io.py:277
DBG 23:18:26 : Starting --- SignalExtractor000-MainThread fast5_io.py:246
DBG 23:18:26 : Starting --- FileFiller-ReadEnumThread004 fast5_io.py:277
DBG 23:18:26 : Closing --- FileFiller-ReadEnumThread000 fast5_io.py:290
DBG 23:18:26 : Found 0 total FAST5 files --- FileFiller-FileEnum fast5_io.py:319
DBG 23:18:26 : Starting --- SignalExtractor000-ExtractSigThread000 fast5_io.py:209
DBG 23:18:26 : Starting --- FileFiller-ReadEnumThread005 fast5_io.py:277
DBG 23:18:26 : Starting --- SignalExtractor000-ExtractSigThread001 fast5_io.py:209
DBG 23:18:26 : Starting --- FileFiller-ReadEnumThread006 fast5_io.py:277
DBG 23:18:26 : Closing --- FileFiller-ReadEnumThread001 fast5_io.py:290
DBG 23:18:26 : Starting --- SignalExtractor000-ExtractSigThread002 fast5_io.py:209
DBG 23:18:26 : Closing --- FileFiller-FileEnum fast5_io.py:320
DBG 23:18:26 : Starting --- FileFiller-ReadEnumThread007 fast5_io.py:277
DBG 23:18:26 : Starting --- SignalExtractor000-ExtractSigThread003 fast5_io.py:209
DBG 23:18:26 : Closing --- FileFiller-ReadEnumThread002 fast5_io.py:290
DBG 23:18:26 : Starting --- SignalExtractor000-ExtractSigThread004 fast5_io.py:209
DBG 23:18:26 : InitComplete --- FileFiller-MainThread fast5_io.py:351
DBG 23:18:26 : Starting --- SignalExtractor000-ExtractSigThread005 fast5_io.py:209
DBG 23:18:26 : Closing --- FileFiller-ReadEnumThread003 fast5_io.py:290
DBG 23:18:26 : Closing --- FileFiller-ReadEnumThread004 fast5_io.py:290
DBG 23:18:26 : Starting --- SignalExtractor000-ExtractSigThread006 fast5_io.py:209
DBG 23:18:26 : Closing --- FileFiller-ReadEnumThread005 fast5_io.py:290
DBG 23:18:26 : Closing --- FileFiller-ReadEnumThread006 fast5_io.py:290
DBG 23:18:26 : Closing --- FileFiller-ReadEnumThread007 fast5_io.py:290
DBG 23:18:26 : Starting --- SignalExtractor000-ExtractSigThread007 fast5_io.py:209
DBG 23:18:26 : InitComplete --- SignalExtractor000-MainThread fast5_io.py:255
DBG 23:18:26 : Starting --- SignalExtractor001-MainThread fast5_io.py:246
DBG 23:18:26 : Starting --- SignalExtractor001-ExtractSigThread000 fast5_io.py:209
DBG 23:18:26 : Starting --- SignalExtractor001-ExtractSigThread001 fast5_io.py:209
DBG 23:18:26 : Starting --- SignalExtractor001-ExtractSigThread002 fast5_io.py:209
DBG 23:18:26 : Starting --- SignalExtractor001-ExtractSigThread003 fast5_io.py:209
DBG 23:18:26 : Starting --- SignalExtractor001-ExtractSigThread004 fast5_io.py:209
DBG 23:18:26 : Starting --- SignalExtractor001-ExtractSigThread005 fast5_io.py:209
DBG 23:18:26 : Starting --- SignalExtractor001-ExtractSigThread006 fast5_io.py:209
DBG 23:18:26 : Starting --- SignalExtractor001-ExtractSigThread007 fast5_io.py:209
DBG 23:18:26 : InitComplete --- SignalExtractor001-MainThread fast5_io.py:255
DBG 23:18:26 : GetterStarting --- per_read_mods-MainThread mods.py:1420
DBG 23:18:26 : Closing --- SignalExtractor000-ExtractSigThread001 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor001-ExtractSigThread000 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor001-ExtractSigThread001 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor001-ExtractSigThread002 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor001-ExtractSigThread003 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor001-ExtractSigThread004 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor001-ExtractSigThread005 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor001-ExtractSigThread006 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor001-ExtractSigThread007 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor000-ExtractSigThread000 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor000-ExtractSigThread002 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor000-ExtractSigThread003 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor000-ExtractSigThread004 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor001-MainThread fast5_io.py:267
[23:18:26] Processing reads
DBG 23:18:26 : Closing --- SignalExtractor000-ExtractSigThread005 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor000-ExtractSigThread006 fast5_io.py:219
DBG 23:18:26 : GetterStarting --- failed_reads-MainThread megalodon.py:522
DBG 23:18:26 : Closing --- SignalExtractor000-ExtractSigThread007 fast5_io.py:219
DBG 23:18:26 : Closing --- SignalExtractor000-MainThread fast5_io.py:267
DBG 23:18:26 : Starting --- ReadWorker000-MainThread megalodon.py:294
DBG 23:18:26 : GetterInitComplete --- failed_reads-MainThread megalodon.py:530
DBG 23:18:26 : Starting --- ReadWorker001-MainThread megalodon.py:294
DBG 23:18:26 : Starting --- ReadWorker002-MainThread megalodon.py:294
DBG 23:18:26 : Starting --- ReadWorker003-MainThread megalodon.py:294
DBG 23:18:26 : Starting --- ReadWorker004-MainThread megalodon.py:294
DBG 23:18:26 : GetterInitComplete --- per_read_mods-MainThread mods.py:1460
DBG 23:18:26 : Starting --- ReadWorker005-MainThread megalodon.py:294
DBG 23:18:26 : Starting --- ReadWorker006-MainThread megalodon.py:294
DBG 23:18:26 : Starting --- ReadWorker007-MainThread megalodon.py:294
DBG 23:18:26 : MappingWorkerStarting --- MainProcess-Mapper000 mapping.py:230
DBG 23:18:26 : MappingWorkerStarting --- MainProcess-Mapper001 mapping.py:230
DBG 23:18:26 : MappingWorkerInitComplete --- MainProcess-Mapper000 mapping.py:234
DBG 23:18:26 : MappingWorkerInitComplete --- MainProcess-Mapper001 mapping.py:234
DBG 23:18:26 : MappingWorkerStarting --- MainProcess-Mapper002 mapping.py:230
DBG 23:18:26 : MappingWorkerStarting --- MainProcess-Mapper003 mapping.py:230
DBG 23:18:26 : MappingWorkerStarting --- MainProcess-Mapper004 mapping.py:230
DBG 23:18:26 : MappingWorkerInitComplete --- MainProcess-Mapper002 mapping.py:234
DBG 23:18:26 : MappingWorkerStarting --- MainProcess-Mapper005 mapping.py:230
DBG 23:18:26 : MappingWorkerInitComplete --- MainProcess-Mapper003 mapping.py:234
DBG 23:18:26 : MappingWorkerStarting --- MainProcess-Mapper006 mapping.py:230
DBG 23:18:26 : MappingWorkerInitComplete --- MainProcess-Mapper004 mapping.py:234
DBG 23:18:26 : MappingWorkerStarting --- MainProcess-Mapper007 mapping.py:230
DBG 23:18:26 : JoiningMain: FileFiller --- MainProcess-MainThread megalodon.py:623
DBG 23:18:26 : MappingWorkerInitComplete --- MainProcess-Mapper005 mapping.py:234
DBG 23:18:26 : MappingWorkerInitComplete --- MainProcess-Mapper006 mapping.py:234
DBG 23:18:26 : MappingWorkerInitComplete --- MainProcess-Mapper007 mapping.py:234
DBG 23:18:26 : JoinedMain: FileFiller --- MainProcess-MainThread megalodon.py:625
DBG 23:18:26 : JoiningMain: SignalExtractors --- MainProcess-MainThread megalodon.py:639
DBG 23:18:26 : JoinedMain: SignalExtractors --- MainProcess-MainThread megalodon.py:642
DBG 23:18:26 : Closing --- ReadWorker002-MainThread megalodon.py:264
DBG 23:18:26 : Closing --- ReadWorker007-MainThread megalodon.py:264
DBG 23:18:26 : Closing --- ReadWorker005-MainThread megalodon.py:264
DBG 23:18:26 : Closing --- ReadWorker000-MainThread megalodon.py:264
DBG 23:18:26 : Closing --- ReadWorker004-MainThread megalodon.py:264
DBG 23:18:26 : Closing --- ReadWorker003-MainThread megalodon.py:264
DBG 23:18:26 : Closing --- ReadWorker001-MainThread megalodon.py:264
DBG 23:18:26 : Closing --- ReadWorker006-MainThread megalodon.py:264
DBG 23:18:26 : MappingWorkerClosing --- MainProcess-Mapper007 mapping.py:239
DBG 23:18:26 : MappingWorkerClosing --- MainProcess-Mapper005 mapping.py:239
DBG 23:18:26 : MappingWorkerClosing --- MainProcess-Mapper002 mapping.py:239
DBG 23:18:26 : MappingWorkerClosing --- MainProcess-Mapper000 mapping.py:239
DBG 23:18:26 : MappingWorkerClosing --- MainProcess-Mapper003 mapping.py:239
DBG 23:18:26 : MappingWorkerClosing --- MainProcess-Mapper001 mapping.py:239
DBG 23:18:26 : MappingWorkerClosing --- MainProcess-Mapper004 mapping.py:239
DBG 23:18:26 : MappingWorkerClosing --- MainProcess-Mapper006 mapping.py:239
DBG 23:18:27 : JoiningMain: Workers --- MainProcess-MainThread megalodon.py:673
DBG 23:18:27 : JoiningMain: ReadWorker000 --- MainProcess-MainThread megalodon.py:676
DBG 23:18:27 : JoinedMain: ReadWorker000 --- MainProcess-MainThread megalodon.py:678
DBG 23:18:27 : JoiningMain: ReadWorker001 --- MainProcess-MainThread megalodon.py:676
DBG 23:18:27 : JoinedMain: ReadWorker001 --- MainProcess-MainThread megalodon.py:678
DBG 23:18:27 : JoiningMain: ReadWorker002 --- MainProcess-MainThread megalodon.py:676
DBG 23:18:27 : JoinedMain: ReadWorker002 --- MainProcess-MainThread megalodon.py:678
DBG 23:18:27 : JoiningMain: ReadWorker003 --- MainProcess-MainThread megalodon.py:676
DBG 23:18:27 : JoinedMain: ReadWorker003 --- MainProcess-MainThread megalodon.py:678
DBG 23:18:27 : JoiningMain: ReadWorker004 --- MainProcess-MainThread megalodon.py:676
DBG 23:18:27 : JoinedMain: ReadWorker004 --- MainProcess-MainThread megalodon.py:678
DBG 23:18:27 : JoiningMain: ReadWorker005 --- MainProcess-MainThread megalodon.py:676
DBG 23:18:27 : JoinedMain: ReadWorker005 --- MainProcess-MainThread megalodon.py:678
DBG 23:18:27 : JoiningMain: ReadWorker006 --- MainProcess-MainThread megalodon.py:676
DBG 23:18:27 : JoinedMain: ReadWorker006 --- MainProcess-MainThread megalodon.py:678
DBG 23:18:27 : JoiningMain: ReadWorker007 --- MainProcess-MainThread megalodon.py:676
DBG 23:18:27 : JoinedMain: ReadWorker007 --- MainProcess-MainThread megalodon.py:678
DBG 23:18:27 : JoiningMain: Mappers --- MainProcess-MainThread megalodon.py:679
DBG 23:18:27 : JoiningMain: Mapper000 --- MainProcess-MainThread megalodon.py:682
DBG 23:18:27 : JoinedMain: Mapper000 --- MainProcess-MainThread megalodon.py:684
DBG 23:18:27 : JoiningMain: Mapper001 --- MainProcess-MainThread megalodon.py:682
DBG 23:18:27 : JoinedMain: Mapper001 --- MainProcess-MainThread megalodon.py:684
DBG 23:18:27 : JoiningMain: Mapper002 --- MainProcess-MainThread megalodon.py:682
DBG 23:18:27 : JoinedMain: Mapper002 --- MainProcess-MainThread megalodon.py:684
DBG 23:18:27 : JoiningMain: Mapper003 --- MainProcess-MainThread megalodon.py:682
DBG 23:18:27 : JoinedMain: Mapper003 --- MainProcess-MainThread megalodon.py:684
DBG 23:18:27 : JoiningMain: Mapper004 --- MainProcess-MainThread megalodon.py:682
DBG 23:18:27 : JoinedMain: Mapper004 --- MainProcess-MainThread megalodon.py:684
DBG 23:18:27 : JoiningMain: Mapper005 --- MainProcess-MainThread megalodon.py:682
DBG 23:18:27 : JoinedMain: Mapper005 --- MainProcess-MainThread megalodon.py:684
DBG 23:18:27 : JoiningMain: Mapper006 --- MainProcess-MainThread megalodon.py:682
DBG 23:18:27 : JoinedMain: Mapper006 --- MainProcess-MainThread megalodon.py:684
DBG 23:18:27 : JoiningMain: Mapper007 --- MainProcess-MainThread megalodon.py:682
DBG 23:18:27 : JoinedMain: Mapper007 --- MainProcess-MainThread megalodon.py:684
DBG 23:18:27 : JoiningMain: Getters --- MainProcess-MainThread megalodon.py:687
[23:18:27] Waiting for mods database to complete indexing
DBG 23:18:27 : JoiningMain: per_read_mods --- MainProcess-MainThread megalodon.py:697
DBG 23:18:27 : GetterClosing --- failed_reads-MainThread megalodon.py:556
[23:18:27] All reads processed successfully
DBG 23:18:27 : GetterClosing --- per_read_mods-MainThread mods.py:1477
DBG 23:18:27 : CreatingIndex --- per_read_mods-MainThread mods.py:1493
DBG 23:18:27 : ClosingDB --- per_read_mods-MainThread mods.py:1495
DBG 23:18:27 : JoinedMain: per_read_mods --- MainProcess-MainThread megalodon.py:699
DBG 23:18:27 : JoiningMain: Complete --- MainProcess-MainThread megalodon.py:700
[23:18:27] Spawning modified base aggregation processes
******************** WARNING: No per-read variants or modified base statistics found for aggregation. ********************
[23:18:27] Mega Done

**Comment by marcus1487** [comment]
This line `FileFiller-FileEnum fast5_io.py:319
DBG 23:18:26 : Starting --- SignalExtractor000-ExtractSigThread000 fast5_io.py:209` indicates that no fast5 files were found. Megalodon only processes files ending in fast5. Are there files with this ending within this directory (including subdirectories)?

I also note you are using the —live-processing argument. This could be related to this issue. Do you get the same error without running with the live processing option? If so this could be a bug with that option. 

On an unrelated note, I would highly recommend using the latest CpG model from Rerio for CpG methylation detection. These results are much better than the default model from Guppy.

**Comment by acibadem** [comment]
I have fast5 files in the directory but somehow it can not be decteted.

I removed  —live-processing argument but result is same.

Later, I have updated the Rerio for CpG methylation detection to 
--guppy-config res_dna_r941_min_modbases_5mC_5hmC_CpG_v001.cfg

I have got below log

[01:26:04] Running Megalodon version 2.2.4
[01:26:04] Loading guppy basecalling backend
[01:26:15] Loading reference
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[01:26:15] Using canonical alphabet ACGT and modified bases m=5mC (alt to C); h=5hmC (alt to C)
[2020-11-15 01:26:15.207333] [0x00007ff9964dd740] [info]    Connecting to server as 
Traceback (most recent call last):
  File "/home/p289325/Programs/megalodon_env/bin/megalodon", line 11, in <module>
    load_entry_point('megalodon==2.2.4', 'console_scripts', 'megalodon')()
  File "/home/p289325/Programs/megalodon_env/lib/python3.7/site-packages/megalodon/__main__.py", line 430, in _main
    megalodon._main(args)
  File "/home/p289325/Programs/megalodon_env/lib/python3.7/site-packages/megalodon/megalodon.py", line 1234, in _main
    args, model_info, ref_out_info, map_info)
  File "/home/p289325/Programs/megalodon_env/lib/python3.7/site-packages/megalodon/megalodon.py", line 1000, in parse_mod_args
    skip_db_index=skip_db_index, do_output=do_output)
  File "/home/p289325/Programs/megalodon_env/lib/python3.7/site-packages/megalodon/mods.py", line 1640, in __init__
    self._parse_mod_motifs(all_mod_motifs_raw)
  File "/home/p289325/Programs/megalodon_env/lib/python3.7/site-packages/megalodon/mods.py", line 1555, in _parse_mod_motifs
    mod_base, list(self.str_to_int_mod_labels.keys()))
AssertionError: Modified base label (Z) not found in model alphabet (['m', 'h']).


###############################################################################

**Comment by acibadem** [comment]
I have used --mod-motif mh CG 0

But I am back to the initial error...

[01:40:08] Running Megalodon version 2.2.4
[01:40:08] Loading guppy basecalling backend
[01:40:15] Loading reference
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[01:40:15] Using canonical alphabet ACGT and modified bases m=5mC (alt to C); h=5hmC (alt to C)
[01:40:16] Preparing workers to process reads
[01:40:16] Processing reads
Full output or empty input queues indicate I/O bottleneck
3 most common unsuccessful processing stages:

    -----

    -----[A


    -----[A[A



Read Processing: 0reads [00:00, ?reads/s][A[A[A




 input queue capacity extract_signal      :   0%|          | 0/10000[A[A[A[A





output queue capacity per_read_mods       :   0%|          | 0/10000[A[A[A[A[A[01:40:17] Waiting for mods database to complete indexing

    -----

    -----

    -----

Read Processing: 0reads [00:01, ?reads/s]

 input queue capacity extract_signal      :   0%|          | 0/10000

output queue capacity per_read_mods       :   0%|          | 0/10000
[01:40:17] All reads processed successfully
[01:40:17] Spawning modified base aggregation processes
******************** WARNING: No per-read variants or modified base statistics found for aggregation. ********************
[01:40:17] Mega Done
[2020-11-15 01:40:15.809138] [0x00007f2b076d8740] [info]    Connecting to server as 


###############################################################################

**Comment by acibadem** [comment]
megalodon ./data/p289325/Nanopore_mt/test_fast5/multi_reads_b1_new/HepG2_wt/

removing . from the beginning made fast5 folder visible and .sh running successfully

**Comment by acibadem** [comment]
Dear Marcus,

I have completed a run looks good.

What do you think? Do you see any fatal problem? It was relatively fast.

 

See log file in below link

https://unishare.nl/index.php/s/8wfw63gA7knT6Ro

 

 

Thank you for the support,

AGAH

**Comment by acibadem** [comment]
- are there further scripts available to collate the data into for example % methylation at each position?

**Comment by marcus1487** [comment]
There seem to be a large number or reads not aligning to the reference, and the input FAST5s appear to be in single FAST5 format, but aside from this the run looks fine.

For the reporting of percent methylation at each position, this is product of the `--outputs mods` option. This file should appear in the output directory. See details for aggregated modified base outputs [here in the docs](https://nanoporetech.github.io/megalodon/file_formats.html#aggregated-modified-bases).

**Comment by acibadem** [comment]
I have used multi fast5 files however what makes you think that single fast5 file is used. Can it be that my command line could not recognise more than one fast5 in the folder?

I could locate the .bed files so it is the one which has to report per cent methylation, right?

**Comment by marcus1487** [comment]
There are many lines in the log which indicate only a single read id was extracted from each FAST5 file. See with `grep FileFiller log_Megalodon.txt | less -S`. And indeed the fast5 files are named by the read UUID, indicating that these are single FAST5 files.

Yes the BED file is the aggregated modified base results reporting percent methylation. Again find this information in the [doc here](https://nanoporetech.github.io/megalodon/file_formats.html#aggregated-modified-bases).

**Comment by acibadem** [comment]
Dear Marcus,

 

I would like to submit a feature request for Megalodon.

Examples of running an end to end to a workflow including megalodon_extras for calling modified bases.

Best,

AGAH
