### ISSUE TITLE
how to caculate the Methylation Frequency with silde window method

### ISSUE THREAD

**Issue by zhoudreames** [nanoporetech/megalodon#334]
I got the modified_bases.5mC.bed file by using megalodon:
![image](https://user-images.githubusercontent.com/54714639/215481880-805d6beb-62f9-45f1-b683-a75c6f680973.png)
I want to gain  the methylation frequency  for each 10-kb bins, how got it? Thanks~

**Comment by zhoudreames** [comment]
@rmp @javierblasco @myrtlecat @SamStudio8  I am so sorry to disturb you, can you help me ? Thanks~

**Comment by tamvas3712** [comment]
Use the appropriate R function from MethylKit library.
