### ISSUE TITLE
pod5 migration for methylation

### ISSUE THREAD

**Issue by colindaven** [nanoporetech/megalodon#336]
Hi,

as ONT moves more towards pod5 output format as a default in 2023, how will this affect methylation calling workflows (I'd like to start re-writing pipelines)?

At the moment I see several possibilities (please correct me if I am wrong)
- call using dorado directly
- use megalodon to call or refine calls on different motifs using dorado basecalled data
- ? Something else

In this landscape I guess there will be a future for megalodon, but not for guppy or fast5. Is that correct?

I hope modbam format and the modbamtobed package will continue to be supported as well.

Thanks

**Comment by marcus1487** [comment]
Megalodon is being deprecated. I would strongly recommend moving pipelines away from megalodon. Megalodon will not add POD5 support.

The modbam format is currently output by all basecallers (guppy, bonito and dorado). This will be the primary output format. modbam2bed type analysis will certainly be supported moving forward.
