### ISSUE TITLE
No ont_guppy

### ISSUE THREAD

**Issue by weishwu** [nanoporetech/megalodon#347]
I installed `megalodon` and `ont_pyguppy_client_lib` without problems, but when I run `megalodon_extras modified_bases describe_alphabet`, it says 

> FileNotFoundError: [Errno 2] No such file or directory: './ont-guppy/bin/guppy_basecall_server'

I can't find this `ont-guppy` anywhere. 

Below is what I ran to install megalodon:
```
conda install megalodon
pip install ont_pyguppy_client_lib
```
I also tried installing `guppy3`, but still there is no `ont-guppy`.
I think I have to install guppy server, am I right?

**Comment by marcus1487** [comment]
Megalodon is deprecated as noted in the top of the readme. Please follow the recommendations there for the correct tools to replace Megalodon.
