### ISSUE TITLE
How to get the bed file from per_read_modified_base_calls.db

### ISSUE THREAD

**Issue by Smart-zhi** [nanoporetech/megalodon#35]
Hi,
When I analyzed the DNA methylation in human , I divided the original files into multiple parts to run `megalodon v1.0.2`.  After that I got multiple sets of 

> log.txt 
> mappings.bam 
> modified_bases.5mC.bed 
> modified_bases.6mA.bed 
> per_read_modified_base_calls.db 
> per_read_modified_base_calls.txt file.

Then I used `merge_per_read_modified_base_dbs.py` to merge `per_read_modified_base_calls.db`s, and I got `megalodon_merge_mods_results/per_read_modified_base_calls.db`. 

I hope get `bed` file finally, but I don't know how to do. Can you give some advise on these?

**Comment by marcus1487** [comment]
In version <2.1, thus step is completed with the `run_aggregate.py` script. In version >=2.1 this is run with the `megalodon_extras aggregate run` command.

**Comment by Smart-zhi** [comment]
I used `run_aggregate.py` script: 
``` bash
python ${megalodon}/run_aggregation.py --outputs mods --megalodon-directory ./megalodon_merge_mods_results --output-suffix re_aggregated  --mod-output-formats  bedmethyl 
```
and I got:
``` bash
Loading model.
Traceback (most recent call last):
  File "/home/tools/megalodon-1.0.2/scripts/run_aggregation.py", line 134, in <module>
    main()
  File "/home/tools/megalodon-1.0.2/scripts/run_aggregation.py", line 107, in main
    args.taiyaki_model_filename)).mod_long_names
  File "/home/tools/anaconda3/envs/megalodon/lib/python3.6/site-packages/megalodon/backends.py", line 236, in __init__
    raise mh.MegaError('Invalid model specification.')
megalodon.megalodon_helper.MegaError: Invalid model specification.
```
```
$ ls megalodon_merge_mods_results/*
megalodon_merge_mods_results/per_read_modified_base_calls.db
```

**Comment by Smart-zhi** [comment]
Thank you.
