### ISSUE TITLE
Aggregation takes longer time than normal

### ISSUE THREAD

**Issue by XINYAN2** [nanoporetech/megalodon#40]
I was running megalodon and output directory is also located on a local disk. However, the aggregation step seems to take forever to run. Because I ran megalodon successfully before under same environment whose aggregation is much much faster than this one. Any idea to solve this? 
<img width="1232" alt="Screen Shot 2020-07-09 at 10 21 22 AM" src="https://user-images.githubusercontent.com/13326275/86990090-64fdcd80-c1ce-11ea-90c8-652614682ced.png">

**Comment by marcus1487** [comment]
This is certainly much slower aggregation time than expected. While the disk where the database are stored is local, are they an SSD or an HDD disk. The speed improvement may be quite significant with a faster local disk for a sample with 120 million sites. Internally we have run aggregation over 1 billion sites with 50 billion per-read calls and get speeds in the range of 5-50k positions processed per second. I know that we see speeds like this over network mounted disks, but I have not tested the difference between SSD and HDD.

Note that the next release will address some of these issues with some updates to the database scheme (and remove the laggy start to processing).

**Comment by XINYAN2** [comment]
It's an SSD disk. I ran megalodon successfully once before with same machine and same local disk without setting "--database-safety 0". However, it exited with an error like "can not read database"  when I tried to run it second time. After I set "--database-safety 0 --mod-database-timeout 30" according to log file, the aggregation became this slow.

**Comment by XINYAN2** [comment]
I think i know the reason. It's not the problem of disk. I think it's indexing. Although it showed that indexing finished successfully, it's actually not. I re-indexed the database and the aggregation is normal now.

**Comment by marcus1487** [comment]
Ah. Yes I have noticed this happening from time to time as well. The next release will include a check that the index was created successfully both after the attempted index creation, as well as before attempting any aggregation steps. Sorry for this inconvenience!

**Comment by marcus1487** [comment]
In the 2.2 release the index is now checked for before aggregation can start. Additionally, a new `megalodon_extras modified_bases index_database` command has been added to assist in this process.
