### ISSUE TITLE
Installation Confusion

### ISSUE THREAD

**Issue by ruicatxiao** [nanoporetech/megalodon#41]
Hi dev team of Megalodon,

I am a bit confused as for what other components are needed for most up to date megalodon to function properly. My goal is to have 5mC in all sequence context. Currently our cluster have Guppy 4.0.11 installed. Should I be installing Rerio before installation of Megalodon? Or would Megalodon include the said trained model already? The documentation page did not explain it very clearly. Can you explain it a bit clear?

A). Just install this and it will work
B). Need Guppy to be installed first
C). Need Rerio to be installed first

Which one is it?

**Comment by marcus1487** [comment]
Guppy must be installed to run Megalodon (for the most part; the Taiyaki or FAST5 backends can be used, but this is discouraged for most all users). Rerio must be downloaded if one wishes to use the most current research basecalling models.

I'm not sure if this is an "order of operations" question, but the order of installing Guppy, Rerio and Megalodon does not matter.

One final note is that Megalodon has only preliminary support for guppy 4.0+ at the moment. This change involved a change to the server client interface and this has not been fully tested in Megalodon at this point. See the README for further instructions for compatibility with Guppy 4.0+. Also note that the pyguppyclient also has a pre-release with Guppy 4.0 support that may work as well. For stable support I would recommend using Guppy 3.6.1.

**Comment by ruicatxiao** [comment]
I see. So Guppy is the back end, Rerio provides the trained basemod files, megalodon operates as central hub for modification calling and aggregation? 

Is there currently a time frame for supporting Guppy V4 in the next release of megalodon?

Thanks!

**Comment by marcus1487** [comment]
Yes that is a good summary of the functionality for each package.

There is not currently a time frame to switch to Guppy 4.0 support. Once the new pyguppyclient package is released Megalodon should work with Guppy 4.0, but this may not be fully tested until after the next release.

**Comment by ruicatxiao** [comment]
Understood. All questions solved!

**Comment by marcus1487** [comment]
With the 2.2 release, Megalodon now requires (and thus obviously supports) Guppy version >=4.0. Error messages concerning the guppy version should be more useful with this release.
