### ISSUE TITLE
using amplified cDNA reads as control for genomic reads?

### ISSUE THREAD

**Issue by michieitel** [nanoporetech/megalodon#48]
Hi!

This is more a consideration rather than an issue.
I am wondering if it would be possible to use nanopore cDNA reads and compare the output of megalodon with the genomic reads to identify possibly false positive bases (for coding regions). I do not have a set of amplified genomic reads to use for this purpose. Would the current megalodon pipeline work with transcripts or will an adjustment have to made in the mapping step (mappy part of the code)?

Best
Michael

**Comment by marcus1487** [comment]
Megalodon does not currently support spliced mappings. The conversion to spliced mapping settings (via mappy) are quite trivial, but handling spliced mappings downstream is much more complicated. Namely the splice junctions would have to be taken as ground truth. Adjustments to the splice junctions explicitly would not be allowed in the downstream Megalodon steps for sequence variant detection. Thus for transcript processing Megalodon currently requires a transcript reference to process spliced transcript reads.

As for a solution here, I am not exactly sure what is the goal? What do you mean exactly by "false positive bases"? How would the native genomic sample be used in this setting?

**Comment by marcus1487** [comment]
More information is needed to accurately address this issue. Re-open this issue if such information can be provided.
