### ISSUE TITLE
Megalodon 2.2 Performance and Updated per_read_modified_base_calls database schema

### ISSUE THREAD

**Issue by AAnnan** [nanoporetech/megalodon#49]
Hello,

Thank you for this new release of Megalodon. I've been doing some testing and I have 2 issues with it so far:

1) The read-processing performance went from ~**28** reads/s (Megalodon 2.1 w/ Guppy 4.0.14) to ~**9** reads/s (Megalodon 2.2 w/ Guppy 4.0.15), for the same outputs requested. 
I tried applying the recommended Guppy params `--num_callers 5 --ipc_threads 6` and even increasing the `--gpu_runners_per_device` but performance was not better. GPUs are 2x GeForce RTX 2080ti.

2) The `per_read_modified_base_calls.db` file doesn't contain the `mod` table anymore. Therefore, when calling multiple motifs (see Megalodon command), there is no way to know which motif was present at which position. Motif-dependent strand offset cannot be applied when performing downstream analysis. A solution would be to run Megalodon 1 time per motif and then add the offset when merging the outputs, but this would be quite inefficient... A new `megolodon_extras` script proposes to merge databases, is there one to split them?

#### Megalodon 2.2 Command:
```
megalodon ./final_fast5s/ --guppy-server-path ${GUPPY_DIR}/guppy_basecall_server \
        --guppy-params "-d ./rerio/basecall_models/ --num_callers 5 --ipc_threads 6" \
        --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg \
        --outputs basecalls mappings mods per_read_mods mod_mappings \
        --output-directory ./res_mega \
        --reference $genomeFile \
        --sort-mappings \
        --mod-motif Z GCG 1 --mod-motif Z HCG 1 --mod-motif Z GCH 1 \
        --write-mods-text \
        --mod-aggregate-method binary_threshold \
        --mod-binary-threshold 0.7 \
        --mod-output-formats bedmethyl wiggle \
        --mod-map-emulate-bisulfite \
        --mod-map-base-conv C T --mod-map-base-conv Z C \
        --devices 0 --processes 30 
```

#### Megalodon 2.1 Command:
```
megalodon ./final_fast5s/ --guppy-server-path ${GUPPY_DIR}/guppy_basecall_server \
        --guppy-params "-d ./rerio/basecall_models/" \
        --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg \
        --outputs basecalls mappings mods per_read_mods mod_mappings \
        --output-directory ./megalodon_results \
        --reference $genomeFile \
        --mod-motif Z GCG 1 --mod-motif Z HCG 1 --mod-motif Z GCH 1 \
        --write-mods-text \
        --mod-aggregate-method binary_threshold \
        --mod-binary-threshold 0.7 \
        --mod-output-formats bedmethyl wiggle \
        --mod-map-base-conv C T --mod-map-base-conv Z C \
        --devices 0 --processes 30
```

**Comment by AAnnan** [comment]
Hi Marcus,

The output queues are not full, no.

[read_processing.prof.zip](https://github.com/nanoporetech/megalodon/files/5116409/read_processing.prof.zip)

**Comment by AAnnan** [comment]
I didn't catch that before but `per_read_modified_base_calls.db` doesn't carry strand information so setting a strand-specific offset on positions is difficult.

**Comment by marcus1487** [comment]
The profiling shows as, I would expect, that the vast majority of the processing time (~70%) is spent being waiting for the basecaller to return the results. This unfortunately doesn't give me much of a clue as to why this version would be slower. I will be looking into settings to optimize the Megalodon/Guppy interface. Do you see the same performance without the added guppy options (`--num_callers 5 --ipc_threads 6`)? I.e. when running the two versions with the exact same settings.

For the decoding [here is the function in the code that performs this conversion](https://github.com/nanoporetech/megalodon/blob/2.2.0/megalodon/mods.py#L312). As you can see there the `strand = pos_id % 2`. This was part of the optimization that removes a database lookup in order to compute position IDs for storage (and has the upside that the indexed data table is in genome sorted order).

**Comment by AAnnan** [comment]
`--num_callers 5 --ipc_threads 6` don't seem to contribute very much to the speed of my runs. I tried with and without with v2.2 and with v2.1.1. Same goes with using 2 GPUs `--devices 0 1` vs only 1 GPU.

Thank you for the conversion method, I like this way of storing this information!

**Comment by marcus1487** [comment]
I am looking into a new read batching method. This will hopefully provide more robust performance across a range of compute environments.

**Comment by marcus1487** [comment]
I've just pushed a branch with this new read batching scheme. I've not merged into master yet as further testing is required, but hope to merge this into master shortly and address this issue more robustly.

@AAnnan , if you have a chance to test this out that would be great! Install this new branch with the command: `pip install git+https://github.com/nanoporetech/megalodon@batch_reads`. I hope that this will provide more robust performance across system and parameter settings.

Note that the `--processes` argument should generally be much lower than may have been optimal in the current master (or 2.1 release). In this new branch each worker process sends a batch (default `50` reads; set with new `--reads-per-guppy-batch` argument) of reads to the guppy server and processes the results as they are returned within the batch. As such 50 times more reads are sent to guppy at a time in this branch than in current master with the same arguments, which can quickly overwhelm the guppy server with too many worker processes.

Also note that this does not solve the slower performance on single FAST5 inputs. This will be fixed in a future release.

**Comment by AAnnan** [comment]
It worked! 

I tested this new branch with 10000 reads of the same dataset and with the same Megalodon parameters as my original post, changing only the input single fast5s to multi. I obtained the best performance with `--processes 8`: **48** reads/s. During this run, the input queue was filling up slowly.

Increasing the number of processes above 8 only slightly decreased performance (down to ~43 reads/s @ 30 processes). In those runs, the input queues tended to be left empty.

In all runs, the output queues stayed almost completely empty.

This branch's increase in performance is great, still, I'm left wondering if Megalodon takes full advantage of the resources present in the machine. It would be nice to have some small piece of documentation, or simply some guidelines on how to adjust Megalodon's resource parameters to obtain the best running performance on a given machine.

Thank you @marcus1487

**Comment by marcus1487** [comment]
I'm glad this branch addressed most of the lag compared to expected performance improvements. The fact that the input queue remains empty in your 30 process run indicates that raw signal input is still a bottleneck. I have designed this solution (adding multithreading to the input processes), but have yet to implement this.

I agree that a section explaining useful parameters to optimize in the documentation/README would be very helpful. This was my note concerning the need for documentation before merging this branch into master (along with a version bump). I have been working through the bottlenecks my self and figuring out what parameters are useful to adjust for performance. I will include such a section in the next release.

Thank you so much for the quick turnaround on beta testing the new branch. This is much appreciated!

**Comment by marcus1487** [comment]
The threaded read enumeration and signal extraction has now been added to the `batch_reads` branch. Re-installation with the same `pip` command as above will update megalodon. I would be interested to see how well this branch performs both on the single read FAST5s on your (@AAnnan ) system as well as if you see improvement in performance at the higher number of processes (where you were seeing the empty input queue with the last version of this branch).

Note that this threading introduces a new command line arg `--num-read-enumeration-threads`. This is set to a default of 8. If you still see an empty input queue I would be interested to see if increasing this argument helps performance (and is able to saturate the input queue).

I am hoping to finish up the documentation for these features either tomorrow or early next week and merge this into master for a new release. I look forward to your experience with these updates.

**Comment by marcus1487** [comment]
This batch_reads update has now been merged into master and released as version 2.2.1.

**Comment by AAnnan** [comment]
Hello @marcus1487,

I apologize for replying so late. 
I got around to testing the Chum release. I installed megalodon via `pip3 install Megalodon` and like my previous tests, I ran it on the same fast5s with the same command:
```
megalodon ./final_fast5s/ --guppy-server-path ${GUPPY_DIR}/guppy_basecall_server \
        --guppy-params "-d ./rerio/basecall_models/ --num_callers 5 --ipc_threads 6" \
        --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg \
        --outputs basecalls mappings mods per_read_mods mod_mappings \
        --output-directory ./res_mega \
        --reference $genomeFile \
        --sort-mappings \
        --mod-motif Z GCG 1 --mod-motif Z HCG 1 --mod-motif Z GCH 1 \
        --write-mods-text \
        --mod-aggregate-method binary_threshold \
        --mod-binary-threshold 0.7 \
        --mod-output-formats bedmethyl wiggle \
        --mod-map-emulate-bisulfite \
        --mod-map-base-conv C T --mod-map-base-conv Z C \
        --devices 0 --processes 30 \
        --num-reads 10000
```
Testing involved 4 states: changing the input format from single to multi and the `--processes` from 30 to 8:

- multiFast5s

30 processes: 60 reads/s with some Guppy errors in the standard output (Pyguppy:result.failed & Guppy server timeout)
8 processes: 50 reads/s with less errors (Pyguppy:result.failed only)
These errors appear just after the usual "No alignment" ones and seem to occur more in the very beginning of the run. See attached `mega_multiF5_err.txt` for exact wording on the errors. 
[mega_multiF5_err.txt](https://github.com/nanoporetech/megalodon/files/5193663/mega_multiF5_err.txt)

Additionally, for both runs the number of reads planned for processing, shown in the standard output, was 30000 and not 10000, as specified by the `--num-reads` command.

- singleFast5s 

30 processes & 8 processes: Read processing did not start. Not output beside logs. The standard output and the output directory are attached (from the 30 processes run, but 8 processes was the same).
[mega_singF5_out.txt](https://github.com/nanoporetech/megalodon/files/5193664/mega_singF5_out.txt)
[mega_singF5_outDir.zip](https://github.com/nanoporetech/megalodon/files/5193665/mega_singF5_outDir.zip)

**Comment by AAnnan** [comment]
A couple of unrelated question that I'd love to have the answers to:

1) You mentioned in another issue I opened that a new Rerio model was in the works for All-Context 5mC. Is it possible to have an approximate ETA on this? Official or not...

2) I tried calling the methylations on a fully 6mA methylated (EcoGII) genomic DNA sample with `res_dna_r941_min_modbases-all-context_v001.cfg` but got very poor results when I compared it to a negative control. Might the model be the cause for this or should it be as good as all-context 5mC calling? It is also possible that the concentration of EcoGII enzyme used to methylate the gDNA was too low.

**Comment by marcus1487** [comment]
First, thank you so much for the detailed benchmarking and metrics! This is much appreciated!

The `--num-reads` behavior is a bug. I have just pushed a branch (`fix_num_reads`) with a fix for this and include in the next release.

The pyguppy and timeout errors indicate that the guppy server is overloaded. Adjusting the `--processes` and/or `--reads-per-guppy-batch` may help here (default is `50`). I've attempted to add some docs to this effect [here in the README](https://github.com/nanoporetech/megalodon#disk-performance-considerations). Do let me know if further clarifications here would be helpful. The combination of `--processes` and `--reads-per-guppy-batch` are the most likely parameters which may be adjusted to achieve optimal performance on a given environment (especially when specifying multiple `--devices`).

For the hanging single read FAST5s runs, I have seen h5py hang previously under certain settings. I am not able to replicate this behavior on our servers (even setting `--num-read-enumeration-threads 64`). Googling around I think this may have to do with either network file systems or system settings concerning the number of files allowed open at once. I would try to lower the `--num-read-enumeration-threads` for these runs, though I would guess that processing speed will be severely limited when processing single read fast5 files.

For updated to all-context 5mC model in Rerio, I unfortunately don't have an approximate ETA for this.

For the final question regarding fully methylated genomic DNA, this may be an issue with the model in a sense. The model was not trained from completely modified samples. Completely modified samples tend to change the nature of the signal (e.g. the signal normalization). The all context model is aimed at picking out modified bases at biologically relevant concentrations. It may be possible to train a model to detect higher concentrations of 6mA or other bases, but that is not the aim of the released model. Creating a very good ground truth with the full range of modified base concentrations in all/most contexts would be the barrier towards training such a model. Internally, testing 6mA detection with this model from biological samples performs reasonably well (per-read F1-scores in the range 0.75-0.9).

**Comment by AAnnan** [comment]
Hi Marcus,

Lowering `--processes` and/or `--reads-per-guppy-batch` got rid of most pyguppy and timeout errors. I found that with my current data sample, setting `--processes` to `8` and `--reads-per-guppy-batch` to `40` got rid of read drops entirely while retaining good performance (47r/s)

For single read Fast5s, there was nothing I could change that would make the run actually start.

Thanks for your answers on the models.
