### ISSUE TITLE
How many alignments from a read are used?

### ISSUE THREAD

**Issue by drfultz** [nanoporetech/megalodon#5]
By default minimap2 can generate secondary as well as supplementary alignments for each read.  Which alignments are used for variant and modification calling?  I'm guessing only the primary?

As a related question, is there any way to alter the minimap2 mapping parameters within a megalodon run?

Thanks!

**Comment by marcus1487** [comment]
Only the primary mapping is used currently. There is not a way to change the mapping parameters from the command line, but you could change them within the code [here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/megalodon.py#L566). This would require either reinstalling or an installation via `pip install -e`.

**Comment by drfultz** [comment]
Great, thanks for the answer!
