### ISSUE TITLE
Install issue: Could not find a version that satisfies the requirement ont-pyguppy-client-lib

### ISSUE THREAD

**Issue by zshipony** [nanoporetech/megalodon#51]
When trying to upgrade to the new Megalodon (V2.2) I receive the following message:
  Could not find a version that satisfies the requirement ont-pyguppy-client-lib (from megalodon) (from versions: )
No matching distribution found for ont-pyguppy-client-lib (from megalodon)

**Comment by techsavy12** [comment]
I'm trying to download Megalodon and I receive a similar error [Could not find a version that satisfies the requirement ont_pyguppy_client_lib (from versions: ) No matching distribution found for ont_pyguppy_client_lib]

**Comment by marcus1487** [comment]
On what systems are you trying to install megalodon? The ont_pyguppy_client_lib should have releases for all python versions from 3.5-3.8 on Linux, OS X and windows.

**Comment by zshipony** [comment]
Hey Marcus,

Thanks for trying to help,

I am installing on 
CentOS Linux release 7.6.1810 (Core)
Python 3.6.1

**Comment by fbrennen** [comment]
Hi @zshipony -- what version of pip are you using? (`pip --version`)

You'll need at least version 19.0 in order to install `ont-pyguppy-client-lib`.

You can upgrade your version of pip with `pip install --upgrade pip`.

**Comment by zshipony** [comment]
@fbrennen Thanks for the help! This solved the problem

**Comment by tonperre** [comment]
Hi, I'm very rookie to this but I'm facing an issue.
Background : I have bam and mod base bam files from Megalodon that I need to convert to a more "ready to use" format. I did not use Megalodon before, the files were provided by a third-person. 
Problem : I'm trying to install Megalodon on my system to convert those files.

I have the error described although having :
Ubuntu 18.04
Python 3.6.9
Pip3 9.0.1

The error thrown is the same as described in the topic : 
`Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting ont-pyguppy-client-lib (from megalodon)  
Could not find a version that satisfies the requirement ont-pyguppy-client-lib (from megalodon) (from versions: )                                                                                                 No matching distribution found for ont-pyguppy-client-lib (from megalodon)`

Extra info : I can't access for now the resources to install guppy, but as I am not willing to base call for now, I thought I could install without Guppy.

How can I circumvent the issue?
If Guppy is necessary, how can I download it without being for now "fully" registered on ONT resources center?

Thanks a lot Marcus !

**Comment by tonperre** [comment]
> Hi, I'm very rookie to this but I'm facing an issue.
> Background : I have bam and mod base bam files from Megalodon that I need to convert to a more "ready to use" format. I did not use Megalodon before, the files were provided by a third-person.
> Problem : I'm trying to install Megalodon on my system to convert those files.
> 
> I have the error described although having :
> Ubuntu 18.04
> Python 3.6.9
> Pip3 9.0.1
> 
> The error thrown is the same as described in the topic :
> `Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl Collecting ont-pyguppy-client-lib (from megalodon) Could not find a version that satisfies the requirement ont-pyguppy-client-lib (from megalodon) (from versions: ) No matching distribution found for ont-pyguppy-client-lib (from megalodon)`
> 
> Extra info : I can't access for now the resources to install guppy, but as I am not willing to base call for now, I thought I could install without Guppy.
> 
> How can I circumvent the issue?
> If Guppy is necessary, how can I download it without being for now "fully" registered on ONT resources center?
> 
> Thanks a lot Marcus !

I actually solved it using 
`python3 -m pip install megalodon`

The issue that I have now is that I need to use python3 -m megalodon.
A simple alias should do the job or is there any drawbacks to this approach?
