### ISSUE TITLE
Guppy basecall server unavailable

### ISSUE THREAD

**Issue by esteinig** [nanoporetech/megalodon#57]
Hi Marcus,

I am attempting to run the latest release but for some reason the server is flagged as unavailable. Server command runs fine independently.

Server log output is uninformative:

```
config file:         /opt/ont/guppy/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
model file:          /opt/ont/guppy/data/template_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.jsn
log path:            test_guppy/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:
runners per device:  4

2020-09-23 06:44:00.166002 [guppy/info] crashpad_handler not supported on this platform.
2020-09-23 06:44:00.167041 [guppy/info] Listening on port 36729.
2020-09-23 06:44:00.257901 [guppy/info] CUDA device 0 (compute 6.1) initialised, memory limit 11718361088B (7645888512B free)

2020-09-23 06:44:02.136483 [guppy/message] Starting server on port: 36729
```

`Guppy` is the latest version (4.2.2+effbaf84), models are available, test files are normal and work for standard basecalling with Guppy. Occurs inside and outside `Docker` container. Setting manual port also does not help.

Megalodon log output:

```
DBG 06:44:00 : Command: """/opt/conda/bin/megalodon --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server --output-directory test_guppy --outputs variants --reference jdk.fasta --haploid --variant-filename core.vcf --devices 0 --processes 12 --guppy-config dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg f5""" --- MainProcess-MainThread megalodon.py:1215
[06:44:00] Loading guppy basecalling backend
DBG 06:44:00 : guppy server init command: "/opt/ont/guppy/bin/guppy_basecall_server -p auto -l test_guppy/guppy_log -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --post_out -x cuda:0" --- MainProcess-MainThread backends.py:529
****************************************************************************************************
        ERROR: Error connecting to Guppy server. Server unavailable.
****************************************************************************************************
```

Any ideas? Is there perhaps an option for debugging to see where it goes wrong? Many thanks!

**Comment by esteinig** [comment]
I see this is an exception raised on connecting to the `PyGuppyClient` - I installed Megalodon via `Conda` and `pip install ont_pyguppy_client_lib` (v4.0.15) via `PyPI` if that helps.

**Comment by rfinkers** [comment]
I do have the same issue/reports reported by @esteinig with guppy 4.2.2. in combination with megalodon 2.2.2 (conda install, with pip install for the client).

`
[10:52:04] Loading guppy basecalling backend
DBG 10:52:04 : guppy server init command: "/usr/bin/guppy_basecall_server -p auto -l megalodon_results/guppy_log -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --post_out -x cuda:0" --- MainProcess-MainThread backends.py:529
****************************************************************************************************
        ERROR: Error connecting to Guppy server. Server unavailable.
****************************************************************************************************
`

**Comment by esteinig** [comment]
Minimal example for reproducible Docker image (not tested sorry will do later)

```dockerfile
# (NVIDIA GPU drivers > v440)
FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04  

ARG MINICONDA_VERSION=latest

ENV PATH /opt/conda/bin:/opt/ont/guppy/bin:$PATH

RUN apt-get update && apt-get install -y wget lsb-release

RUN export PLATFORM=$(lsb_release -cs) && \
    wget -O- https://mirror.oxfordnanoportal.com/apt/ont-repo.pub | apt-key add - && \
    echo "deb http://mirror.oxfordnanoportal.com/apt ${PLATFORM}-stable non-free" | tee /etc/apt/sources.list.d/nanoporetech.sources.list

RUN apt-get update && apt install ont-guppy -y --no-install-recommends

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN conda install -c conda-forge -c bioconda -c defaults --yes megalodon=2.2.2
RUN pip install ont_pyguppy_client_lib




```

**Comment by marcus1487** [comment]
This new version of Guppy was just released yesterday. The python interface to communicate with Guppy must match the same version as Guppy. There was a delay in the release of the associated python interface. This is being remedied at the moment. This new version should resolve this issue.

As a workaround installing Guppy 4.0.15 (to match the current `ont_pyguppy_client_lib` release) should also resolve this issue.

I will also try to add an explicit check that these versions match to give a more useful error message in the future.

**Comment by esteinig** [comment]
Thanks for the quick reply, that makes total sense! I'll close this issue for now.
