### ISSUE TITLE
High number of unexpected errors; mod_mappings blank

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/megalodon#58]
I'm running Megalodon 2.2 with the default model and Guppy 4.0.15 and am getting a large number of "Unexpected Errors". Basically, I'm getting reads in mappings.bam (reads are mapped) and basecalls.fastq, but mod_mappings.bam remains blank.

My command:

`nohup nice megalodon ./fast5 --guppy-server-path /mnt/ix2/Experimental_tools/ont-guppy_4.0.15/ont-guppy/bin/guppy_basecall_server --outputs basecalls mappings mod_mappings mods --reference /mnt/ix1/Resources/GenomeRef/Homo_sapiens/Ensembl/GRCh38_no_alt/Sequence/WholeGenomeFasta/hs38_naa.fna --mod-motif Z CG 0 --devices 0 1 2 --processes 40 --samtools-executable /mnt/ix1/Resources/tools/samtools/v1.10/samtools --output-directory ./megalodon2/ &`

The unexpected error log shows:

`./fast5/FAL01283_36c8477dbfb44575c0d1cc063920d2dea85e131c_481.fast5:::163af7dd-b8ec-4350-bd94-7e6b386d7f58
:::
Traceback (most recent call last):
  File "/mnt/ix2/Experimental_tools/megalodon/megalodon/megalodon.py", line 108, in handle_errors
    out_q.put((func(*args), r_vals))
  File "/mnt/ix2/Experimental_tools/megalodon/megalodon/mods.py", line 1220, in call_read_mods
    sig_map_res.ref_out_info.per_site_threshs is not None:
AttributeError: 'NoneType' object has no attribute 'ref_out_info'`

`cat nohup.out 
[21:09:26] Loading guppy basecalling backend  0%|          | 0/10000
[21:09:30] Loading referencead_mods       :   0%|          | 0/10000
******************** WARNING: Adding "per_read_mods" to --outputs since "mod_mappings" was requested. ********************
[21:11:11] Using canonical alphabet ACGT and modified bases Y=6mA (alt to A); Z=5mC (alt to C)
[21:11:11] Preparing workers to process reads
[21:11:31] Processing reads
Full output or empty input queues indicate I/O bottleneck
3 most common unsuccessful processing stages:
    70.2% ( 654341 reads) : Unexpected error                         
    29.8% ( 278183 reads) : No alignment                                                                    
    -----
Read Processing:   4%|▍         | 960080/22184316 [24:29<9:01:17, 653.50reads/s, samples/s=2.48e+6]
 input queue capacity extract_signal      : 100%|█████████▉| 9998/10000 
output queue capacity basecalls           :   0%|          | 31/10000
output queue capacity mappings            :   0%|          | 24/10000
output queue capacity per_read_mods       :   0%|          | 0/10000`

My environment: 
# packages in environment at /home/billylau/.conda/envs/megalodon2:
#
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2020.7.22                     0  
certifi                   2018.8.24                py35_1  
cycler                    0.10.0                    <pip>
cython                    0.28.5           py35hf484d3e_0  
h5py                      2.10.0                    <pip>
intel-openmp              2020.2                      254  
joblib                    0.14.1                    <pip>
kiwisolver                1.1.0                     <pip>
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
mappy                     2.17                      <pip>
matplotlib                3.0.3                     <pip>
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py35h7dd41cf_0  
mkl_random                1.0.1            py35h4414c95_1  
ncurses                   6.2                  he6710b0_1  
numpy                     1.15.2           py35h1d66e8a_0  
numpy-base                1.15.2           py35h81de0dd_0  
ont-fast5-api             3.1.6                     <pip>
ont-pyguppy-client-lib    4.0.15                    <pip>
openssl                   1.0.2u               h7b6447c_0  
packaging                 20.4                      <pip>
pandas                    0.25.3                    <pip>
pip                       10.0.1                   py35_0  
pip                       20.2.3                    <pip>
progressbar33             2.4                       <pip>
pyparsing                 2.4.7                     <pip>
pysam                     0.16.0.1                  <pip>
python                    3.5.6                hc3d631a_0  
python-dateutil           2.8.1                     <pip>
pytz                      2020.1                    <pip>
readline                  7.0                  h7b6447c_5  
scikit-learn              0.22.2.post1              <pip>
scipy                     1.4.1                     <pip>
seaborn                   0.9.1                     <pip>
setuptools                40.2.0                   py35_0  
sklearn                   0.0                       <pip>
sqlite                    3.33.0               h62c20be_0  
tbb                       2020.3               hfd86e86_0  
tbb4py                    2018.0.5         py35h6bb024c_0  
tk                        8.6.10               hbc83047_0  
tqdm                      4.49.0                    <pip>
wheel                     0.35.1                     py_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3

**Comment by billytcl** [comment]
Any comments on this?

I ran plain guppy (4.2.2) with methylation calling on the fast5s and it's calling methylated bases alongside alignment with --align_ref. So I'm guessing something is weird with how megalodon is handling the reads.

**Comment by marcus1487** [comment]
Yes. This is a bug. I am currently testing the fix. I hope to have a point release pushed later today.

**Comment by billytcl** [comment]
Looking forward to it!!

**Comment by marcus1487** [comment]
The 2.2.3 release should fix this issue (up on pypi and github; conda shortly). Please re-open this issue if this issue persists.
