### ISSUE TITLE
Guppy server init failed, unexpected option '-p' found on command line

### ISSUE THREAD

**Issue by walexandertsu** [nanoporetech/megalodon#59]
Hi there,
I am new to Megalodon, and just 15 minutes ago I installed the software via pip. When I tried to fire up Megalodon, I got the Guppy server initialization failed error. Looking at guppy_log.err:
`Unexpected option '-p' found on command line.
Missing required option 'save_path'.`

I then replicated this by pasting the init command from the log.txt directly into my Terminal, and it threw the same error. Any thoughts as to what is causing this error?

**Comment by walexandertsu** [comment]
The exact command is as follows:
`megalodon --guppy-config dna_r9.4.1_450bps_hac.cfg --guppy-server-path /usr/bin/guppy_basecaller --guppy-params "--chunks_per_caller 950 --num_callers 4 --trim_strategy 'none'" --outputs basecalls mappings --reference path/to/reference.fasta --processes 15 --devices 0:99% --output-directory /path/to/output_dir /path/to/fast5_files --overwrite`

**Comment by marcus1487** [comment]
The `—guppy-server-path` option should point to the `gupper_basecall_server` executable, not the `guppy_basecaller` executable.
