### ISSUE TITLE
Ploidy

### ISSUE THREAD

**Issue by fbemm** [nanoporetech/megalodon#6]
Is Megadolon able to call variants/modifications for heterozygot sites?

Thx,
F

**Comment by marcus1487** [comment]
Yes. Megalodon can be run in either haploid or diploid mode. But the best diploid results would be achieved using the phasing pipeline. See details in the documentation [here](https://nanoporetech.github.io/megalodon/variant_phasing.html).

**Comment by fbemm** [comment]
Great!
