### ISSUE TITLE
BasecallingFailed Guppy server timeout 

### ISSUE THREAD

**Issue by ligiamateiu** [nanoporetech/megalodon#60]
It seems there is a kind of jamming of the input reads in the basecaller. I ran out of ideas what to try. I'm using megalodon 2.2.3 (the same issue was in 2.2.2 as well) 
I do get reads in the output files until the input queue capacity extract_signal becomes 100%. Then also the timeout error. 

The latest command I'm using is 
/bin/megalodon fast5 --outputs basecalls mappings \
    --reference hg38.fa \
    --guppy-config dna_r9.4.1_450bps_hac_prom.cfg \
    --output-directory  megalodon_output \
    --guppy-server-path /bin/guppy_basecall_server \
    --reads-per-guppy-batch 10 \
    --mappings-format bam \
    --sort-mappings --samtools-executable /opt/software/miniconda_rnaseq/bin/samtools \
    --processes 2 --overwrite

(Running guppy_basecaller directly it's working fine. )

![screenshot_megalodon](https://user-images.githubusercontent.com/33923971/94937968-8ff77500-04d0-11eb-8a24-b7808856181c.png)

![screenshot_out](https://user-images.githubusercontent.com/33923971/94938092-b1f0f780-04d0-11eb-8473-6af856559c48.png)

**Comment by marcus1487** [comment]
Running megalodon on CPU compute resources is much slower than GPU (as would be specified via `—devices`). The defaults in megalodon are set for GPU settings. 

As noted in the error message, the `—guppy-timeout` option would be the most straightforward to adjust here. This value should likely be 5-10 times higher than the default on CPU resources. See more details about other arguments to adjust in the README here https://github.com/nanoporetech/megalodon#guppy-models-and-parameters .

**Comment by ligiamateiu** [comment]
Thanks for the quick response! It is clearly not meant to be run on CPUs. It is very slow and eventually the same problem occurs after 3-4 hours of running. I gathered only a few MB of aligned reads so far.
