### ISSUE TITLE
0 reads during processing but goes to 'completion'

### ISSUE THREAD

**Issue by mollybrothers** [nanoporetech/megalodon#62]
Hello! Trying out Megalodon for the first time (trying it alongside tombo!). Having trouble, but not sure where the problem is.

Call was for a subset of reads, just 4000 to test it out:

`megalodon raw_data/multifast5s --output-directory megalodon_outputv0 --reference genomes/genome.fa --outputs basecalls mod_basecalls mappings per_read_mods mods --mod-motif Y A 0 --write-mods-text --processes 4 --devices 0 1 --num-reads 4000`

It seems like it's not finding any reads, but maybe I'm not reading the output right. Any idea what's going on? There are definitely multi-fast5 files in the input directory and they definitely have reads in them!

`[17:58:55] Loading guppy basecalling backend
[17:59:07] Loading reference
[17:59:08] Using canonical alphabet ACGT and modified bases Y=6mA (alt to A); Z=5mC (alt to C)
[17:59:08] Preparing workers to process reads
[17:59:09] Processing reads
Full output or empty input queues indicate I/O bottleneck
3 most common unsuccessful processing stages:
    -----
    -----
    -----

Read Processing: 0reads [00:00, ?reads/s]

input queue capacity extract_signal      :   0%|          | 0/10000

output queue capacity basecalls           :   0%|          | 0/10000

output queue capacity mappings            :   0%|          | 0/10000

output queue capacity per_read_mods       :   0%|          | 0/10000  
    -----
    -----
    -----
Read Processing: 0reads [00:01, ?reads/s]
 input queue capacity extract_signal      :   0%|          | 0/10000
output queue capacity basecalls           :   0%|          | 0/10000
output queue capacity mappings            :   0%|          | 0/10000
output queue capacity per_read_mods       :   0%|          | 0/10000
[17:59:10] All reads processed successfully
[17:59:10] Spawning modified base aggregation processes
******************** WARNING: No per-read variants or modified base statistics found for aggregation. ********************
[17:59:10] Mega Done
`

**Comment by mollybrothers** [comment]
I also tried this same call but with --num-reads 50000 to see if that was an issue but I got the same output.

Thank you!

**Comment by marcus1487** [comment]
This usually means that megalodon is not finding any reads in the input directory. The log file in the output directory should contain some information about how the search for reads proceeded. Could you post the log file here?

**Comment by marcus1487** [comment]
P.S. I would recommend looking at the all context 6mA model in the [Rerio respository](https://github.com/nanoporetech/rerio) for the best all context 6mA results.

**Comment by mollybrothers** [comment]
Hi Marcus, thanks for the Rerio tip. I'll definitely check it out. I've attached the log and guppy_log in the output folder (guppy didn't throw any errors so I didn't attach that here)

[log.txt](https://github.com/nanoporetech/megalodon/files/5375416/log.txt)

[guppy_log.txt](https://github.com/nanoporetech/megalodon/files/5375425/guppy_log.txt)

**Comment by mollybrothers** [comment]
Will update again soon – all of the reads are in the fast5 files but there is no signal for any of them, which is clearly the current issue. Haven't run into this one before...

**Comment by marcus1487** [comment]
It looks like Megalodon is not finding any fast5 files. In the log file you’ll note the line stating: `Found 0 total FAST5 files`. By default Megalodon searches recursively for files ending in `.fast5`. Is it possible that the reads files do not have the standard file extension?

**Comment by mollybrothers** [comment]
I have about 1200 multi fast5 files in the directory all ending with `.fast5`

HDFView showed readIDs and all of the attributes but where there is supposed to be signal data there is nothing.

**Comment by mollybrothers** [comment]
Trying to re-run this morning I'm not having any issues... ran and got all of the output files with data in them.

running your little snippet of code now returns a value of 1225 (but I don't know what it would have returned yesterday).

Not sure what my problem was yesterday, maybe something an 'off and then on again' solved. Thanks for always being quick to help, sorry for whatever this odd mixup was (very likely my fault).
