### ISSUE TITLE
Using bootstrap modified base annotation to train a model

### ISSUE THREAD

**Issue by PengNi** [nanoporetech/megalodon#65]
Hi, 

I have a question that, if I want to train a modified base model, is using only Ground Truth Aided Bootstrap Modified Base Annotation enough? or I should fisrt use Bootstrap Modified Base Annotation (calibration files) to train, and then use Ground Truth Aided Bootstrap Modified Base Annotation to train a second round.

Thanks in advance!

Best,
Peng

**Comment by marcus1487** [comment]
Both the "Bootstrap Modified Base Annotation" and "Ground Truth Aided Bootstrap Modified Base Annotation" require a model which can detect the modified base of interest with some accuracy. So either of these methods requires a first round (or at least an appropriate modified base model to start from). If a ground truth is available, it is recommended to use the ground truth aided method given an initial model. There is no need to train a bootstrap model first. I have not tested whether a three step approach (initial model -> bootstrap model -> ground truth aided bootstrap model) might improve the final performance.

**Comment by PengNi** [comment]
OK, I get it. Thanks for your response!
