### ISSUE TITLE
Identical probabilities in the output

### ISSUE THREAD

**Issue by rrazaghi** [nanoporetech/megalodon#67]
Hi Marcus!

I'm trying the latest version of megalodon on a new run and I am observing identical probability scores in the per_read_modified_base_calls outout:

> cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43956607        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43956991        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43957112        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43957429        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43957621        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43958156        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43958245        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43958385        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43958875        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43958905        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43959575        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43959585        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43960022        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43960413        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43960528        -2.001431069462787      -0.14518965549004856    Y
cd32b824-9c3a-4aad-98ce-d482d415703f    chr7    1       43960723        -2.001431069462787      -0.14518965549004856    Y
94b95218-5e9c-4785-978e-e6e80730bf15    chr12   -1      79536145        -2.001431069462787      -0.14518965549004856    Y
94b95218-5e9c-4785-978e-e6e80730bf15    chr12   -1      79535900        -2.001431069462787      -0.14518965549004856    Y
94b95218-5e9c-4785-978e-e6e80730bf15    chr12   -1      79535795        -2.001431069462787      -0.14518965549004856    Y
94b95218-5e9c-4785-978e-e6e80730bf15    chr12   -1      79535533        -2.001431069462787      -0.14518965549004856    Y
94b95218-5e9c-4785-978e-e6e80730bf15    chr12   -1      79535441        -2.001431069462787      -0.14518965549004856    Y
94b95218-5e9c-4785-978e-e6e80730bf15    chr12   -1      79535065        -2.001431069462787      -0.14518965549004856    Y
94b95218-5e9c-4785-978e-e6e80730bf15    chr12   -1      79533905        -2.001431069462787      -0.14518965549004856    Y
94b95218-5e9c-4785-978e-e6e80730bf15    chr12   -1      79533810        -2.001431069462787      -0.14518965549004856    Y

This seems to be happening with all the calls (I'm still in the middle of the run) and is specific to m6A calls in dam motif. I do not observe similar behavior with the CpG calls however.

This is the megalodon command:

> megalodon $fast5 \
    --overwrite \
    --guppy-server-path $guppy_path \
    --guppy-server-port 5556 \
    --guppy-params "--num_callers 10 --ipc_threads 6" \
    --guppy-timeout 120 \
    --output-directory $outdir \
    --outputs basecalls mappings per_read_mods \
    --write-mods-text \
    --reference $ref \
    --mod-motif Z CG 0 --mod-motif Y GATC 1 --devices 0 --processes 60 \
    --verbose-read-progress 3

Thanks for your help as always!

**Comment by rrazaghi** [comment]
I can confirm however I don't see the same issue with the rerio model!

**Comment by marcus1487** [comment]
This is an issue that results from the combination of model performance and calibration (explained more below). The short answer here is to use the Rerio models. The default modbase models shipped with Guppy are not currently recommended for the best modified base detection.

Megalodon calibration uses a set of ground truth modified and canonical sites from a set of reads. These reads are processed without calibration to take the raw neural network output. These scores are then compared to empirical observations from these two sets of modified base score. In the tails of these distributions the binned fraction of modified bases can be non-monotonic (i.e. more confident neural network modified base score indicates less observed modified bases). Megalodon forces these scores to be monotonic as it does not make sense for a more confident raw score to produce a less confident calibrated score. The code to accomplish this forced monotonicity can be found [here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/calibration.py#L229) (apologies for the lack of comments in this module). 

To help visualize this, see the plots produced by the calibration script for this model [here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/model_data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg/megalodon_mod_calibration.pdf). Note in the bottom facet of the 6mA plot that the right hand side of the plot plateaus. This is from the forced monotonicity (red line before and yellow line after) and is what is causing the fixed single value when the model is quite certain of the canonical call. The yellow line in this plot is what is actually stored in the Megalodon calibration file. Note that this effect does not occur in the calibration of the Rerio model [here](https://github.com/nanoporetech/megalodon/blob/master/megalodon/model_data/res_dna_r941_min_modbases-all-context_v001.cfg/megalodon_mod_calibration.pdf) (though there are clearly other issues there; active area of internal research).

**Comment by rrazaghi** [comment]
Thank you Marcus for the thorough explanation! Those calibration plots are very useful.
