### ISSUE TITLE
AttributeError: 'ModsDb' object has no attribute 'iter_pos' when running megalodon_extras per_read_text modified_bases

### ISSUE THREAD

**Issue by mollybrothers** [nanoporetech/megalodon#68]
Hi Marcus,

After running megalodon and getting a `per_read_modified_base_calls.db`, I was trying to use `megalodon_extras per_read_text modified_bases` to turn that into a `.txt` file, but I got the following error:

`Traceback (most recent call last):
  File "/global/home/users/molly_brothers/.conda/envs/guppy/bin/megalodon_extras", line 11, in <module>
    sys.exit(_main())`
  `File "/global/home/users/molly_brothers/.conda/envs/guppy/lib/python3.7/site-packages/megalodon_extras/__main__.py", line 157, in _main
    module._main(args)`
 ` File "/global/home/users/molly_brothers/.conda/envs/guppy/lib/python3.7/site-packages/megalodon_extras/per_read_text_modified_bases.py", line 18, in _main
    mods_db.iter_pos(), total=mods_db.get_num_uniq_mod_pos(),`
`AttributeError: 'ModsDb' object has no attribute 'iter_pos' `

When I run megalodon with the `--write-mods-text` flag instead of trying to use `megalodon_extras`, I do not run into this problem. Am I missing something? (let me know if I can provide more information)

Thank you!

**Comment by marcus1487** [comment]
This is a bug. This command line function was missed in a recent round of edits to the modified base database API. A fix for this will be included in the next release.

**Comment by marcus1487** [comment]
This should be fixed in the latest release. Please re-open this if this issue persists.
