### ISSUE TITLE
Why: Adding "per_read_mods" to --outputs since "mod_mappings" was requested

### ISSUE THREAD

**Issue by organic-chemistry** [nanoporetech/megalodon#70]
Hello,
I am using megalodon with mod_mappings as I am interested in the bam file produced, however, if I understand correctly it automatically adds the option per_read_mods, that create a .db file with a significant size, a file that I don't use.
Is it possible to prevent the creation of this file?
Best,

**Comment by marcus1487** [comment]
Currently this is not possible. This should be possible to implement in a future version. Originally the modified database object held much of the important information required to process the `mod_mappings` (and other mod outputs). This is likely not the case anymore (or at least could be resolved with less effort than previously). I will look into adding this to the next release.

**Comment by marcus1487** [comment]
This is now implemented in the latest release (2.2.6). If this issue is not fixed, please re-open.

**Comment by organic-chemistry** [comment]
Ok, Thank you very much, I will try it.
Best
