### ISSUE TITLE
UnboundLocalError with modbases model

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/megalodon#77]
Hi,
I am trying to detect CpG methylation with the following command:
```
megalodon \
    `# input reads` \
    ${FAST5_PATH} \
    `# output location + overwrite` \
    --output-directory ${OUTPUT_PATH} \
    --overwrite \
    `# output all the things` \
    --outputs basecalls mod_basecalls mappings \
    per_read_mods mods mod_mappings \
    per_read_refs signal_mappings \
    `# guppy options` \
    --guppy-server-path ${GUPPY_PATH}/guppy_basecall_server \
    --guppy-config ${GUPPY_MOD_CONFIG} \
    `# number of megalodon workers` \
    --processes ${NPROC} \
    `# mapping settings (cram requires FASTA reference)` \
    --sort-mappings \
    --reference ${FASTA_REF} \
    --devices 0 --processes 40 \
    `# modified base settings` \
    --mod-motif Z CG 0    #test only in CpG locations
```
But I got the `UnboundLocalError` with the following information: 
```
[00:12:23] Running Megalodon version 2.2.9
[00:12:23] Loading guppy basecalling backend
[00:12:29] Loading reference
******************** WARNING: Samtools executable not found. Mappings will not be sorted or indexed. ********************
[2020-12-15 00:12:29.443105] [0x00002aaaaaae8e80] [info]    Connecting to server as 
Traceback (most recent call last):
  File "Anaconda3/envs/megalodon/bin/megalodon", line 11, in <module>
    sys.exit(_main())
  File "Anaconda3/envs/megalodon/lib/python3.6/site-packages/megalodon/__main__.py", line 430, in _main
    megalodon._main(args)
  File "Anaconda3/envs/megalodon/lib/python3.6/site-packages/megalodon/megalodon.py", line 1225, in _main
    aligner, map_info = parse_aligner_args(args)
  File "Anaconda3/envs/megalodon/lib/python3.6/site-packages/megalodon/megalodon.py", line 835, in parse_aligner_args
    map_info.test_samtools()
  File "Anaconda3/envs/megalodon/lib/python3.6/site-packages/megalodon/mapping.py", line 169, in test_samtools
    if test_sort_res.returncode != 0:
UnboundLocalError: local variable 'test_sort_res' referenced before assignment
```
Package version: `python==3.6, Megalodon==2.2.9, Guppy==4.4.2`

Can you help me with the issue? Thanks!

**Comment by marcus1487** [comment]
I've pushed a fix for this bug to github. This is not included in a release yet, but you can re-install megalodon with `pip install git+https://github.com/nanoporetech/megalodon/` to work around this issue until the next release. Please re-open if this issue re-occurs.

**Comment by PanZiwei** [comment]
Hi @marcus1487 , 
I have re-install megalodon following your advice but still got the exact same error...Is it because I have to install Samtools also?

**Comment by marcus1487** [comment]
That is the core of the issue. You should now get a warning but processing will continue (but without running sorting which requires samtools).

**Comment by PanZiwei** [comment]
Yeah right now another error occurs:
1. When I use `--mod-motif Z CG 0` statement, I got the error AssertionError like #53 with the mode, saying that `AssertionError: Modified base label (Z) not found in model alphabet (['h', 'm']).`
2. When I use `--mod-motif m 5mC CG 0     --mod-motif h 5hmC CG 0` instead, I got the error:
```
[16:30:50] Using canonical alphabet ACGT and modified bases h=5hmC (alt to C); m=5mC (alt to C)
****************************************************************************************************
	ERROR: One provided motif can be found within another motif. Only distinct sets of motifs are accepted
****************************************************************************************************
```
Then I switched to one motif separately one time and it indeed worked. So it seems that Megalodon can only accept one provided motif at a time? What if I am interested in 5hmC and 5mC at the same time in the model `res_dna_r941_min_modbases_5mC_5hmC_v001.cfg` from rerio?

BTW I would really appreciate it if you can also answer the question about the model also: https://github.com/nanoporetech/rerio/issues/14.

**Comment by marcus1487** [comment]
As noted in the `megalodon --help` description `--mod-motif` should contain three values: 1) the single letter modified base(s), 2) sequence motif and 3) relative modified base position. When processing multiple modified bases (e.g. 5mC and 5hmC) in the same context they should be provided in one `--mod-motif` argument as `--mod-motif mh CG 0`.

I will respond to the Rerio model question shortly.
