### ISSUE TITLE
Issue: --mod-aggregate-method: command not found

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/megalodon#80]
Hello,
Wish you had a nice noliday. Thanks for the new release for Megalodon. I have installed Megalodon v2.2.9 but encountered some problems when using megalodon with the following command:

```
megalodon \
    `# input reads` \
    ${FAST5_PATH} \
    `# output location + overwrite` \
    --output-directory ${OUTPUT_PATH} \
    --overwrite \
    `# output all the things` \
    --outputs basecalls mod_basecalls mappings per_read_mods mods mod_mappings \
    `# guppy options` \
    --guppy-server-path ${GUPPY_PATH}/guppy_basecall_server \
    --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg \
    `# mapping settings (cram requires FASTA reference)` \
    --samtools-executable ${SAMTOOLS_PATH} \
    --sort-mappings \
    --mappings-format bam \
    --reference ${FASTA_REF} \
    --devices 0 --processes ${NPROC} \
    --mod-motif m CG 0 \ 
    --mod-aggregate-method binary_threshold \
    --mod-binary-threshold 0.7 \
    --mod-output-formats bedmethyl wiggle \
    --write-mods-text \
    --write-mod-log-probs
```

I got the error:
```
megalodon: error: unrecognized arguments:   
--mod-aggregate-method: command not found
```

Any idea on the issues? Thank you!

**Comment by marcus1487** [comment]
I'm not able to reproduce this behavior. It looks like the command is somehow trying to use `--mod-aggregate-method` as a command. Or that the megalodon command is not found. Can you describe how megalodon was installed on your system?

**Comment by PanZiwei** [comment]
@marcus1487 ,
Thank you for your reply! I somehow uninstall the current version and install the developed version with git command and the behaviour just disappeared somehow...

I successfully got the modified results with the above command but I still have some questions and would really appreciate it if you can help answer them:

1. Can you explain more on the output results `per_read_modified_base_calls.txt` (See several lines below) generated by megalodon? The `pos` column is 0-based or 1-based? For column `mod_log_prob` and `can_log_prob`, do they show the log probability of the base that is called as modified (`mod_log_prob`) or canonical (`can_log_prob`)? So how do you annotate whether a base as modified or not? What is the  `mod_base` column used for?

```
read_id chrm    strand  pos     mod_log_prob    can_log_prob    mod_base
7c573c97-f52b-4c49-bef6-6265f6e23e69    chr5    -       181086582       -1.0989259872672734     -0.40530829570342086    m
7c573c97-f52b-4c49-bef6-6265f6e23e69    chr5    -       181086564       -0.07531978645197457    -2.6234359368809015     m
7c573c97-f52b-4c49-bef6-6265f6e23e69    chr5    -       181086557       -0.01827896475640456    -4.0111299078689004     m
7c573c97-f52b-4c49-bef6-6265f6e23e69    chr5    -       181086501       -0.013637282015030117   -4.301758804225129      m
```

2. So the Megalodon can do the base calling and modification calling at the same time, instead of the modification calling after base calling like Nanopolish? Does the modified calling results generated by Megalodon comparable with Nanopolish results?

3. Is it possible to get the methylation frequencies at genome level from the read level in this case? 

Thank you so much for your help!

**Comment by marcus1487** [comment]
1) pos is 0-based. `mod_log_prob ` and `can_log_prob` are indeed the log probability that the base is modified or canonical. The `mod_base` column is used for results from multiple modified bases (e.g. 5mC and 5hmC) in the same run. This is also why the modified and canonical probabilities are provided for each record.

2) Yes, in fact Megalodon must perform basecalling and modified base calling at the same time. The idea is that the modified base calling target should be designed from the beginning of an experiment. If basecalling has been completed already it must unfortunately be completed again within Megalodon to produce modified base calls. 

Megalodon has shown superior performance to all other algorithms I am aware of for 5mC CpG detection. I don't believe we have an internal comparison available, but an independent group recently produced an algorithm benchmarking ([link here](https://www.biorxiv.org/content/10.1101/2020.10.14.340315v3.full)). In particular see figure 3 a and b for per-read results.

3) Methylation frequencies at the genome level are available via the `--output mods` option ([docs here](https://nanoporetech.github.io/megalodon/algorithm_details.html#modified-base-calling)). This can also be computed from a completed Megalodon run using the `megalodon_extras aggregate run` command ([docs here](https://nanoporetech.github.io/megalodon/extras_aggregate.html)).

**Comment by PanZiwei** [comment]
Hi @marcus1487,
Thanks for your reply. Following your 1st answer,  is it possible to have 2 rows for a specific site, one is 5hmC in `mod_base` column, another one is 5mC in 'mod_base'? If so, how do I know the exactly modified state for the specific site? Thanks!

**Comment by marcus1487** [comment]
Yes it is possible to have both the probability of 5mC and the probability of 5hmC listed for a single reference site. This is done by design as these are both possibilities at any reference site. By default in the aggregation step Megalodon requires that the called base (modified or canonical) have a probability greater than 0.8 to count towards the aggregated total at that site. This per-read table is not meant to represent calls, but simply give users a text view of the raw data contributing to the aggregated values. For most users the aggregated data is the best downstream output file from Megalodon.
