### ISSUE TITLE
binary per_read_basecalls file

### ISSUE THREAD

**Issue by koenvandenberge** [nanoporetech/megalodon#81]
Hi,

We are calling m6A methylation using megalodon.
It is possible to create a TSV file using the megalodon output using the `megalodon_extras per_read_text modified_bases` command, where all bases are considered. The default call for methylation however seems to be >80% or <20%. I am wondering if it's possible to create a binary version (and therefore space efficient) of the file produced by `megalodon_extras per_read_text modified_bases`. Basically like the `megalodon_extras aggregate run` command, but without the aggregation.
Would you simply recommend post-processing the file obtained by `megalodon_extras per_read_text modified_bases` ?

**Comment by marcus1487** [comment]
You are looking for the per-read modified bases database. This is stored as the `per_read_modified_base_calls.db` file in the output directory. See [this comment](https://github.com/nanoporetech/megalodon/issues/76#issuecomment-749840101) for minimal use case to access the binary file.

**Comment by koenvandenberge** [comment]
Thank you @marcus1487.
I ended up using an awk script which seemed less involved, using the 20/80% methylation calls rule. I'll paste it here for reference.
`awk '(NR>1) && ($5 > -0.2231436) || ($5 < -1.609438) ' per_read_modified_base_calls.txt > per_read_modified_base_calls_binary.txt`

Best,
Koen

**Comment by marcus1487** [comment]
Ah I see you were looking for a binary file meaning having made the binary call between modified and canonical, not binary as in a binary disk storage format (to save space). 

This awk script will work for the 5mC model, but for more robust results (when using a model with more than 1 modified base; e.g. 5mC+5hmC) It might be better to check `($5 > -0.2231436) || ($6 > -0.2231436)`. This should match the aggregated results exactly for all models.
