### ISSUE TITLE
atomize_variants calls a function that doesn't exist

### ISSUE THREAD

**Issue by mglevy** [nanoporetech/megalodon#82]
I presume when you updated to using mappy you never changed the mapping.alignerPlus  reference in megladon_extras atomize_variants. I tried fiddling around but there doesn't appear to be an alignerPlus anywhere else in your code and I didn't see any obvious quick fix. Thoughts?

**Comment by marcus1487** [comment]
Yes. This is a bug. The `mappy.Aligner` used to be wrapped in the `meglaodon.mapping.alignerPlus` object, but this interface has been replace. This instance was missed. I will try to get a fix up shortly.

**Comment by marcus1487** [comment]
This should now be fixed in github. This will be included in the next release, but install with `pip install git+https://github.com/nanoporetech/megalodon.git` for now to test the functionality. Please re-open if this issue persists.
