### ISSUE TITLE
Which version of Guppy need?

### ISSUE THREAD

**Issue by xug15** [nanoporetech/megalodon#84]
megalodon rawdata/  --outputs basecalls mappings mod_mappings mods  --reference /home/xugang/data/reference/cp00357/GCF_000007045.1_ASM704v1_genomic.fa --mod-motif Z CG 0 --devices 0 1 --processes 10
[16:26:10] Running Megalodon version 2.2.9
[16:26:10] Loading guppy basecalling backend
******************** WARNING: Guppy and pyguppy minor versions do not match. This may lead to a failure. Please install matching Guppy and pyguppy versions.

 Guppy Basecall Service Software, (C) Oxford Nanopore Technologies, Limited. Version 4.2.2+effbaf8, client-server API version 3.2.0

**Comment by marcus1487** [comment]
The Guppy and pyguppy versions are printed in the `log.txt` file in the first several lines. By default the most current version of pyguppy is installed by pip. This matches the most current version of Guppy. If you would like to use an older version of guppy manually installing the matching pyguppy package is recommended. For example: `pip install ont-pyguppy-client-lib==4.2.2` should solve your current issue without changing guppy installations. I will add this recommendation as a note to this warning message.

**Comment by xug15** [comment]
Thanks!

I fixed the above problem, but a new error rise: my computer doesn't have gpu. 
Please tell me how to set the parameter: --devices 0 1 --processes 10

terminate called after throwing an instance of 'std::runtime_error'
  what():  This build does not support GPU basecalling mode.

**Comment by marcus1487** [comment]
The `--devices` argument specifies the GPU devices to use. If this argument is omitted Guppy will run on CPUs only. Note though that this is much slower (generally about 100X slower) than when using a GPU, so is not likely to scale well.
