### ISSUE TITLE
megalodon extra useage question

### ISSUE THREAD

**Issue by ruicatxiao** [nanoporetech/megalodon#87]
Hi,
I am trying to figure out how to use 2 of the megalodon extra  options. First is the describe_alphabet option. I gave it path to the rerio cfg file and it just states AttributeError: 'Namespace' object has no attribute 'output_directory'. I cannot find a proper documentation for this specific command on the documentation website.

Second is the split by motif command. I assume with latest version, m is mC while mh is 5hmC. I am interested in 6mA, what would be the single letter modified base for that? I cannot find it on the documentation either.

Thanks!

**Comment by marcus1487** [comment]
The `describe_alphabet` behavior is a bug. A fix for this has just been pushed to guthub and will be included in the next release. For now you can test describe alphabet command via an install from github (`pip install git+https://github.com/nanoporetech/megalodon` ). Thank you for the bug report!

For the modified base labels, we have moved to single letter codes as defined by hts-specs ([see here in pre-release](https://github.com/jkbonfield/hts-specs/blob/methylation/SAMtags.tex#L532)). This lists 5mC as `m`, 5hmC as `h` and 6mA as `a`. These are the values that the currently recommended Rerio models use. But using the describe_alphabet for a particular model is the best way to be sure to use the correct modified base single letter codes. Again thank you for that bug report.

**Comment by marcus1487** [comment]
Fixed and included in release `2.2.10`
