### ISSUE TITLE
Guppy Error: 'flow_cell_id' not found

### ISSUE THREAD

**Issue by al3xMlt** [nanoporetech/megalodon#88]
Hey, 
I'm using ont-guppy_4.2.2 to basecall multiple fast5 files. During basecalling with following command line: 
`~/ont-guppy_4.2.2/bin/guppy_basecaller -i {$fast5-input} -s {$output} --recursive --disable_pings --reverse_sequence true --u_substitution true --trim_strategy rna --flowcell FLO-MIN106 --kit SQK-RNA001  -x 'cuda:0' --chunks_per_runner 512 --gpu_runners_per_device 4 --num_callers 8` I got following error in the log file, here an example: **Error loading read "684f7b01-d72d-4f5d-a2b0-9d39669966db" from file " ./batch_0.fast5": Key 'flow_cell_id' not found** . Instead of flow_cell_id the multi (and the single) fast5 files say device_id. Is there an older version of guppy which could read those files? Or is there a way to fix it? 
Thanks in advance! 

.

**Comment by marcus1487** [comment]
This is an issue with Guppy and not Megalodon. Please contact technical support or post on the nanopore community for help with Guppy issues.
