### ISSUE TITLE
How to calculate the methylation frequency?

### ISSUE THREAD

**Issue by ligiamateiu** [nanoporetech/megalodon#89]
Hey, 
Is there a way to calculate the methylation frequency? 

Best,
Ligia

**Comment by marcus1487** [comment]
Could you elaborate a bit more on the statistic you aim to produce?

When megalodon is run with the `--outputs mods`, the per-reference site methylation frequencies are output in the standard bedmethyl format. See [docs here](https://nanoporetech.github.io/megalodon/file_formats.html#aggregated-modified-bases).

**Comment by ligiamateiu** [comment]
The information about bedMethyl file format is sufficient! :) I did not have the header for the generated bed file. Thank you.
