### ISSUE TITLE
counting repeat motif CGG

### ISSUE THREAD

**Issue by ligiamateiu** [nanoporetech/megalodon#90]
Hey,
I wonder if i can used megalodon to count CGG motifs.
Best,
Ligia

**Comment by marcus1487** [comment]
You could accomplish this with the `megalodon_extras modified_bases create_motif_bed` command. This will produce one line for each occurrence (per-strand) of the specified motif. You could also modify the code found in that command [here](https://github.com/nanoporetech/megalodon/blob/master/megalodon_extras/modified_bases_create_motif_bed.py), to simply perform the counting.
