### ISSUE TITLE
Error connecting to Guppy server

### ISSUE THREAD

**Issue by zhengdafangyuan** [nanoporetech/megalodon#91]
Hi,  below are the environment and command I performed the megalodon to call 5mC methylation, and the error messages I got.  Could you help me to fix it? Thank you.

Environment:
Ubuntu 16.04
Megalodon version: 2.2.1
Guppy Basecalling Software (guppy_basecaller):  Version 4.4.1+1c81d62
Guppy Basecall Service Software (guppy_basecall_server) : Version 4.4.1+1c81d62, client-server API version 5.0.0
CUDA Version 11.0.207

Command :
`THREAD=20

OUTDIR="/data1/ONTmethylation/test/output"

RAWDIR="/data1/ONTmethylation/test"

REFDIR="/data1/human_genome"

megalodon \
    $RAWDIR \
    --guppy-params "-d /home/zyserver/software/rerio/basecall_models" \
    --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg \
    --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server \
    --reference ${REFDIR}/GCA_000001405.15_GRCh38_no_alt_analysis_set.mmi \
    --mod-motif m CG 0 \
    --outputs basecalls mappings mod_mappings mods \
    --output-directory $OUTDIR  --overwrite \
    --devices 0 1 --processes $THREAD`

Error Message:
" 
DBG 18:03:06 : guppy server init command: "/opt/ont/guppy/bin/guppy_basecall_server -p auto -l /data1/ONTmethylation/test/output/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --post_out -x cuda:0 -d /home/zyserver/software/rerio/basecall_models" --- MainProcess-MainThread backends.py:530
****************************************************************************************************
	ERROR: Error connecting to Guppy server. Server unavailable.
**************************************************************************************************** 
"

**Comment by marcus1487** [comment]
Could you provide the output of the standalone guppy server init command: `/opt/ont/guppy/bin/guppy_basecall_server -p auto -l /data1/ONTmethylation/test/output/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --post_out -x cuda:0 -d /home/zyserver/software/rerio/basecall_models`

**Comment by zhengdafangyuan** [comment]
From the previous [issue](https://github.com/nanoporetech/megalodon/issues/83), we thought it might be the problem of PyguppyClient, and after the pyguppyclient installed `pip install pyguppyclient` ,  it works now.
