### ISSUE TITLE
Probabilities in vcf, bam files and output from database API and Ml tag in bam file

### ISSUE THREAD

**Issue by daggoo** [nanoporetech/megalodon#93]
Hello @marcus1487! Could you please tell me how probabilities for base modification are represented in the vcf files, bam files and in the output from the database API. I understand that the probabilities in the database API output are natural log. But what about probabilities in the vcf file and in the bam file?
Could you please also tell me whether it is correct that Ml tag contains relative base positions when only canonical bases are counted as in the second example in the [hts-seq specs page](https://github.com/samtools/hts-specs/pull/418)?

**Comment by marcus1487** [comment]
The BAM tag specification is described in the draft hts-spec. Here is the [relevant section in the current draft](https://github.com/jkbonfield/hts-specs/blob/methylation/SAMtags.tex#L477). This is as you noted the second example on the top of the proposed format.

In the VCF file, the per-read calls are requested in the mods VCF output via the `--write-mod-log-probs` argument. As such the per-read probabilities are stored as log probabilities. The VCF quality field is ill-defined in this modified base context, but attempts to agree with the standard definition of the field in the VCF format ([see here](https://github.com/nanoporetech/megalodon/blob/2.2.10/megalodon/mods.py#L1834) for the programatic computation for the quality field). The recommended aggregated output from the VCF field is the sample modified base attribute (`m` for 5mC). This field shows the estimated fraction of modified bases at each "variant site" (really a potential modified base site). The `DP` and `VALID_DP` fields (also found in the `SAMPLE` field) give the read depth and valid depth (after removing modified base or canonical calls with low probability) that go into the fraction modified computation.

Hopefully this helps clear up the specification, but please post if further clarification would be helpful.
