### ISSUE TITLE
Default values for --guppy-timeout

### ISSUE THREAD

**Issue by MrKevinDC** [nanoporetech/megalodon#95]
I was writing to ask what are the default values of `--guppy-timeout` and `--reads-per-guppy-batch`, since there seems to be some conflict in the documentation:

According to [this](https://nanoporetech.github.io/megalodon/advanced_arguments.html#guppy-backend-argument):

> --guppy-timeout
> 
>     Timeout to wait for guppy server to call a single read in seconds.
> 
>     Default: 5.0

However in [most places](https://github.com/nanoporetech/megalodon#:~:text=Finally%20the%20%2D%2Dguppy%2Dtimeout,per%20batch%20of%2050%20reads) it is indicated such as: 

> Finally the --guppy-timeout arguments ensures that a run will not stall on a small number of reads taking a very long time (default 30 seconds per batch of 50 reads). The Pyguppy get completed reads invalid error "Something went wrong. return_code: result.failed" error indicate that the Guppy server is overwhelmed. Consider lowering the --processes and/or --reads-per-guppy-batch values to reduce these errors. Finding the right balance for these parameters can help achieve optimal performance on a system.

Which is `true`?

**Comment by marcus1487** [comment]
The most reliable place to look for the default values is the command line defaults (via `megalodon --help-long`). This shows the default as `30`. I will try to address the other locations with incorrect default values in the docs.
