### ISSUE TITLE
Detect 5hmC hydroxymethylation

### ISSUE THREAD

**Issue by colindaven** [nanoporetech/megalodon#97]
Hello,

we're interested in 5hmC hydroxymethylation using ONT data. I'm struggling to find tools which can do this. Is megalodon suitable or do you have any other recommendations? 

Thanks.
Colin

**Comment by marcus1487** [comment]
There is a research 5hmC model in the [Rerio repository](https://github.com/nanoporetech/rerio). Once these models have been validated further they will be moved into the Guppy product, but for now we make the 5hmC model available via the Rerio repository.

Given this 5hmC model, megalodon is the recommended tool to extract the highest accuracy modified base calls utilizing this model.

Best of luck in your research!
