### ISSUE TITLE
Reads are not being processed

### ISSUE THREAD

**Issue by dipannita-g** [nanoporetech/megalodon#99]
I tried running Megalodon with and without the Guppy basecaller (input files from a separate Guppy run with posterior matrix in fast5 in this case) but both the times, majority of my reads are not getting processed.

**When Megalodon is run with Guppy in background:**
```
$ megalodon \
barcode01/ \
--guppy-config dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg \
--guppy-server-path /usr/bin/guppy_basecall_server \
--outputs mod_mappings \
--reference reference.fasta
```

Here the total read count is 17793, out of which, 12102 reads say "Guppy server unable to receive read" and 4775 reads say "Guppy server timeout (see --guppy-timeout argument)".

**When Guppy and Megalodon are run separately:**

`$ guppy_basecaller -i barcode01/ -s out/ -c /opt/ont/guppy/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --qscore_filtering --min_qscore 7 --post_out --fast5_out
`
`$ megalodon /home/akhilesh/out/workspace/ --guppy-config /opt/ont/guppy/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg --do-not-use-guppy-server --outputs mod_mappings --reference reference.fasta --processes 8`

Here all the 17793 reads say "unexpected error". I have uploaded the log file for this. 
[log.txt](https://github.com/nanoporetech/megalodon/files/6014399/log.txt)

Please help me figure out how to resolve this issue. I am using CPU for the analysis.  Here are the details:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              36
On-line CPU(s) list: 0-35
Thread(s) per core:  2
Core(s) per socket:  18
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz
Stepping:            4
CPU MHz:             1200.405
CPU max MHz:         3700.0000
CPU min MHz:         1200.0000
BogoMIPS:            5400.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            25344K
NUMA node0 CPU(s):   0-35
```

**Comment by marcus1487** [comment]
For the first part running Guppy within megalodon, it is highly discouraged to run guppy without GPU compute resources. In order to run in this mode I would recommend setting the following settings: `--guppy-timeout 300 --reads-per-guppy-batch 10`, but note that run times are expected to be on the order of 100 times slower.

For the second part, this is a real bug. The FAST5 mode is not well tested/maintained. I'll try to have a fix in the next release for this.

**Comment by dipannita-g** [comment]
Hi Marcus,

I have managed to get output files. Thanks for the recommendation! Yes, the processing time is slow but manageable for now.

I also wanted to know if there are ways to get the ROC curves for Megalodon outputs, similar to what ont-tombo generates?

**Comment by marcus1487** [comment]
Glad you have gotten going now!

For the ROC curves, have a look at the `megalodon_extras validate` set of commands. There are commands for creating ROC and precision-recall curves for both per-read and aggregated calls. See more info in the [docs here](https://nanoporetech.github.io/megalodon/extras_validate.html).
